# -*- coding: utf-8 -*-
"""CT-1 — generates the reviewer's interface, one self-contained page per slot.

    python scripts/ct1/review_app.py --batch core/ml/review/ct1_review_batch_002

Output is a single HTML file per reviewer slot with that slot's items embedded.
No server, no build step, no network: a reviewer opens the file, answers, and
presses Export. That is not minimalism for its own sake — a review tool that
needs infrastructure to run is a review tool that does not get run, and the
whole CT-1 gate is blocked on somebody actually doing this work.

## What the page must not contain, and why it is tested rather than intended

The page is what a reviewer sees, so it is where blindness either holds or
fails. It carries the catalogue content and the question vocabulary. It does
NOT carry: the deterministic baseline's verdict for the row, the name of any
rule that fired, any model prediction or score, any other reviewer's answer, or
the fact that the row is also assigned to somebody else.

Each of those leaks the same way: it converts the reviewer from someone
producing an independent label into someone confirming or contesting an existing
one, and a confirmation rate is not a label. ``test_review_app`` scans the
GENERATED BYTES for the vocabulary rather than trusting this docstring, because
the failure mode is a template picking up a field somebody added upstream.

## What it stores

``localStorage``, keyed by batch and slot, written on every change. A reviewer
gets through 180 rows over more than one sitting, and losing an afternoon's work
to a closed tab is how a batch stops being finished. Export writes a submission
file that ``review_import`` validates; the page itself validates nothing beyond
prompting, because a page that silently corrects a submission is a page that
decides what the label is.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from review_batch import (  # noqa: E402
    REASON_CODES,
    assert_authoritative,
    check_contract,
    REVIEW_QUESTIONS,
    REVIEW_SCHEMA_VERSION,
    VERDICTS,
)

#: What each question means, in the words a reviewer reads.
#:
#: Every one is a comparison between two things visible on the page. None asks
#: whether the exercise is safe, appropriate, advisable or correct for anybody:
#: that is clinical authority, it is unreachable from this repository by
#: construction (see ``label_contract.CLINICALLY_VALIDATED_LABEL``), and a
#: question that invites the answer is exactly how a content label gets read as
#: a clinical one later. Section 9 and 10 of the brief; D1 and H3.
QUESTION_TEXT = {
    "title_matches_content": (
        "Does the title describe the movement the steps actually describe?"
    ),
    "content_is_complete": (
        "Are the steps a complete description, with nothing obviously missing "
        "or cut off mid-sentence?"
    ),
    "structure_is_consistent": (
        "Are the steps well formed — in a sensible order, not repeated, not "
        "broken formatting?"
    ),
    "instructions_are_consistent": (
        "Do the steps and tips agree with each other, rather than telling the "
        "reader two different things?"
    ),
    "content_is_not_duplicated": (
        "Is this text specific to this entry, rather than copied from another "
        "entry or repeated inside this one?"
    ),
    "equipment_matches_content": (
        "Does the listed equipment match the equipment the steps use?"
    ),
    "localisation_is_faithful": (
        "Does the Russian text say the same thing as the English, and is it "
        "actually translated?"
    ),
    "metadata_matches_content": (
        "Do the muscles, difficulty and stretch flag match what the steps "
        "describe?"
    ),
}

VERDICT_TEXT = {
    "ok": "OK",
    "problem": "Problem",
    "unsure": "Unsure",
}

REASON_TEXT = {
    "steps_missing": "Steps missing entirely",
    "steps_truncated": "Steps cut off / incomplete",
    "steps_out_of_order": "Steps in the wrong order",
    "steps_contradict_each_other": "Steps or tips contradict each other",
    "title_describes_different_movement": "Title is a different movement",
    "duplicate_of_another_row": "Copied from another entry",
    "duplicate_text_within_row": "Text repeated inside this entry",
    "equipment_not_used_by_steps": "Listed equipment is never used",
    "equipment_required_but_absent": "Steps need equipment that is not listed",
    "translation_missing": "Russian text missing",
    "translation_left_in_source_language": "Russian text is still English",
    "translation_changes_meaning": "Russian text says something else",
    "muscles_do_not_match_content": "Muscles do not match the movement",
    "difficulty_does_not_match_content": "Difficulty does not match",
    "formatting_broken": "Broken formatting / markup / encoding",
    "other": "Something else (write a note)",
}


def _payload(slot: str, batch_id: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    """Exactly what the page is allowed to know.

    Built by naming the permitted fields rather than by removing forbidden ones.
    A denylist over an upstream dict leaks every field added after it was
    written; an allowlist fails closed, and the failure is a missing field
    somebody notices immediately rather than a leak nobody notices at all.
    """
    return {
        "batch_id": batch_id,
        "review_schema_version": REVIEW_SCHEMA_VERSION,
        "slot": slot,
        "questions": [
            {"id": q, "text": QUESTION_TEXT[q]} for q in REVIEW_QUESTIONS
        ],
        "verdicts": [{"id": v, "text": VERDICT_TEXT[v]} for v in VERDICTS],
        "reasons": [{"id": r, "text": REASON_TEXT[r]} for r in REASON_CODES],
        "items": [
            {
                "item_id": i["item_id"],
                "source_content_version": i["source_content_version"],
                "title": i.get("title"),
                "summary": i.get("summary"),
                "steps": list(i.get("steps") or []),
                "tips": list(i.get("tips") or []),
                "equipment_id": i.get("equipment_id"),
                "muscles": list(i.get("muscles") or []),
                "difficulty": i.get("difficulty"),
                "is_stretch": bool(i.get("is_stretch")),
                "ru": i.get("ru"),
            }
            for i in items
        ],
    }


CSS = """
:root{--bg:#fbfaf7;--fg:#1c1b19;--muted:#6b6862;--line:#ddd9d1;--card:#fff;
--ok:#2f6b45;--prob:#8c3222;--uns:#6b5a2f;--accent:#33506e}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.55 ui-sans-serif,system-ui,"Segoe UI",Roboto,sans-serif}
header{position:sticky;top:0;z-index:5;background:var(--card);
border-bottom:1px solid var(--line);padding:10px 16px;display:flex;
gap:16px;align-items:center;flex-wrap:wrap}
h1{font-size:15px;margin:0;font-weight:650;letter-spacing:.01em}
.grow{flex:1}
.muted{color:var(--muted)}
.wrap{display:grid;grid-template-columns:220px minmax(0,1fr);gap:0;
align-items:start}
nav{border-right:1px solid var(--line);height:calc(100vh - 46px);
overflow:auto;position:sticky;top:46px;background:var(--card)}
nav button{display:block;width:100%;text-align:left;border:0;background:none;
padding:6px 12px;font:inherit;font-size:13px;cursor:pointer;
border-left:3px solid transparent;color:var(--muted)}
nav button.done{color:var(--fg)}
nav button.cur{border-left-color:var(--accent);background:#eef2f6;color:var(--fg)}
main{padding:20px 24px 80px;max-width:74ch}
section{background:var(--card);border:1px solid var(--line);border-radius:6px;
padding:16px 18px;margin:0 0 16px}
h2{font-size:19px;margin:0 0 4px}
h3{font-size:12px;text-transform:uppercase;letter-spacing:.08em;
color:var(--muted);margin:16px 0 6px;font-weight:650}
ol,ul{margin:0;padding-left:22px}
li{margin:3px 0}
dl{display:grid;grid-template-columns:auto 1fr;gap:2px 12px;margin:0;
font-size:14px}
dt{color:var(--muted)}
dd{margin:0}
.q{border-top:1px solid var(--line);padding:10px 0}
.q:first-of-type{border-top:0}
.q p{margin:0 0 6px}
.opts{display:flex;gap:8px;flex-wrap:wrap}
.opts label{border:1px solid var(--line);border-radius:14px;padding:3px 12px;
cursor:pointer;font-size:14px;user-select:none}
.opts input{position:absolute;opacity:0;pointer-events:none}
.opts input:focus-visible+span{outline:2px solid var(--accent);outline-offset:3px}
.opts label:has(input[value=ok]:checked){background:var(--ok);color:#fff;
border-color:var(--ok)}
.opts label:has(input[value=problem]:checked){background:var(--prob);color:#fff;
border-color:var(--prob)}
.opts label:has(input[value=unsure]:checked){background:var(--uns);color:#fff;
border-color:var(--uns)}
.reasons{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));
gap:2px 14px;font-size:14px}
.reasons label{cursor:pointer}
textarea{width:100%;min-height:72px;font:inherit;padding:8px;
border:1px solid var(--line);border-radius:4px;background:var(--bg);
color:var(--fg);resize:vertical}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:12px}
button.act{font:inherit;padding:6px 14px;border-radius:4px;cursor:pointer;
border:1px solid var(--line);background:var(--card);color:var(--fg)}
button.act.primary{background:var(--accent);color:#fff;border-color:var(--accent)}
:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
@media (prefers-color-scheme:dark){
:root{--bg:#16181a;--fg:#e8e6e1;--muted:#9a968e;--line:#33363a;--card:#1e2124;
--ok:#4e9a6b;--prob:#c05a45;--uns:#a3894b;--accent:#7aa2c8}
nav button.cur{background:#242a31}
}
"""

JS = r"""
const P = JSON.parse(document.getElementById('payload').textContent);
const KEY = 'ct1:' + P.batch_id + ':' + P.slot;
let state = {};
try { state = JSON.parse(localStorage.getItem(KEY) || '{}'); } catch (e) { state = {}; }
let cur = 0;

// Quotes are escaped too, although no vendor-controlled value currently
// reaches an attribute. Every `="${...}"` slot below interpolates a code
// constant or a loop index, and a test pins those vocabularies to
// `[a-z][a-z0-9_]*` so a quote cannot appear in one -- that is what makes the
// attribute contexts safe. This is the belt: it means the property survives
// somebody adding a catalogue field to an attribute later, rather than
// depending on nobody doing so.
const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g,
  c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function rec(id) {
  if (!state[id]) state[id] = { answers: {}, reason_codes: [], note: '',
                                needs_domain_review: false, review_status: null };
  return state[id];
}
function complete(id) {
  const r = state[id];
  if (!r) return false;
  if (r.review_status === 'SKIPPED') return true;
  return P.questions.every(q => r.answers[q.id]);
}
function save() { localStorage.setItem(KEY, JSON.stringify(state)); paintNav(); }

function paintNav() {
  const n = document.getElementById('nav');
  n.innerHTML = P.items.map((it, i) =>
    `<button data-i="${i}" class="${complete(it.item_id) ? 'done' : ''} ${i === cur ? 'cur' : ''}">`
    + `${i + 1}. ${esc(it.title || it.item_id)}</button>`).join('');
  const done = P.items.filter(it => complete(it.item_id)).length;
  document.getElementById('progress').textContent =
    done + ' / ' + P.items.length + ' answered';
}

function paint() {
  const it = P.items[cur], r = rec(it.item_id);
  const ru = it.ru || {};
  const list = (label, arr) => (arr && arr.length)
    ? `<h3>${label}</h3><ol>${arr.map(s => `<li>${esc(s)}</li>`).join('')}</ol>` : '';
  document.getElementById('content').innerHTML =
    `<h2>${esc(it.title)}</h2>`
    + `<p class="muted">${esc(it.item_id)}</p>`
    + (it.summary ? `<p>${esc(it.summary)}</p>` : '')
    + list('Steps', it.steps)
    + ((it.tips && it.tips.length)
        ? `<h3>Tips</h3><ul>${it.tips.map(s => `<li>${esc(s)}</li>`).join('')}</ul>` : '')
    + `<h3>Metadata</h3><dl>`
    + `<dt>Equipment</dt><dd>${esc(it.equipment_id) || '<span class="muted">none</span>'}</dd>`
    + `<dt>Muscles</dt><dd>${esc((it.muscles || []).join(', ')) || '<span class="muted">none</span>'}</dd>`
    + `<dt>Difficulty</dt><dd>${esc(it.difficulty) || '<span class="muted">none</span>'}</dd>`
    + `<dt>Stretch</dt><dd>${it.is_stretch ? 'yes' : 'no'}</dd></dl>`
    + `<h3>Russian</h3>`
    + (Object.keys(ru).length
        ? `<p><b>${esc(ru.title)}</b></p>` + (ru.summary ? `<p>${esc(ru.summary)}</p>` : '')
          + list('', ru.steps)
        : `<p class="muted">no Russian row</p>`);

  document.getElementById('questions').innerHTML = P.questions.map(q =>
    `<div class="q"><p>${esc(q.text)}</p><div class="opts">`
    + P.verdicts.map(v =>
        `<label><input type="radio" name="${q.id}" value="${v.id}"`
        + `${r.answers[q.id] === v.id ? ' checked' : ''}><span>${esc(v.text)}</span></label>`
      ).join('')
    + `</div></div>`).join('');

  document.getElementById('reasons').innerHTML = P.reasons.map(c =>
    `<label><input type="checkbox" value="${c.id}"`
    + `${r.reason_codes.includes(c.id) ? ' checked' : ''}> ${esc(c.text)}</label>`).join('');

  document.getElementById('note').value = r.note || '';
  document.getElementById('domain').checked = !!r.needs_domain_review;
  document.getElementById('pos').textContent = (cur + 1) + ' of ' + P.items.length;
  paintNav();
  window.scrollTo(0, 0);
}

document.getElementById('nav').addEventListener('click', e => {
  const b = e.target.closest('button'); if (!b) return;
  cur = +b.dataset.i; paint();
});
document.getElementById('questions').addEventListener('change', e => {
  const r = rec(P.items[cur].item_id);
  r.answers[e.target.name] = e.target.value;
  r.review_status = 'COMPLETE';
  save();
});
document.getElementById('reasons').addEventListener('change', () => {
  const r = rec(P.items[cur].item_id);
  r.reason_codes = [...document.querySelectorAll('#reasons input:checked')].map(i => i.value);
  save();
});
document.getElementById('note').addEventListener('input', e => {
  rec(P.items[cur].item_id).note = e.target.value; save();
});
document.getElementById('domain').addEventListener('change', e => {
  rec(P.items[cur].item_id).needs_domain_review = e.target.checked; save();
});
document.getElementById('skip').addEventListener('click', () => {
  const r = rec(P.items[cur].item_id);
  r.review_status = 'SKIPPED'; r.answers = {};
  save(); paint();
});
document.getElementById('prev').addEventListener('click', () => {
  if (cur > 0) { cur--; paint(); }
});
document.getElementById('next').addEventListener('click', () => {
  if (cur < P.items.length - 1) { cur++; paint(); }
});

document.getElementById('export').addEventListener('click', () => {
  const now = new Date().toISOString();
  const reviews = [];
  for (const it of P.items) {
    const r = state[it.item_id];
    if (!r || !r.review_status) continue;   // never opened: stays UNKNOWN
    const status = r.review_status === 'SKIPPED' ? 'SKIPPED'
      : (P.questions.every(q => r.answers[q.id]) ? 'COMPLETE' : null);
    if (!status) continue;                  // partially answered: not a review
    reviews.push({
      item_id: it.item_id,
      source_content_version: it.source_content_version,
      review_timestamp: r.at || now,
      review_status: status,
      answers: status === 'SKIPPED' ? {} : r.answers,
      reason_codes: r.reason_codes || [],
      note: r.note || '',
      needs_domain_review: !!r.needs_domain_review
    });
  }
  const who = document.getElementById('who').value.trim();
  const out = {
    batch_id: P.batch_id,
    review_schema_version: P.review_schema_version,
    reviewer: who,
    reviewer_slot: P.slot,
    reviewer_kind: 'HUMAN',
    submitted_at: now,
    reviews: reviews
  };
  const text = JSON.stringify(out, null, 2);
  const box = document.getElementById('out');
  box.value = text; box.hidden = false; box.select();
  const a = document.getElementById('dl');
  a.href = URL.createObjectURL(new Blob([text], { type: 'application/json' }));
  a.download = P.batch_id + '.' + (who || P.slot) + '.json';
  a.hidden = false;
  document.getElementById('exportnote').textContent =
    reviews.length + ' of ' + P.items.length + ' rows returned. Rows you did '
    + 'not open are absent from the file and count as NOT REVIEWED, not as clean.';
});

paint();
"""


def render(slot: str, batch_id: str, items: list[dict[str, Any]]) -> str:
    payload = json.dumps(_payload(slot, batch_id, items), ensure_ascii=False)
    # `</script>` inside catalogue text would close the block early; `<` is
    # escaped rather than the exact sequence, because the exact sequence is one
    # of several that terminate a script element and the others are easy to
    # forget. JSON parses < identically.
    payload = payload.replace("<", "\\u003c").replace("&", "\\u0026")
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CT-1 content review — {slot}</title>
<style>{CSS}</style>
</head>
<body>
<header>
  <h1>CT-1 content review</h1>
  <span class="muted">{batch_id} &middot; slot {slot}</span>
  <span class="grow"></span>
  <span id="progress" class="muted"></span>
</header>
<div class="wrap">
<nav id="nav" aria-label="Items"></nav>
<main>
  <section id="content"></section>
  <section>
    <div id="questions"></div>
    <h3>What is wrong (tick all that apply)</h3>
    <div id="reasons" class="reasons"></div>
    <h3>Note</h3>
    <textarea id="note" placeholder="Anything a reason code does not cover. Required if you tick &ldquo;Something else&rdquo;."></textarea>
    <div class="row">
      <label><input type="checkbox" id="domain"> Needs someone with domain
      knowledge to look at this</label>
    </div>
    <div class="row">
      <button class="act" id="prev">&larr; Previous</button>
      <button class="act" id="next">Next &rarr;</button>
      <span id="pos" class="muted"></span>
      <span class="grow"></span>
      <button class="act" id="skip">Skip this row</button>
    </div>
  </section>
  <section>
    <h3>Finish</h3>
    <div class="row">
      <label>Your name <input id="who" size="24" placeholder="first and last"></label>
      <button class="act primary" id="export">Export submission</button>
      <a id="dl" class="act" hidden>Download</a>
    </div>
    <p id="exportnote" class="muted"></p>
    <textarea id="out" hidden readonly></textarea>
  </section>
</main>
</div>
<script type="application/json" id="payload">{payload}</script>
<script>{JS}</script>
</body>
</html>
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--batch", required=True, help="the batch directory")
    ap.add_argument("--out", default=None, help="defaults to <batch>/app")
    args = ap.parse_args(argv)

    batch = Path(args.batch)
    manifest = json.loads((batch / "manifest.json").read_text(encoding="utf-8"))
    # Dealing pages from a superseded batch would send a reviewer rows whose
    # assignments are not the live ones, and their submission would be refused
    # on import -- after the work had already been done.
    check_contract(manifest)
    assert_authoritative(manifest)
    items = json.loads((batch / "items.json").read_text(encoding="utf-8"))
    assignments = json.loads(
        (batch / "assignments.json").read_text(encoding="utf-8")
    )
    by_id = {i["item_id"]: i for i in items}

    out = Path(args.out) if args.out else batch / "app"
    out.mkdir(parents=True, exist_ok=True)
    for slot, ids in sorted(assignments["packages"].items()):
        page = render(slot, manifest["batch_id"], [by_id[i] for i in ids])
        path = out / f"review_{slot}.html"
        path.write_text(page, encoding="utf-8")
        print(f"{slot}: {len(ids):>3} items  ->  {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
