# -*- coding: utf-8 -*-
"""CT-1 review interface: blindness, asserted against the generated bytes.

    python -m pytest scripts/ct1/test_review_app.py -q

The page is what a reviewer actually sees, so it is where blindness either
holds or fails. Everything upstream can be correct and the leak still happens
here — a template picking up a field somebody added to the item dict, a debug
line, a helpful tooltip.

So these tests read the RENDERED HTML rather than the payload builder. A test
that checks the intermediate structure proves the intermediate structure.
"""
from __future__ import annotations

import json
import re

from baseline import run_checks
from review_batch import REASON_CODES, REVIEW_QUESTIONS, assign, select
from review_app import QUESTION_TEXT, render
from test_review_batch import _corpus


PAYLOAD_RE = re.compile(
    r'<script type="application/json" id="payload">(.*?)</script>', re.S
)


def _raw_payload(html: str) -> str:
    return PAYLOAD_RE.search(html).group(1)


def _payload(html: str) -> dict:
    # No unescaping step. `render` emits those characters as JSON escapes,
    # which a parser decodes on its own -- and that the payload survives a
    # real parser is part of what these tests check.
    return json.loads(_raw_payload(html))


def _pages():
    en, ru, eq = _corpus()
    batch = select(en, ru, eq, size=60)
    a = assign(batch["items"])
    by_id = {i["item_id"]: i for i in batch["items"]}
    return batch, a, {
        slot: render(slot, batch["manifest"]["batch_id"], [by_id[i] for i in ids])
        for slot, ids in a["packages"].items()
    }


#: Every check name the deterministic baseline can produce on this fixture.
#: Derived from the baseline rather than hand-listed, so a rule added later is
#: covered without anybody remembering to add it here.
def _rule_vocabulary():
    en, ru, eq = _corpus()
    return {l.check.split(":", 1)[0] for l in run_checks(en, ru, eq)}


# --------------------------------------------------------------------------
# section 7 — the four things the page may not show
# --------------------------------------------------------------------------


def test_the_page_never_names_a_rule_that_fired():
    _, _, pages = _pages()
    vocabulary = _rule_vocabulary()
    assert vocabulary, "the fixture fires no rules, so this test proves nothing"
    for slot, html in pages.items():
        low = html.lower()
        for rule in vocabulary:
            assert rule not in low, f"{slot} names the rule {rule!r}"


def test_the_page_carries_no_baseline_verdict_model_output_or_score():
    _, _, pages = _pages()
    forbidden = (
        "baseline", "heuristic", "auto_heuristic", "prediction", "predicted",
        "confidence", "probability", "score", "flagged", "sealed",
        "model_prediction", "champion", "challenger", "likelihood",
    )
    for slot, html in pages.items():
        low = html.lower()
        for word in forbidden:
            assert word not in low, f"{slot} contains {word!r}"


def test_the_page_does_not_reveal_that_a_row_is_double_reviewed():
    _, assignments, pages = _pages()
    assert assignments["secondary"], "nothing is doubled, so this proves nothing"
    for slot, html in pages.items():
        low = html.lower()
        for word in ("double", "second reviewer", "overlap", "agreement",
                     "adjudicat", "kappa"):
            assert word not in low, f"{slot} contains {word!r}"


def test_the_page_carries_no_other_reviewers_answer():
    """The payload is built by allowlist, so this asserts the outcome: the
    only reviewer named anywhere in a page is the slot it belongs to."""
    _, assignments, pages = _pages()
    for slot, html in pages.items():
        for other in assignments["slots"]:
            if other == slot:
                continue
            assert re.search(rf"\b{other}\b", html) is None, \
                f"{slot} mentions {other}"


def test_the_page_carries_only_the_rows_its_slot_was_dealt():
    batch, assignments, pages = _pages()
    for slot, html in pages.items():
        assert [i["item_id"] for i in _payload(html)["items"]] == \
            assignments["packages"][slot]


# --------------------------------------------------------------------------
# sections 9 and 10 — the clinical boundary, in the prose the reviewer reads
# --------------------------------------------------------------------------


def test_no_question_the_reviewer_reads_asks_about_safety():
    """`test_review_batch` checks the question NAMES. This checks the words
    they are asked in, which is where the smuggling would actually happen."""
    forbidden = ("safe", "unsafe", "risk", "injur", "contraindicat", "clinic",
                 "danger", "harm", "medical", "advisab", "appropriate for",
                 "should anyone", "healthy")
    for question, text in QUESTION_TEXT.items():
        for word in forbidden:
            assert word not in text.lower(), \
                f"{question} asks about {word!r}: {text!r}"


def test_the_rendered_page_asks_no_clinical_question():
    _, _, pages = _pages()
    for slot, html in pages.items():
        low = html.lower()
        for word in ("is this exercise safe", "injury risk", "contraindicat",
                     "medically", "clinically"):
            assert word not in low, f"{slot} asks {word!r}"


def test_every_question_is_asked_in_words_and_every_word_belongs_to_a_question():
    assert set(QUESTION_TEXT) == set(REVIEW_QUESTIONS)
    for text in QUESTION_TEXT.values():
        assert text.endswith("?"), f"{text!r} is not a question"


# --------------------------------------------------------------------------
# what the page must contain to be usable at all
# --------------------------------------------------------------------------


def test_the_page_shows_the_content_a_reviewer_needs_to_judge_the_row():
    batch, assignments, pages = _pages()
    slot = sorted(pages)[0]
    first = _payload(pages[slot])["items"][0]
    for field in ("title", "summary", "steps", "tips", "equipment_id",
                  "muscles", "difficulty", "is_stretch", "ru",
                  "source_content_version"):
        assert field in first, f"a reviewer cannot judge the row without {field}"


def test_every_answer_the_page_offers_is_one_the_importer_accepts():
    """And every answer the importer accepts is reachable in the UI.

    Both directions. A code the page cannot produce is dead vocabulary; a code
    the page produces and the importer rejects loses a reviewer's work at the
    last step, after the effort has been spent.
    """
    _, _, pages = _pages()
    payload = _payload(pages[sorted(pages)[0]])
    assert [c["id"] for c in payload["reasons"]] == list(REASON_CODES)
    assert [v["id"] for v in payload["verdicts"]] == ["ok", "problem", "unsure"]
    assert [q["id"] for q in payload["questions"]] == list(REVIEW_QUESTIONS)


def test_the_page_is_self_contained():
    """No server, no CDN, no build step. A review tool that needs
    infrastructure is a review tool that does not get run, and this gate is
    blocked on the work actually being done."""
    _, _, pages = _pages()
    for slot, html in pages.items():
        assert "http://" not in html
        assert "https://" not in html
        assert "<script src=" not in html
        assert 'rel="stylesheet"' not in html


def test_the_export_records_the_slot_and_the_content_version():
    """Both are what the importer needs; a page that omits either produces
    submissions the importer must refuse."""
    _, _, pages = _pages()
    html = pages[sorted(pages)[0]]
    assert "reviewer_slot: P.slot" in html
    assert "source_content_version: it.source_content_version" in html
    assert "reviewer_kind: 'HUMAN'" in html


def test_a_row_the_reviewer_never_opened_is_absent_from_the_export():
    """Section 48. It must come back as an UNKNOWN, which the importer counts
    as NOT_RETURNED -- not as a clean row."""
    _, _, pages = _pages()
    html = pages[sorted(pages)[0]]
    assert "if (!r || !r.review_status) continue;" in html
    assert "NOT REVIEWED, not as clean" in html


def test_catalogue_text_cannot_close_the_payload_script_block():
    """A row containing `</script>` would otherwise end the JSON early and
    execute the rest of the catalogue as markup."""
    batch, _, _ = _pages()
    poisoned = dict(batch["items"][0])
    poisoned["title"] = "Bench </script><img src=x onerror=alert(1)> press"
    body = _raw_payload(render("R1", "B", [poisoned]))
    assert "<" not in body
    # The text survives, escaped, rather than vanishing: a sanitiser that
    # deletes catalogue content shows the reviewer something the catalogue does
    # not contain, which is a different defect with the same appearance.
    assert "onerror" in body
    assert json.loads(body)["items"][0]["title"].startswith(
        "Bench </script>"
    )
