import 'dart:convert';

import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:flutter/services.dart' show rootBundle;

/// Free-text machine name -> catalog equipmentId.
///
/// This is the "registry index" half of the recognition pipeline: whatever
/// produces a machine name — the cloud recogniser answering in prose, the
/// on-device model's label, a future search box — resolves it here, offline,
/// in microseconds. The data lives in `assets/data/equipment_aliases.json`
/// (en + ru aliases per id, all lowercase), generated by
/// `scripts/catalog/build_registry.py` which asserts no alias is claimed by
/// two ids.
class EquipmentAliasIndex {
  EquipmentAliasIndex._(this._exact);

  /// Normalised alias -> equipmentId.
  final Map<String, String> _exact;

  static Future<EquipmentAliasIndex> load() async {
    final raw = await rootBundle.loadString('assets/data/equipment_aliases.json');
    return fromJson((jsonDecode(raw) as Map).cast<String, dynamic>());
  }

  @visibleForTesting
  static EquipmentAliasIndex fromJson(Map<String, dynamic> json) {
    final exact = <String, String>{};
    json.forEach((id, aliases) {
      for (final a in (aliases as List).cast<String>()) {
        exact[normalise(a)] = id;
      }
    });
    return EquipmentAliasIndex._(exact);
  }

  /// Lowercase, ё->е, punctuation to spaces, collapsed whitespace — so
  /// "Гакк-Машина!", "гакк машина" and "ёлка/елка" variants all meet the
  /// same key. Keep in sync with the generator, which lowercases too.
  static String normalise(String s) => s
      .toLowerCase()
      .replaceAll('ё', 'е')
      .replaceAll(RegExp(r'[^a-zа-я0-9]+'), ' ')
      .trim();

  /// Resolves free text to an equipmentId, or null when nothing matches.
  ///
  /// Three passes, strictest first:
  ///  1. the whole text IS an alias;
  ///  2. an alias appears in the text as a whole-word phrase ("looks like a
  ///     smith machine to me" -> smith_machine), longest alias wins so
  ///     "seated leg curl" beats "leg curl" beats "leg";
  ///  3. nothing — null, never a guess. An unresolved answer is the caller's
  ///     honest "couldn't tell", not a coin flip.
  String? resolve(String freeText) {
    final text = normalise(freeText);
    if (text.isEmpty) return null;
    final direct = _exact[text];
    if (direct != null) return direct;

    String? bestId;
    var bestLen = 0;
    final padded = ' $text ';
    for (final entry in _exact.entries) {
      if (entry.key.length <= bestLen) continue;
      if (padded.contains(' ${entry.key} ')) {
        bestId = entry.value;
        bestLen = entry.key.length;
      }
    }
    return bestId;
  }
}
