// RECOG-C1 step 3 — build the ground-truth table from the per-arm labelling.
//
// Plan fitness_app-2026-09-05T11-25-16-919Z-377ee0, step 3. The column list is
// the plan's own, verbatim and in its order; nothing is added and nothing is
// dropped. The one piece of labelling detail the plan's schema has no column
// for — which KIND of multiplicity a `multiple` frame has — is carried as a
// bracketed prefix inside `features_the_label_rests_on`, so the frozen schema
// stays frozen and the information still survives.
//
// **Arm-specific by construction.** The labelling input is 104 records keyed
// by (index, arm), and each arm's output row is built ONLY from that arm's
// record. An earlier version of this file read one image-level label and wrote
// it into both arms with `gt_equivalent` hard-coded to `true`; GPT-PM's round-1
// review returned that as a BLOCKER and was right. A crop can genuinely turn a
// `multiple` frame into a `canonical_single`, or move the central subject —
// and a generator that duplicates A into B cannot encode that even when the
// labeller saw it, which would make step 8's crop comparison attribute a
// changed TASK to changed recognition. `gt_equivalent` is now DERIVED from the
// two frozen labels by [armsAreEquivalent], never asserted.
//
// Not a test. Named without the `_test.dart` suffix on purpose, so a plain
// `flutter test` run never collects it and never rewrites the ground truth.
// Run it explicitly:
//
//   flutter test test/tools/recog_c1_generate_ground_truth.dart
//
// Everything about one machine's filesystem comes from the environment:
//
//   RECOG_C1_LABELS    core/plans/RECOG_C1_LABELS_2026-09-05.csv (104 rows)
//   RECOG_C1_MANIFEST  core/plans/RECOG_C1_ARM_MANIFEST_2026-09-05.csv
//   RECOG_C1_ALIASES   mobile/assets/data/equipment_aliases.json
//   RECOG_C1_GT_OUT    the CSV to write
//
// Why it runs under `flutter test`: `canonical_equipment_id` is generated by
// the PRODUCTION resolver, `EquipmentAliasIndex`, not by a lookup table typed
// out here. If a ground-truth label could not be resolved by the same code the
// app runs, "the model answered correctly" would be unmeasurable in production
// terms — so an unresolvable label is a hard stop, never an empty cell.
//
// Four properties are asserted before a single row is written, each a stop,
// because a ground truth that is quietly wrong is worse than none:
//
//   1. every canonical_single label resolves through the production index;
//   2. it resolves by EXACT alias match, not by the resolver's
//      longest-substring fallback — a label matching only as a substring
//      would silently depend on which other aliases happen to exist;
//   3. the label -> id mapping is one-to-one in both directions;
//   4. every label is a member of `kCanonicalMachines`, i.e. an answer the
//      cloud prompt actually offers the model.
//
// The committed CSV is then re-validated independently by
// `test/features/visual_equipment/recog_c1_ground_truth_test.dart`, which
// reads both files back from disk and re-derives everything. This generator
// asserting its own output would only prove the generator agrees with itself.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:fitness_app/features/equipment/data/equipment_alias_index.dart';
import 'package:fitness_app/features/visual_equipment/measurement/recog_c1_contract.dart';

import '../support/recog_c1_csv.dart';

String _env(String name) {
  final v = Platform.environment[name];
  if (v == null || v.trim().isEmpty) {
    throw StateError('$name is not set; see the header of this file');
  }
  return v.trim();
}

void main() {
  test('generate RECOG-C1 ground truth from the per-arm labelling', () {
    final labelsFile = File(_env('RECOG_C1_LABELS'));
    final manifestFile = File(_env('RECOG_C1_MANIFEST'));
    final aliasesFile = File(_env('RECOG_C1_ALIASES'));
    final outFile = File(_env('RECOG_C1_GT_OUT'));

    for (final f in [labelsFile, manifestFile, aliasesFile]) {
      expect(f.existsSync(), isTrue, reason: '${f.path} must exist');
    }

    // The production resolver, over the production alias asset.
    final aliasJson = (jsonDecode(aliasesFile.readAsStringSync()) as Map)
        .cast<String, dynamic>();
    final index = EquipmentAliasIndex.fromJson(aliasJson);

    // The same data keyed the way pass 1 of `resolve` keys it, so property 2
    // (exact match, not substring fallback) is checkable from outside the
    // class. Built with the PRODUCTION `normalise`, not a copy of it.
    final exactAliases = <String, String>{};
    aliasJson.forEach((id, aliases) {
      for (final a in (aliases as List).cast<String>()) {
        exactAliases[EquipmentAliasIndex.normalise(a)] = id;
      }
    });

    final labels = readCsv(labelsFile);
    final manifest = readCsv(manifestFile);
    expect(manifest.length, 52, reason: 'the corpus is 52 photographs');
    expect(labels.length, manifest.length * kArms.length,
        reason: 'the labelling must carry one record per (image, arm)');

    // (index, arm) -> label record. A missing or duplicated key is a stop:
    // silently falling back to the other arm is the defect this file was
    // rewritten to make impossible.
    final byKey = <String, Map<String, String>>{};
    for (final row in labels) {
      final key = '${row['index']!.trim()}|${row['arm']!.trim()}';
      expect(byKey.containsKey(key), isFalse,
          reason: 'duplicate label record for $key');
      byKey[key] = row;
    }

    final canonicalSet = kCanonicalMachines.toSet();
    final labelToId = <String, String>{};

    /// Resolves a label to an equipment id through the production index,
    /// stopping on anything ambiguous. Returns '' for a non-single row.
    String resolveFor(String idx, String arm, String kind, String label) {
      if (kind != 'canonical_single') {
        if (label.isNotEmpty) {
          throw StateError(
            'index $idx arm $arm is $kind but carries a canonical label '
            '"$label"',
          );
        }
        return '';
      }
      if (label.isEmpty) {
        throw StateError('index $idx arm $arm is canonical_single with no label');
      }
      if (!canonicalSet.contains(label)) {
        throw StateError(
          'index $idx arm $arm: "$label" is not in kCanonicalMachines, so the '
          'cloud prompt never offers it as an answer',
        );
      }
      final exact = exactAliases[EquipmentAliasIndex.normalise(label)];
      if (exact == null) {
        throw StateError(
          'index $idx arm $arm: "$label" is not an exact alias; resolving it '
          'would depend on the longest-substring fallback',
        );
      }
      final resolved = index.resolve(label);
      if (resolved == null || resolved != exact) {
        throw StateError(
          'index $idx arm $arm: production resolve("$label") returned '
          '$resolved, exact alias table says $exact',
        );
      }
      final seen = labelToId[label];
      if (seen != null && seen != resolved) {
        throw StateError('"$label" resolved to $seen and to $resolved');
      }
      labelToId[label] = resolved;
      return resolved;
    }

    final out = <String>[csvRow(kGroundTruthColumns)];
    var equivalent = 0;
    final kindCounts = <String, int>{};
    var unresolved = 0;

    for (final m in manifest) {
      final idx = m['index']!.trim();
      final perArm = <String, Map<String, String>>{};
      for (final arm in kArms) {
        final l = byKey['$idx|$arm'];
        expect(l, isNotNull, reason: 'no label record for index $idx arm $arm');
        perArm[arm] = l!;
      }

      final ids = <String, String>{};
      for (final arm in kArms) {
        final l = perArm[arm]!;
        final kind = l['gt_kind']!.trim();
        if (!kGroundTruthKinds.contains(kind)) {
          throw StateError('index $idx arm $arm: gt_kind "$kind" is not one of '
              'the four');
        }
        final status = l['gt_status']!.trim();
        if (status != 'resolved' && status != 'unresolved') {
          throw StateError('index $idx arm $arm: gt_status "$status" is '
              'neither state');
        }
        ids[arm] = resolveFor(idx, arm, kind, l['canonical_label']!.trim());
      }

      // DERIVED, never asserted — see this file's header.
      final equiv = armsAreEquivalent(perArm['A']!, perArm['B']!, ids);
      if (equiv) equivalent++;

      for (final arm in kArms) {
        final l = perArm[arm]!;
        final kind = l['gt_kind']!.trim();
        final multipleKind = l['multiple_kind']!.trim();
        final features = l['features']!.trim();
        if (arm == 'A') {
          kindCounts[kind] = (kindCounts[kind] ?? 0) + 1;
          if (l['gt_status']!.trim() != 'resolved') unresolved++;
        }
        out.add(csvRow([
          m['image_id_sha256_original'],
          arm,
          m['source_file'],
          arm == 'A' ? m['image_id_sha256_original'] : m['arm_b_sha256'],
          kind,
          l['canonical_label']!.trim(),
          ids[arm],
          l['semantic_label']!.trim(),
          l['central_subject']!.trim(),
          equiv ? 'true' : 'false',
          l['gt_status']!.trim(),
          l['pass1_label']!.trim(),
          l['pass2_label']!.trim(),
          multipleKind.isEmpty ? features : '[$multipleKind] $features',
        ]));
      }
    }

    // Property 3, the other direction — distinct labels, distinct ids.
    final idSet = labelToId.values.toSet();
    expect(idSet.length, labelToId.length,
        reason: 'two ground-truth labels resolve to the same equipment id');

    expect(out.length, manifest.length * kArms.length + 1,
        reason: 'one row per (image_id, arm), plus the header');

    outFile.writeAsStringSync('${out.join('\n')}\n');

    // ignore: avoid_print
    print('wrote ${outFile.path}: ${out.length - 1} rows '
        '(${manifest.length} images x ${kArms.length} arms)');
    // ignore: avoid_print
    print('arm A kinds: $kindCounts  unresolved $unresolved');
    // ignore: avoid_print
    print('gt_equivalent true for $equivalent of ${manifest.length} images');
    // ignore: avoid_print
    print('label -> id: '
        '${labelToId.entries.map((e) => '${e.key}=${e.value}').join(', ')}');
  });
}
