# -*- coding: utf-8 -*-
"""Abs. 42 rows: 1 dropped as a duplicate clip, 8 merge, 33 authored here.

`sit_ups` is the replaced match: upstream paired it with a butterfly crunch
("make the soles of your feet touch each other ... your legs should create a
diamond shape"), which is a different exercise and a quarter of the range.

Two rows take their equipment from the matched text rather than the filename:
`landmine_180` names a barbell in a landmine, and `spell_caster` names a pair of
dumbbells, so neither is bodyweight even though the title starts with neither
word.
"""
_C = ['core']

ENTRIES = {
    '45_degree_bycicle_twisting_crunch': {
        't': '45-Degree Bicycle Twisting Crunch',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the hands lightly behind your head and lift both feet off the floor, knees bent to a right angle.',
            'Curl the head and shoulders off the floor and press the lower back down. This is the starting position.',
            'Extend one leg out to about 45 degrees while drawing the opposite knee in, and rotate your torso so that shoulder turns toward the bent knee.',
            'Switch sides in one smooth movement, turning from the ribs rather than pulling on your neck.',
            'Keep alternating for the prescribed amount of repetitions, then lower the head and feet together.',
        ],
        'ru': 'Скручивания «велосипед» с ногами под углом 45 градусов',
        'rs': [
            'Лягте на спину, положите ладони за голову без нажима и оторвите обе стопы от пола, согнув колени под прямым углом.',
            'Оторвите голову и плечи от пола и прижмите поясницу. Это исходное положение.',
            'Вытяните одну ногу вперёд примерно под 45 градусов, одновременно подтягивая противоположное колено, и разверните корпус так, чтобы плечо шло к согнутому колену.',
            'Плавно смените стороны, поворачиваясь от рёбер, а не подтягивая себя за шею.',
            'Чередуйте стороны нужное количество повторений, затем одновременно опустите голову и стопы.',
        ],
    },
    '45_degree_side_bend': {
        't': '45-Degree Side Bend',
        'eq': 'back_extension', 'm': ['core', 'lower_back'], 'p': ['core'],
        'en': [
            'Set a 45-degree back extension bench and climb on sideways, so one hip rests on the pad and your feet are locked under the rollers.',
            'Cross your arms over your chest or place your hands behind your head and hold the torso in line with the legs. This is the starting position.',
            'Bend sideways toward the floor as you breathe in, letting the top side of your waist lengthen.',
            'Raise the torso back up until it is in line with the legs as you breathe out, and squeeze the side of the waist for a second.',
            'Repeat for the prescribed amount of repetitions, then turn over and work the other side.',
        ],
        'ru': 'Боковые наклоны в тренажёре под углом 45 градусов',
        'rs': [
            'Установите наклонную скамью для гиперэкстензии и займите на ней боковое положение: одно бедро лежит на подушке, стопы зафиксированы под валиками.',
            'Скрестите руки на груди или положите ладони за голову и удерживайте корпус на одной линии с ногами. Это исходное положение.',
            'На вдохе наклонитесь вбок к полу, позволяя верхней стороне талии удлиниться.',
            'На выдохе поднимите корпус обратно на одну линию с ногами и на секунду напрягите боковые мышцы.',
            'Выполните рекомендованное количество повторений, затем перевернитесь и проработайте другую сторону.',
        ],
    },
    'air_twisting_crunch': {
        't': 'Air Twisting Crunch',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the hands lightly behind your head and raise both legs so the hips and knees are bent to right angles.',
            'Curl the head and shoulders off the floor and keep the lower back pressed down. This is the starting position.',
            'Rotate the torso so one shoulder travels toward the opposite knee as you breathe out, keeping both feet in the air.',
            'Return to the middle as you breathe in, then repeat to the other side.',
            'Keep alternating for the prescribed amount of repetitions without letting the feet touch the floor.',
        ],
        'ru': 'Скручивания с поворотом и ногами на весу',
        'rs': [
            'Лягте на спину, положите ладони за голову без нажима и поднимите ноги так, чтобы в тазобедренных и коленных суставах были прямые углы.',
            'Оторвите голову и плечи от пола, прижав поясницу. Это исходное положение.',
            'На выдохе разверните корпус так, чтобы плечо пошло к противоположному колену; обе стопы остаются на весу.',
            'На вдохе вернитесь в среднее положение, затем повторите в другую сторону.',
            'Чередуйте стороны нужное количество повторений, не опуская стопы на пол.',
        ],
    },
    'band_decline_sit_ups': {
        't': 'Band Decline Sit-Up',
        'eq': 'resistance_bands', 'm': _C, 'd': 'intermediate',
        'ru': 'Подъёмы корпуса на наклонной скамье с лентой',
        'rs': [
            'Закрепите ленты у основания наклонной скамьи. Расположите рукояти внутрь скамьи так, чтобы, лёжа на ней, вы могли дотянуться до обеих.',
            'Зафиксируйте ноги за валиками скамьи. Возьмите рукояти обеими руками прямым хватом (ладони вперёд), поднесите их к ключицам и разверните кисти в нейтральное положение (ладони к корпусу). Примечание: руки остаются неподвижными всё упражнение. Это исходное положение.',
            'На выдохе поднимите корпус, пока верх тела не станет перпендикулярен полу. Задержитесь в сокращении на секунду и на вдохе опуститесь обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'band_side_bend': {
        't': 'Band Side Bend',
        'eq': 'resistance_bands', 'm': _C,
        'en': [
            'Stand on one end of a resistance band with the foot on the same side as the working hand and hold the other end at your side.',
            'Stand tall with the feet hip width apart, the free hand behind your head and the band already under tension. This is the starting position.',
            'Bend sideways away from the anchored foot as you breathe in, letting the band lengthen along your working side.',
            'Pull yourself back upright with the side of your waist as you breathe out, and hold for a second at the top.',
            'Repeat for the prescribed amount of repetitions, then change sides.',
        ],
        'ru': 'Наклоны в сторону с лентой',
        'rs': [
            'Встаньте на один конец ленты стопой со стороны рабочей руки, а другой конец удерживайте у бедра.',
            'Встаньте прямо, стопы на ширине таза, свободная рука за головой, лента уже натянута. Это исходное положение.',
            'На вдохе наклонитесь в сторону от опорной стопы, позволяя ленте растянуться вдоль рабочего бока.',
            'На выдохе вернитесь в вертикальное положение усилием боковых мышц живота и задержитесь на секунду.',
            'Выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'band_standing_crunch': {
        't': 'Band Standing Crunch',
        'eq': 'resistance_bands', 'm': _C,
        'en': [
            'Anchor a resistance band above head height and stand facing away from it, holding an end in each hand beside your ears.',
            'Step forward until the band is under tension, feet hip width apart and knees soft. This is the starting position.',
            'Crunch the ribs down toward your hips as you breathe out, rounding the upper back rather than folding at the hips.',
            'Let the band draw you back upright slowly as you breathe in, keeping the hands beside your ears throughout.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания с лентой стоя',
        'rs': [
            'Закрепите ленту выше уровня головы и встаньте спиной к точке крепления, удерживая по концу в каждой руке у висков.',
            'Отойдите вперёд, чтобы лента натянулась; стопы на ширине таза, колени мягкие. Это исходное положение.',
            'На выдохе скрутитесь, опуская рёбра к тазу и округляя верх спины, а не складываясь в тазобедренных суставах.',
            'На вдохе медленно позвольте ленте вернуть вас в вертикальное положение, всё время удерживая кисти у висков.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'band_standing_lift': {
        't': 'Band Standing Lift',
        'eq': 'resistance_bands', 'm': _C,
        'en': [
            'Anchor a resistance band at floor level and stand side-on to it, holding the free end in both hands beside the hip nearest the anchor.',
            'Step out until the band is under tension, feet shoulder width apart and knees slightly bent. This is the starting position.',
            'Pull the hands up and diagonally across your body to above the opposite shoulder as you breathe out, rotating through the hips and turning the back foot.',
            'Return along the same diagonal slowly as you breathe in, letting the band lower you rather than dropping.',
            'Repeat for the prescribed amount of repetitions, then change sides.',
        ],
        'ru': 'Диагональная тяга ленты снизу вверх',
        'rs': [
            'Закрепите ленту у пола и встаньте к ней боком, удерживая свободный конец обеими руками у ближнего к креплению бедра.',
            'Отойдите так, чтобы лента натянулась; стопы на ширине плеч, колени слегка согнуты. Это исходное положение.',
            'На выдохе потяните руки вверх по диагонали через корпус к противоположному плечу, разворачиваясь в тазе и проворачивая заднюю стопу.',
            'На вдохе медленно вернитесь по той же диагонали, сопротивляясь ленте, а не отпуская её.',
            'Выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'band_twist': {
        't': 'Band Standing Twist',
        'eq': 'resistance_bands', 'm': _C,
        'en': [
            'Anchor a resistance band at chest height and stand side-on to it, holding the free end in both hands with the arms straight out in front of your chest.',
            'Step out until the band is under tension, feet shoulder width apart and the core braced. This is the starting position.',
            'Rotate the torso away from the anchor, keeping the arms straight and the hips facing forward, until the band is fully loaded.',
            'Return to the middle slowly as you breathe in, resisting the pull rather than letting it snap you back.',
            'Repeat for the prescribed amount of repetitions, then turn around and work the other side.',
        ],
        'ru': 'Повороты корпуса с лентой стоя',
        'rs': [
            'Закрепите ленту на уровне груди и встаньте к ней боком, удерживая свободный конец обеими руками на прямых руках перед грудью.',
            'Отойдите так, чтобы лента натянулась; стопы на ширине плеч, живот подтянут. Это исходное положение.',
            'Разверните корпус в сторону от точки крепления, не сгибая руки и удерживая таз направленным вперёд, пока лента полностью не натянется.',
            'На вдохе медленно вернитесь в среднее положение, сопротивляясь натяжению, а не позволяя ленте вернуть вас рывком.',
            'Выполните рекомендованное количество повторений, затем развернитесь и проработайте другую сторону.',
        ],
    },
    'band_twist_up_down': {
        't': 'Band Twist - Up and Down',
        'eq': 'resistance_bands', 'm': _C,
        'en': [
            'Anchor a resistance band high on one side and stand side-on to it, holding the free end in both hands above the near shoulder with the arms straight.',
            'Step out until the band is under tension and set the feet shoulder width apart. This is the starting position.',
            'Pull the hands down and diagonally across your body toward the opposite hip as you breathe out, turning the ribs and pivoting the back foot.',
            'Reverse the path slowly back up above the shoulder as you breathe in, keeping the arms straight throughout.',
            'Repeat for the prescribed amount of repetitions, then change sides.',
        ],
        'ru': 'Диагональная тяга ленты сверху вниз',
        'rs': [
            'Закрепите ленту высоко с одной стороны и встаньте к ней боком, удерживая свободный конец обеими руками над ближним плечом на прямых руках.',
            'Отойдите так, чтобы лента натянулась; стопы на ширине плеч. Это исходное положение.',
            'На выдохе потяните руки вниз по диагонали через корпус к противоположному бедру, разворачивая рёбра и проворачивая заднюю стопу.',
            'На вдохе медленно вернитесь по той же траектории вверх над плечом, не сгибая руки.',
            'Выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'bent_knee_lying_twist': {
        't': 'Bent Knee Lying Twist',
        'eq': None, 'm': ['core', 'lower_back'], 'p': ['core'], 'stretch': True,
        'en': [
            'Lie on your back with the arms out to the sides in a T and the knees bent, feet flat on the floor.',
            'Press both shoulder blades into the floor. This is the starting position.',
            'Let both knees fall together to one side, keeping the shoulders down, until you feel the stretch through the lower back and waist.',
            'Hold for 20 to 30 seconds, breathing steadily, then bring the knees back to the middle and repeat to the other side.',
        ],
        'ru': 'Скручивание лёжа с согнутыми коленями',
        'rs': [
            'Лягте на спину, разведите руки в стороны буквой «Т», согните колени и поставьте стопы на пол.',
            'Прижмите обе лопатки к полу. Это исходное положение.',
            'Опустите оба колена вместе в одну сторону, не отрывая плечи от пола, до ощущения растяжения в пояснице и по боку.',
            'Удерживайте 20–30 секунд, дыша ровно, затем верните колени в середину и повторите в другую сторону.',
        ],
    },
    'cable_standing_lift': {
        't': 'Cable Standing Lift',
        'eq': 'cable_machine', 'm': _C, 'd': 'intermediate',
        'ru': 'Диагональная тяга снизу вверх на блоке',
        'rs': [
            'Закрепите стандартную рукоять на стойке и опустите блок в самое нижнее положение.',
            'Встаньте боком к стойке, возьмите рукоять одной рукой и отойдите. Расстояние — примерно вытянутая рука, трос под нагрузкой. Вытянутая рука должна быть на одной линии с тросом.',
            'Поставьте стопы на ширине плеч, присядьте и возьмитесь за рукоять обеими руками. Руки при этом остаются полностью выпрямленными.',
            'Одним движением потяните рукоять вверх и по диагонали через корпус, пока руки полностью не выпрямятся над головой.',
            'Держите спину прямой, а руки — близко к телу; проворачивайте заднюю стопу и выпрямляйте ноги, чтобы пройти всю амплитуду.',
            'Верните сначала руки, затем корпус. Возвращайтесь в нейтральное положение медленно и подконтрольно.',
            'Выполняйте повторения до отказа.',
            'Затем перестройтесь и повторите ту же серию движений в другую сторону.',
        ],
    },
    'crunch_on_bench': {
        't': 'Crunch on a Bench',
        'eq': 'adjustable_bench', 'm': _C,
        'en': [
            'Lie on a flat bench with your knees bent and your heels resting on the end of it, hands lightly behind your head.',
            'Press the lower back into the bench and keep the chin off the chest. This is the starting position.',
            'Curl the head, shoulders and upper back up off the bench as you breathe out, and hold the squeeze for a second.',
            'Lower back down slowly as you breathe in, stopping just before the shoulders touch, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания на скамье',
        'rs': [
            'Лягте на горизонтальную скамью, согнув колени и поставив пятки на её край; ладони лежат за головой без нажима.',
            'Прижмите поясницу к скамье и не прижимайте подбородок к груди. Это исходное положение.',
            'На выдохе оторвите от скамьи голову, плечи и верх спины и задержитесь в сокращении на секунду.',
            'На вдохе медленно опуститесь, остановившись прямо перед касанием лопатками, и выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_side_bend': {
        't': 'Dumbbell Side Bend',
        'eq': 'dumbbell', 'm': _C,
        'ru': 'Наклоны в сторону с гантелью',
        'rs': [
            'Встаньте прямо, удерживая гантель в левой руке (ладонь обращена к корпусу), правую руку положите на пояс. Стопы на ширине плеч. Это исходное положение.',
            'Сохраняя спину прямой и голову поднятой, наклонитесь только в талии вправо настолько, насколько сможете. На наклоне делайте вдох. Задержитесь на секунду и на выдохе вернитесь в исходное положение. Подсказка: остальное тело остаётся неподвижным.',
            'Теперь выполните то же движение, наклоняясь влево. Задержитесь на секунду и вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений и смените руку.',
        ],
    },
    'incline_leg_hip_raise': {
        't': 'Incline Leg Hip Raise',
        'eq': 'adjustable_bench', 'm': _C, 'd': 'intermediate',
        'en': [
            'Set a bench to a slight decline and lie back on it, gripping the top edge or the rollers behind your head.',
            'Raise both legs until they point at the ceiling and press the lower back into the bench. This is the starting position.',
            'Lift the hips off the bench by pushing the feet straight up as you breathe out, using the abdominals rather than swinging the legs.',
            'Lower the hips back to the bench slowly as you breathe in, keeping the legs vertical.',
            'Repeat for the prescribed amount of repetitions, then lower the legs under control.',
        ],
        'ru': 'Подъём таза с ногами вверх на наклонной скамье',
        'rs': [
            'Установите скамью с небольшим наклоном вниз и лягте на неё, взявшись за верхний край или за валики за головой.',
            'Поднимите обе ноги до вертикали и прижмите поясницу к скамье. Это исходное положение.',
            'На выдохе оторвите таз от скамьи, толкая стопы строго вверх усилием мышц живота, а не махом ног.',
            'На вдохе медленно опустите таз обратно на скамью, удерживая ноги вертикально.',
            'Выполните рекомендованное количество повторений, затем подконтрольно опустите ноги.',
        ],
    },
    'landmine_180': {
        't': 'Landmine 180',
        'eq': 'barbell', 'm': _C, 'd': 'intermediate',
        'ru': 'Развороты со штангой в углу на 180 градусов',
        'rs': [
            'Установите гриф в специальный шарнир или надёжно уприте его в угол. Нагрузите штангу подходящим весом.',
            'Поднимите гриф с пола и выведите его на уровень плеч обеими руками на вытянутых перед собой руках. Встаньте в широкую стойку. Это исходное положение.',
            'Выполняйте движение, разворачивая корпус и таз и опуская вес по дуге в одну сторону. Руки всё время остаются прямыми.',
            'Обратным движением переведите вес в противоположную сторону.',
            'Продолжайте чередовать стороны до конца подхода.',
        ],
    },
    'lever_seated_crunch': {
        't': 'Machine Seated Crunch',
        'eq': 'ab_crunch_machine', 'm': _C,
        'en': [
            'Set the seat so the chest pad sits against your upper chest and hook your feet under the rollers.',
            'Take the handles above your shoulders and sit tall with the weight already lifted off the stack. This is the starting position.',
            'Curl your ribs down toward your hips as you breathe out, rounding the upper back rather than pulling with the arms.',
            'Return slowly to the upright position as you breathe in, keeping tension on the abdominals, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания в тренажёре сидя',
        'rs': [
            'Отрегулируйте сиденье так, чтобы упор ложился на верх груди, и заведите стопы под валики.',
            'Возьмитесь за рукояти над плечами и сядьте ровно, сняв вес со стопки. Это исходное положение.',
            'На выдохе скрутитесь, опуская рёбра к тазу и округляя верх спины, а не подтягивая себя руками.',
            'На вдохе медленно вернитесь в вертикальное положение, сохраняя напряжение в мышцах живота, и выполните рекомендованное количество повторений.',
        ],
    },
    'lever_seated_leg_raise_crunch': {
        't': 'Machine Seated Leg Raise Crunch',
        'eq': 'ab_crunch_machine', 'm': _C, 'd': 'intermediate',
        'en': [
            'Select a light weight and sit in the crunch machine with your feet under the rollers and your hands on the upper handles.',
            'Sit tall with the elbows bent and the triceps on the pads. This is the starting position.',
            'Crunch the torso down and lift the legs at the same time as you breathe out, so the ribs and the knees travel toward each other.',
            'Return slowly to the upright position as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания с подъёмом ног в тренажёре',
        'rs': [
            'Выберите небольшой вес и сядьте в тренажёр для пресса, заведя стопы под валики и взявшись за верхние рукояти.',
            'Сядьте ровно, локти согнуты, трицепсы лежат на упорах. Это исходное положение.',
            'На выдохе одновременно скрутите корпус вниз и поднимите ноги так, чтобы рёбра и колени шли навстречу друг другу.',
            'На вдохе медленно вернитесь в вертикальное положение и выполните рекомендованное количество повторений.',
        ],
    },
    'lying_floor_leg_raise': {
        't': 'Lying Floor Leg Raise',
        'eq': None, 'm': _C,
        'en': [
            'Lie flat on your back with the legs straight and the hands under your glutes, palms down.',
            'Press the lower back into the floor and lift both heels a few centimetres. This is the starting position.',
            'Raise both legs until they are vertical as you breathe out, keeping the knees straight and the lower back down.',
            'Lower the legs slowly as you breathe in, stopping before the heels touch or before the lower back lifts, whichever comes first.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подъёмы ног лёжа на полу',
        'rs': [
            'Лягте на спину, выпрямите ноги и подложите ладони под ягодицы.',
            'Прижмите поясницу к полу и приподнимите пятки на несколько сантиметров. Это исходное положение.',
            'На выдохе поднимите обе ноги до вертикали, не сгибая колени и не отрывая поясницу.',
            'На вдохе медленно опустите ноги, остановившись до касания пятками пола или до момента, когда поясница начнёт отрываться — смотря что наступит раньше.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lying_straight_leg_raise': {
        't': 'Lying Straight Leg Raise',
        'eq': None, 'm': _C,
        'en': [
            'Lie flat on your back with the arms alongside your body and both legs straight.',
            'Brace the abdominals so the lower back stays in contact with the floor. This is the starting position.',
            'Raise both straight legs together until they are perpendicular to the floor as you breathe out.',
            'Lower them slowly back down as you breathe in, keeping the knees locked and stopping the moment the lower back tries to arch.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подъёмы прямых ног лёжа',
        'rs': [
            'Лягте на спину, руки вдоль тела, обе ноги выпрямлены.',
            'Напрягите мышцы живота так, чтобы поясница оставалась прижатой к полу. Это исходное положение.',
            'На выдохе поднимите обе прямые ноги вместе до перпендикуляра к полу.',
            'На вдохе медленно опустите их обратно, не сгибая колени и останавливаясь в тот момент, когда поясница начинает отрываться от пола.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'otis_ups': {
        't': 'Otis-Up',
        'eq': 'weight_plates', 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie on your back with the knees bent and the feet anchored, holding a weight plate against your chest with both hands.',
            'Press the lower back into the floor. This is the starting position.',
            'Sit all the way up as you breathe out, and as you reach the top press the plate straight overhead.',
            'Bring the plate back to your chest, then lower the torso to the floor slowly as you breathe in.',
            'Repeat for the prescribed amount of repetitions, keeping the plate close to the body so the lower back is not pulled forward.',
        ],
        'ru': 'Подъёмы корпуса с блином над головой',
        'rs': [
            'Лягте на спину, согните колени и зафиксируйте стопы, удерживая блин двумя руками у груди.',
            'Прижмите поясницу к полу. Это исходное положение.',
            'На выдохе полностью поднимите корпус, а в верхней точке выжмите блин прямо над головой.',
            'Верните блин к груди и на вдохе медленно опустите корпус на пол.',
            'Выполните рекомендованное количество повторений, удерживая блин близко к телу, чтобы он не тянул поясницу вперёд.',
        ],
    },
    'side_bridge_side_plank': {
        't': 'Side Plank',
        'eq': None, 'm': _C,
        'en': [
            'Lie on one side with the forearm on the floor, the elbow directly under the shoulder and the legs stacked.',
            'Press the forearm and the side of the bottom foot into the floor and lift the hips until the body is a straight line from the ankles to the head. This is the starting position.',
            'Hold the position with the hips high and the top shoulder stacked over the bottom one, breathing steadily.',
            'Hold for 20 to 45 seconds or until the hips start to drop, then lower and repeat on the other side.',
        ],
        'ru': 'Боковая планка',
        'rs': [
            'Лягте на бок, поставив предплечье на пол так, чтобы локоть был точно под плечом, ноги — одна на другой.',
            'Упритесь предплечьем и внешним краем нижней стопы в пол и поднимите таз так, чтобы тело вытянулось в прямую линию от лодыжек до головы. Это исходное положение.',
            'Удерживайте положение с высоко поднятым тазом; верхнее плечо находится строго над нижним, дыхание ровное.',
            'Держите 20–45 секунд или до момента, когда таз начнёт опускаться, затем опуститесь и повторите на другом боку.',
        ],
    },
    'sit_up_on_exercise_ball': {
        't': 'Sit-Up on an Exercise Ball',
        'eq': None, 'm': _C,
        'en': [
            'Sit on a stability ball and walk your feet forward until the ball supports your lower back, knees bent to a right angle.',
            'Cross the arms over your chest or place the hands lightly behind your head. This is the starting position.',
            'Curl the torso up off the ball as you breathe out, lifting the ribs toward the hips rather than pulling on your neck.',
            'Lower back over the ball slowly as you breathe in, letting the abdominals stretch a little at the bottom.',
            'Repeat for the prescribed amount of repetitions, keeping the feet planted so the ball stays still.',
        ],
        'ru': 'Подъёмы корпуса на гимнастическом мяче',
        'rs': [
            'Сядьте на гимнастический мяч и прошагайте стопами вперёд, пока мяч не окажется под поясницей; колени согнуты под прямым углом.',
            'Скрестите руки на груди или положите ладони за голову без нажима. Это исходное положение.',
            'На выдохе поднимите корпус с мяча, направляя рёбра к тазу, а не подтягивая себя за шею.',
            'На вдохе медленно опуститесь назад через мяч, позволяя мышцам живота немного растянуться в нижней точке.',
            'Выполните рекомендованное количество повторений, удерживая стопы на месте, чтобы мяч не катился.',
        ],
    },
    'sit_ups': {
        't': 'Sit-Up',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the knees bent, the feet flat on the floor and the arms crossed over your chest.',
            'Press the lower back down and keep the chin a fist\'s width from your chest. This is the starting position.',
            'Curl the torso all the way up until your chest is close to your thighs as you breathe out, leading with the ribs rather than the head.',
            'Lower back to the floor slowly as you breathe in, one vertebra at a time.',
            'Repeat for the prescribed amount of repetitions, anchoring the feet only if you cannot keep them down.',
        ],
        'ru': 'Подъёмы корпуса',
        'rs': [
            'Лягте на спину, согните колени, поставьте стопы на пол и скрестите руки на груди.',
            'Прижмите поясницу к полу, между подбородком и грудью оставьте расстояние в кулак. Это исходное положение.',
            'На выдохе полностью поднимите корпус, пока грудь не окажется близко к бёдрам, ведя движение рёбрами, а не головой.',
            'На вдохе медленно опуститесь на пол позвонок за позвонком.',
            'Выполните рекомендованное количество повторений; фиксируйте стопы только в том случае, если иначе они отрываются от пола.',
        ],
    },
    'spell_caster': {
        't': 'Spell Caster',
        'eq': 'dumbbell', 'm': _C, 'd': 'intermediate',
        'ru': 'Развороты с гантелями стоя',
        'rs': [
            'Возьмите по гантели в каждую руку прямым хватом. Стопы широко, таз и колени выпрямлены. Это исходное положение.',
            'Начните движение, подтянув обе гантели к одному бедру и развернув корпус.',
            'Не сгибая руки и удерживая гантели параллельно полу, разверните корпус и переведите вес на противоположную сторону.',
            'Продолжайте чередовать стороны до конца подхода.',
        ],
    },
    'stretching_chin_to_chest_stretch': {
        't': 'Chin-to-Chest Stretch',
        'eq': None, 'm': ['traps', 'back'], 'p': ['traps'], 'stretch': True,
        'ru': 'Растяжка шеи «подбородок к груди»',
        'rs': [
            'Сядьте на пол.',
            'Положите обе ладони на затылок, сцепив пальцы: большие пальцы направлены вниз, локти — вперёд. Медленно потяните голову вниз, к груди. Удерживайте 20–30 секунд.',
        ],
    },
    'stretching_iron_cross_stretch': {
        't': 'Iron Cross Stretch',
        'eq': None, 'm': ['core', 'lower_back', 'glutes'], 'p': ['core'],
        'stretch': True,
        'en': [
            'Lie on your back with the arms out to the sides in a T and both legs straight.',
            'Press the shoulder blades into the floor. This is the starting position.',
            'Raise one leg and take it across your body toward the opposite hand, keeping both shoulders down and the knee as straight as is comfortable.',
            'Hold for 20 to 30 seconds where the lower back and the outside of the hip stretch, then return and repeat on the other side.',
        ],
        'ru': 'Растяжка «железный крест» лёжа',
        'rs': [
            'Лягте на спину, разведите руки в стороны буквой «Т», ноги выпрямлены.',
            'Прижмите лопатки к полу. Это исходное положение.',
            'Поднимите одну ногу и переведите её поперёк тела к противоположной руке, не отрывая плечи от пола и сохраняя колено настолько прямым, насколько это комфортно.',
            'Удерживайте 20–30 секунд там, где растягиваются поясница и внешняя поверхность бедра, затем вернитесь и повторите в другую сторону.',
        ],
    },
    'stretching_seated_twist_straight_arm': {
        't': 'Seated Twist Stretch - Straight Arm',
        'eq': None, 'm': ['core', 'lower_back'], 'p': ['core'], 'stretch': True,
        'en': [
            'Sit tall on the floor with both legs straight in front of you and the spine lengthened.',
            'Reach both arms straight forward at shoulder height, palms facing down. This is the starting position.',
            'Rotate the torso to one side, keeping the arms straight and level and the hips facing forward, until the waist stretches.',
            'Return to the middle and repeat to the other side, alternating for 8 to 10 turns each way.',
        ],
        'ru': 'Повороты корпуса сидя с прямыми руками',
        'rs': [
            'Сядьте на пол с прямой спиной, вытянув обе ноги перед собой и удлинив позвоночник.',
            'Вытяните обе руки прямо перед собой на уровне плеч ладонями вниз. Это исходное положение.',
            'Разверните корпус в одну сторону, удерживая руки прямыми и на одном уровне, а таз — направленным вперёд, пока не растянется талия.',
            'Вернитесь в середину и повторите в другую сторону, чередуя по 8–10 разворотов в каждую.',
        ],
    },
    'stretching_spinal_stretch_on_exercise_ball': {
        't': 'Spinal Stretch on an Exercise Ball',
        'eq': None, 'm': ['core', 'lower_back', 'chest'], 'p': ['core'],
        'stretch': True,
        'en': [
            'Sit on a stability ball and walk your feet forward, lying back until the ball supports your mid-back.',
            'Keep the feet flat on the floor about hip width apart and the knees over the ankles. This is the starting position.',
            'Let the head, arms and shoulders drape back over the ball so the spine extends and the front of the body opens.',
            'Hold for 20 to 30 seconds, breathing steadily, then walk the feet back in and curl up to sitting.',
        ],
        'ru': 'Растяжка позвоночника на гимнастическом мяче',
        'rs': [
            'Сядьте на гимнастический мяч и прошагайте стопами вперёд, откидываясь назад, пока мяч не окажется под серединой спины.',
            'Стопы стоят на полу примерно на ширине таза, колени над лодыжками. Это исходное положение.',
            'Позвольте голове, рукам и плечам свободно свеситься назад через мяч, чтобы позвоночник разогнулся, а передняя поверхность тела раскрылась.',
            'Удерживайте 20–30 секунд, дыша ровно, затем подшагните стопами обратно и скруглением поднимитесь в положение сидя.',
        ],
    },
    'stretching_standing_side_bend_bent_arm': {
        't': 'Standing Side Bend - Bent Arm',
        'eq': None, 'm': ['core', 'lats'], 'p': ['core'], 'stretch': True,
        'en': [
            'Stand tall with the feet hip width apart and the knees soft.',
            'Raise one arm overhead and bend the elbow so the hand rests behind your head. This is the starting position.',
            'Bend sideways away from the raised arm, keeping both hips level and the torso in one plane, until that side of the ribs stretches.',
            'Hold for 20 to 30 seconds, then come back upright and repeat on the other side.',
        ],
        'ru': 'Боковой наклон стоя с согнутой рукой',
        'rs': [
            'Встаньте прямо, стопы на ширине таза, колени мягкие.',
            'Поднимите одну руку над головой и согните локоть так, чтобы ладонь легла на затылок. Это исходное положение.',
            'Наклонитесь в сторону от поднятой руки, удерживая таз ровно, а корпус — в одной плоскости, пока не растянется бок.',
            'Удерживайте 20–30 секунд, затем выпрямитесь и повторите в другую сторону.',
        ],
    },
    'twisting_crunch': {
        't': 'Twisting Crunch',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the knees bent, the feet flat on the floor and the hands lightly behind your head.',
            'Press the lower back into the floor and lift the head and shoulders slightly. This is the starting position.',
            'Curl up and rotate so one shoulder travels toward the opposite knee as you breathe out, turning from the ribs.',
            'Lower back to the floor slowly as you breathe in, then repeat to the other side.',
            'Keep alternating for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания с поворотом',
        'rs': [
            'Лягте на спину, согните колени, поставьте стопы на пол и положите ладони за голову без нажима.',
            'Прижмите поясницу к полу и слегка приподнимите голову и плечи. Это исходное положение.',
            'На выдохе скрутитесь вверх с поворотом так, чтобы плечо пошло к противоположному колену; поворот идёт от рёбер.',
            'На вдохе медленно опуститесь на пол, затем повторите в другую сторону.',
            'Чередуйте стороны нужное количество повторений.',
        ],
    },
    'v_up': {
        't': 'V-Up',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie flat on your back with the legs straight and the arms extended overhead on the floor.',
            'Brace the abdominals so the lower back stays down. This is the starting position.',
            'Lift the straight legs and the torso at the same time as you breathe out, reaching the hands toward the feet so the body forms a V.',
            'Lower the arms and legs back to the floor together and under control as you breathe in.',
            'Repeat for the prescribed amount of repetitions, bending the knees slightly if the lower back arches.',
        ],
        'ru': 'Складка «книжка»',
        'rs': [
            'Лягте на спину, ноги выпрямлены, руки вытянуты за головой на полу.',
            'Напрягите мышцы живота так, чтобы поясница оставалась прижатой. Это исходное положение.',
            'На выдохе одновременно поднимите прямые ноги и корпус, тянясь руками к стопам, чтобы тело образовало букву «V».',
            'На вдохе подконтрольно опустите руки и ноги на пол одновременно.',
            'Выполните рекомендованное количество повторений; если поясница прогибается, слегка согните колени.',
        ],
    },
    'vertical_leg_raise_on_parallel_bars': {
        't': 'Vertical Leg Raise on Parallel Bars',
        'eq': 'captains_chair', 'm': _C, 'd': 'intermediate',
        'en': [
            'Step into the captain\'s chair and rest your forearms on the pads, gripping the handles with your back against the back pad.',
            'Let the legs hang straight down and press the shoulders down away from your ears. This is the starting position.',
            'Raise both knees or straight legs toward your chest as you breathe out, curling the pelvis up at the top rather than only bending the hips.',
            'Lower the legs slowly as you breathe in, keeping the back against the pad and stopping any swing before the next repetition.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подъём ног в упоре на брусьях',
        'rs': [
            'Встаньте в тренажёр для подъёма ног, положите предплечья на упоры и возьмитесь за рукояти; спина прижата к спинке.',
            'Позвольте ногам свободно свисать вниз и опустите плечи, отдаляя их от ушей. Это исходное положение.',
            'На выдохе поднимите колени или прямые ноги к груди, в верхней точке подкручивая таз, а не только сгибая тазобедренные суставы.',
            'На вдохе медленно опустите ноги, не отрывая спину от спинки и гася раскачивание перед следующим повторением.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'weighted_leg_extension_crunch': {
        't': 'Weighted Leg Extension Crunch',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie on your back holding a weight plate or a dumbbell against your chest with both hands, knees bent and feet off the floor.',
            'Press the lower back into the floor and curl the head and shoulders up slightly. This is the starting position.',
            'Extend both legs out straight while lowering the torso a little, keeping the lower back down and the weight on your chest.',
            'Draw the knees back in and crunch the ribs toward them as you breathe out, and hold the squeeze for a second.',
            'Repeat for the prescribed amount of repetitions, keeping the feet off the floor throughout.',
        ],
        'ru': 'Скручивания с выпрямлением ног и отягощением',
        'rs': [
            'Лягте на спину, удерживая блин или гантель двумя руками у груди; колени согнуты, стопы оторваны от пола.',
            'Прижмите поясницу к полу и слегка приподнимите голову и плечи. Это исходное положение.',
            'Выпрямите обе ноги, немного опуская корпус, но не отрывая поясницу от пола и удерживая отягощение на груди.',
            'На выдохе подтяните колени обратно и скрутите рёбра им навстречу, задержавшись в сокращении на секунду.',
            'Выполните рекомендованное количество повторений, всё время удерживая стопы на весу.',
        ],
    },
    'cable_standing_crunch': {
        't': 'Cable Standing Crunch',
        'eq': 'cable_machine', 'm': ['core'],
        'en': [
            'Attach a rope to a high pulley, face away from the stack and hold an end in each hand beside your ears.',
            'Stand a step forward with the feet hip width apart and the knees soft, so the cable is under tension. This is the starting position.',
            'Crunch the ribs down toward your hips as you breathe out, rounding the upper back and keeping the hips still.',
            'Let the cable draw you back upright slowly as you breathe in, keeping constant tension on the abdominals.',
            'Repeat for the prescribed amount of repetitions, using a weight light enough that the lower back does not take over.',
        ],
        'ru': 'Скручивания на верхнем блоке стоя',
        'rs': [
            'Закрепите канатную рукоять на верхнем блоке, встаньте спиной к стойке и держите по концу в каждой руке у висков.',
            'Отойдите на шаг вперёд, стопы на ширине таза, колени мягкие, трос натянут. Это исходное положение.',
            'На выдохе скрутитесь, опуская рёбра к тазу и округляя верх спины; таз остаётся неподвижным.',
            'На вдохе медленно позвольте тросу вернуть вас в вертикальное положение, сохраняя постоянное напряжение в мышцах живота.',
            'Выполните рекомендованное количество повторений с таким весом, при котором поясница не берёт работу на себя.',
        ],
    },
    'hanging_straight_leg_hip_raise': {
        't': 'Hanging Straight Leg Hip Raise',
        'eq': 'pullup_bar', 'm': ['core'], 'd': 'advanced',
        'en': [
            'Hang from a pull-up bar with an overhand grip at shoulder width, arms straight and legs together.',
            'Pull the shoulders down away from your ears and brace the core so the body stops swinging. This is the starting position.',
            'Raise both straight legs until they are level with your hips, then keep going by curling the pelvis up toward your ribs so the hips leave the vertical line.',
            'Lower the hips first and then the legs, slowly and under control, as you breathe in.',
            'Repeat for the prescribed amount of repetitions; the pelvic curl at the top is what separates this from a plain leg raise.',
        ],
        'ru': 'Подъём прямых ног с подкручиванием таза в висе',
        'rs': [
            'Повисните на перекладине прямым хватом на ширине плеч: руки прямые, ноги вместе.',
            'Опустите плечи, отдаляя их от ушей, и напрягите живот, чтобы тело перестало раскачиваться. Это исходное положение.',
            'Поднимите обе прямые ноги до уровня таза, а затем продолжите движение, подкручивая таз к рёбрам, чтобы он вышел из вертикали.',
            'На вдохе сначала опустите таз, затем ноги — медленно и подконтрольно.',
            'Выполните рекомендованное количество повторений: именно подкручивание таза в верхней точке отличает это упражнение от обычного подъёма ног.',
        ],
    },
    'hanging_straight_leg_raise': {
        't': 'Hanging Straight Leg Raise',
        'eq': 'pullup_bar', 'm': ['core'], 'd': 'intermediate',
        'ru': 'Подъём прямых ног в висе',
        'rs': [
            'Повисните на перекладине на прямых руках широким или средним хватом. Ноги опущены прямо вниз, таз слегка подкручен назад. Это исходное положение.',
            'Поднимайте ноги, пока между корпусом и ногами не образуется прямой угол. На этом движении делайте выдох и задержитесь в сокращении примерно на секунду.',
            'На вдохе медленно вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
}
