# -*- coding: utf-8 -*-
"""Back. 71 rows: 4 dropped, 11 merge into the existing catalog, 56 authored.

The seated-row family is why so much of this file is hand-written. Five rows --
normal grip, parallel grip, wide grip, V-grip straight-back and the V-bar high
row -- all matched the SAME public-domain text, which describes a V-bar. Keeping
it on all five would have shipped one exercise five times while the titles
promised five grips, so only the V-bar row keeps it.

Also replaced: `band_bent_over_row` and `band_pull_through` matched a barbell
and a cable version of themselves, `barbell_underhand_bent_over_row` matched a
pronated-grip text, and `dumbbell_palm_rotational_bent_over_row` matched a text
with no rotation in it.
"""
_PULL = ['back', 'lats', 'biceps']
_DL = ['hamstrings', 'glutes', 'back', 'lower_back']

ENTRIES = {
    '45_degree_hyperextension': {
        't': '45-Degree Hyperextension',
        'eq': 'back_extension', 'm': ['lower_back', 'glutes', 'hamstrings'],
        'p': ['lower_back'],
        'en': [
            'Set the pad of a 45-degree back extension bench just below your hip bones and lock your ankles under the rollers.',
            'Cross the arms over your chest and hinge forward until your torso hangs down with the back flat. This is the starting position.',
            'Raise the torso by squeezing the glutes and the lower back until the body is in a straight line with the legs, breathing out.',
            'Stop at that line rather than arching past it, then lower slowly back down as you breathe in.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Гиперэкстензия под углом 45 градусов',
        'rs': [
            'Установите подушку наклонной скамьи чуть ниже тазовых костей и зафиксируйте лодыжки под валиками.',
            'Скрестите руки на груди и наклонитесь вперёд так, чтобы корпус свисал вниз с прямой спиной. Это исходное положение.',
            'На выдохе поднимите корпус усилием ягодиц и мышц поясницы, пока тело не окажется на одной линии с ногами.',
            'Остановитесь на этой линии, не переразгибаясь дальше, и на вдохе медленно опуститесь.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'band_bent_over_row': {
        't': 'Band Bent-Over Row',
        'eq': 'resistance_bands', 'm': _PULL, 'p': ['back'],
        'en': [
            'Stand on the middle of a resistance band with the feet hip width apart and take an end in each hand.',
            'Bend the knees slightly and hinge forward from the hips until the torso is close to parallel with the floor, back flat and head in line with the spine. This is the starting position.',
            'Pull both hands to your waist as you breathe out, keeping the elbows close to the body and squeezing the shoulder blades together at the top.',
            'Straighten the arms slowly back toward the floor as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга ленты в наклоне',
        'rs': [
            'Встаньте на середину ленты, стопы на ширине таза, и возьмите по концу в каждую руку.',
            'Слегка согните колени и наклонитесь вперёд от тазобедренных суставов почти до параллели корпуса с полом; спина прямая, голова на одной линии с позвоночником. Это исходное положение.',
            'На выдохе подтяните обе кисти к поясу, прижимая локти к корпусу и сводя лопатки в верхней точке.',
            'На вдохе медленно выпрямите руки и выполните рекомендованное количество повторений.',
        ],
    },
    'band_kneeling_one_arm_pulldown': {
        't': 'Band Kneeling One-Arm Pulldown',
        'eq': 'resistance_bands', 'm': _PULL, 'p': ['lats'],
        'en': [
            'Anchor a resistance band above head height and kneel far enough back from it that the band is under tension with the arm straight overhead.',
            'Hold the free end in one hand, brace the core and keep the torso upright. This is the starting position.',
            'Pull the elbow down and toward your ribs as you breathe out, driving with the lat rather than the hand.',
            'Let the arm straighten back overhead slowly as you breathe in, and repeat for the prescribed amount of repetitions before changing sides.',
        ],
        'ru': 'Тяга ленты одной рукой стоя на коленях',
        'rs': [
            'Закрепите ленту выше уровня головы и встаньте на колени настолько далеко, чтобы при выпрямленной вверх руке она была натянута.',
            'Возьмите свободный конец одной рукой, напрягите живот и держите корпус вертикально. Это исходное положение.',
            'На выдохе опустите локоть вниз и к рёбрам, работая широчайшей мышцей, а не кистью.',
            'На вдохе медленно выпрямите руку обратно вверх и выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'band_one_arm_twisting_seated_row': {
        't': 'Band One-Arm Twisting Seated Row',
        'eq': 'resistance_bands', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit on the floor with the legs extended and loop a resistance band around the soles of your feet, holding one end in one hand with the palm facing down.',
            'Sit tall with the arm straight and the band under tension. This is the starting position.',
            'Pull the elbow back along your ribs as you breathe out, rotating the wrist so the palm faces your torso by the time the hand reaches your waist.',
            'Straighten the arm slowly and rotate the palm back down as you breathe in, and repeat for the prescribed amount of repetitions before changing arms.',
        ],
        'ru': 'Тяга ленты одной рукой сидя с разворотом кисти',
        'rs': [
            'Сядьте на пол, вытянув ноги, накиньте ленту на подошвы стоп и возьмите один конец одной рукой ладонью вниз.',
            'Сядьте ровно: рука выпрямлена, лента натянута. Это исходное положение.',
            'На выдохе отведите локоть назад вдоль рёбер, разворачивая кисть так, чтобы к моменту, когда ладонь окажется у пояса, она смотрела на корпус.',
            'На вдохе медленно выпрямите руку и верните ладонь вниз, затем выполните рекомендованное количество повторений и смените руку.',
        ],
    },
    'band_one_leg_kickback_bent_position': {
        't': 'Band One-Leg Kickback',
        'eq': 'resistance_bands', 'm': ['glutes', 'hamstrings'], 'p': ['glutes'],
        'en': [
            'Kneel on all fours with a resistance band looped around one foot and the other end held under both hands.',
            'Keep the back flat and the working knee bent to a right angle under your hip. This is the starting position.',
            'Push the working foot back and up against the band until the leg is straight in line with your torso, breathing out and squeezing the glute.',
            'Return the knee slowly under your hip as you breathe in without letting the lower back arch, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Мах ногой назад с лентой в упоре на четвереньках',
        'rs': [
            'Встаньте на четвереньки, накинув ленту на одну стопу и прижав другой конец обеими ладонями к полу.',
            'Спина прямая, рабочее колено согнуто под прямым углом под тазом. Это исходное положение.',
            'На выдохе отведите рабочую стопу назад и вверх, преодолевая сопротивление ленты, пока нога не выпрямится на одной линии с корпусом, и сожмите ягодицу.',
            'На вдохе медленно верните колено под таз, не прогибая поясницу, и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'band_pull_through': {
        't': 'Band Pull Through',
        'eq': 'resistance_bands', 'm': ['glutes', 'hamstrings', 'lower_back'],
        'p': ['glutes'],
        'en': [
            'Anchor a resistance band low behind you, straddle it with the feet set wide and hold the free end in both hands between your legs.',
            'Step forward until the band is under tension and stand with the knees slightly bent. This is the starting position.',
            'Hinge at the hips and reach the hands back between your legs as far as they will go, keeping the back flat and the arms straight.',
            'Stand back up by driving the hips forward and squeezing the glutes, breathing out — all of the movement comes from the hips, not the shoulders.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Протяжка ленты между ног',
        'rs': [
            'Закрепите ленту низко за собой, встаньте над ней в широкую стойку и возьмите свободный конец обеими руками между ног.',
            'Сделайте шаг вперёд, чтобы лента натянулась; колени слегка согнуты. Это исходное положение.',
            'Наклонитесь в тазобедренных суставах и уведите руки назад между ног как можно дальше, сохраняя спину прямой, а руки — выпрямленными.',
            'На выдохе выпрямитесь, выводя таз вперёд и сжимая ягодицы: всё движение идёт от таза, а не от плеч.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'band_seated_row': {
        't': 'Band Seated Row',
        'eq': 'resistance_bands', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit on the floor with the legs extended and a slight bend in the knees, looping a resistance band around the soles of both feet.',
            'Hold an end in each hand with the arms straight and sit tall so the band is under tension. This is the starting position.',
            'Pull both hands to your waist as you breathe out, drawing the elbows straight back and squeezing the shoulder blades together.',
            'Straighten the arms slowly as you breathe in, letting the shoulder blades open without rounding the lower back, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга ленты сидя',
        'rs': [
            'Сядьте на пол, вытянув ноги и слегка согнув колени; накиньте ленту на подошвы обеих стоп.',
            'Возьмите по концу в каждую руку, руки прямые; сядьте ровно, чтобы лента натянулась. Это исходное положение.',
            'На выдохе подтяните обе кисти к поясу, отводя локти строго назад и сводя лопатки.',
            'На вдохе медленно выпрямите руки, позволяя лопаткам разойтись, но не скругляя поясницу, и выполните рекомендованное количество повторений.',
        ],
    },
    'band_straight_back_seated_row': {
        't': 'Band Straight-Back Seated Row',
        'eq': 'resistance_bands', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit on the floor with the legs extended and loop a resistance band around the soles of both feet, holding an end in each hand.',
            'Sit tall with the spine vertical and the arms straight. This is the starting position.',
            'Pull both hands to your waist as you breathe out while keeping the torso completely upright — unlike the ordinary seated row, the body does not lean back at all.',
            'Straighten the arms slowly as you breathe in without letting the torso follow them forward, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга ленты сидя с прямой спиной',
        'rs': [
            'Сядьте на пол, вытянув ноги, и накиньте ленту на подошвы обеих стоп, взяв по концу в каждую руку.',
            'Сядьте ровно, позвоночник вертикален, руки прямые. Это исходное положение.',
            'На выдохе подтяните обе кисти к поясу, полностью сохраняя вертикальное положение корпуса: в отличие от обычной тяги сидя, корпус не отклоняется назад.',
            'На вдохе медленно выпрямите руки, не позволяя корпусу уходить вперёд вслед за ними, и выполните рекомендованное количество повторений.',
        ],
    },
    'barbell_bent_over_row_overgrip': {
        't': 'Barbell Bent-Over Row - Overhand Grip',
        'eq': 'barbell', 'm': _PULL, 'p': ['back'], 'd': 'intermediate',
        'min': 8,
        'ru': 'Тяга штанги в наклоне прямым хватом',
        'rs': [
            'Возьмите штангу прямым хватом (ладони вниз), слегка согните колени и наклоните корпус вперёд от тазобедренных суставов, сохраняя спину прямой, почти до параллели с полом. Подсказка: голову держите поднятой. Штанга висит прямо перед вами, руки перпендикулярны полу и корпусу. Это исходное положение.',
            'Не двигая корпусом, на выдохе подтяните штангу к себе. Локти держите близко к телу, а предплечьями только удерживайте вес. В верхней точке сожмите мышцы спины и на мгновение задержитесь.',
            'На вдохе медленно опустите штангу обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'barbell_straight_leg_deadlift': {
        't': 'Barbell Straight-Leg Deadlift',
        'eq': 'barbell', 'm': _DL, 'p': ['hamstrings'], 'd': 'intermediate',
        'min': 8,
        'en': [
            'Stand with the feet hip width apart holding a barbell in front of your thighs with an overhand grip at shoulder width.',
            'Set the back flat, the chest up and the knees almost straight with just a soft bend. This is the starting position.',
            'Push the hips back and lower the bar down the front of your legs as you breathe in, keeping it in contact with them and the back flat.',
            'Stop when the hamstrings will not lengthen further without the lower back rounding, then drive the hips forward to stand up as you breathe out.',
            'Repeat for the prescribed amount of repetitions, treating any rounding of the back as the end of the set.',
        ],
        'ru': 'Становая тяга на прямых ногах со штангой',
        'rs': [
            'Встаньте, стопы на ширине таза, удерживая штангу перед бёдрами прямым хватом на ширине плеч.',
            'Спина прямая, грудь развёрнута, колени почти выпрямлены с лёгким сгибом. Это исходное положение.',
            'На вдохе отведите таз назад и опускайте гриф вдоль передней поверхности ног, сохраняя контакт с ними и прямую спину.',
            'Остановитесь там, где задняя поверхность бедра больше не удлиняется без скругления поясницы, затем на выдохе выпрямитесь, выводя таз вперёд.',
            'Выполните рекомендованное количество повторений; любое скругление спины означает конец подхода.',
        ],
    },
    'barbell_underhand_bent_over_row': {
        't': 'Barbell Bent-Over Row - Underhand Grip',
        'eq': 'barbell', 'm': _PULL, 'p': ['back'], 'd': 'intermediate',
        'min': 8,
        'en': [
            'Hold a barbell with an underhand grip at shoulder width, palms facing forward, and stand with the feet hip width apart.',
            'Bend the knees slightly and hinge forward from the hips until the torso is at about 45 degrees, back flat and the bar hanging at arm\'s length. This is the starting position.',
            'Pull the bar into your lower ribs as you breathe out, keeping the elbows tucked close to the body — the underhand grip brings the lower lats into the pull.',
            'Lower the bar slowly back to arm\'s length as you breathe in without letting the torso rise.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга штанги в наклоне обратным хватом',
        'rs': [
            'Возьмите штангу обратным хватом на ширине плеч, ладони вперёд, стопы на ширине таза.',
            'Слегка согните колени и наклонитесь вперёд от тазобедренных суставов примерно до 45 градусов; спина прямая, гриф висит на прямых руках. Это исходное положение.',
            'На выдохе подтяните гриф к нижним рёбрам, прижимая локти к корпусу: обратный хват сильнее включает нижнюю часть широчайших мышц.',
            'На вдохе медленно опустите гриф на прямые руки, не поднимая корпус.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'cable_bar_lateral_pulldown_reverse_grip': {
        't': 'Cable Lat Pulldown - Reverse Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['lats'],
        'en': [
            'Sit at a pulldown station with the thigh pads set snug and take the bar with an underhand grip at shoulder width.',
            'Sit tall, lean the torso back about 20 degrees and lift the chest. This is the starting position.',
            'Pull the bar to the top of your chest as you breathe out, driving the elbows down and back and squeezing the shoulder blades together.',
            'Let the bar rise slowly until the arms are straight and the lats are stretched as you breathe in, without letting the shoulders shrug up.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга верхнего блока обратным хватом',
        'rs': [
            'Сядьте в тренажёр для тяги верхнего блока, плотно отрегулировав валики над бёдрами, и возьмите рукоять обратным хватом на ширине плеч.',
            'Сядьте ровно, отклоните корпус назад примерно на 20 градусов и приподнимите грудь. Это исходное положение.',
            'На выдохе притяните рукоять к верху груди, направляя локти вниз и назад и сводя лопатки.',
            'На вдохе медленно позвольте рукояти подняться до полного выпрямления рук и растяжения широчайших, не поднимая плечи к ушам.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'cable_bar_lateral_pulldown_wide_shoulder_grip': {
        't': 'Cable Lat Pulldown - Wide Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['lats'],
        'en': [
            'Sit at a pulldown station with the thigh pads snug and take the wide bar with an overhand grip well outside shoulder width.',
            'Sit tall with a slight backward lean and the chest lifted. This is the starting position.',
            'Pull the bar down to the top of your chest as you breathe out, leading with the elbows and squeezing the lats at the bottom.',
            'Let the bar rise slowly to full arm extension as you breathe in, keeping the torso still.',
            'Repeat for the prescribed amount of repetitions, never pulling the bar behind your neck.',
        ],
        'ru': 'Тяга верхнего блока широким хватом',
        'rs': [
            'Сядьте в тренажёр для тяги верхнего блока, плотно отрегулировав валики над бёдрами, и возьмите широкую рукоять прямым хватом заметно шире плеч.',
            'Сядьте ровно, слегка отклонив корпус назад и приподняв грудь. Это исходное положение.',
            'На выдохе притяните рукоять к верху груди, ведя движение локтями и сжимая широчайшие в нижней точке.',
            'На вдохе медленно позвольте рукояти подняться до полного выпрямления рук, не двигая корпусом.',
            'Выполните рекомендованное количество повторений и никогда не тяните рукоять за голову.',
        ],
    },
    'cable_one_arm_lateral_pulldown': {
        't': 'Cable One-Arm Lat Pulldown',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['lats'],
        'en': [
            'Attach a single handle to a high pulley and sit or kneel below it, taking the handle in one hand with the palm facing in.',
            'Let the arm extend fully overhead so the shoulder blade rises, and brace the core. This is the starting position.',
            'Pull the elbow down toward your ribs as you breathe out, drawing the shoulder blade down first and squeezing the lat.',
            'Let the arm straighten back overhead slowly as you breathe in, and repeat for the prescribed amount of repetitions before changing arms.',
        ],
        'ru': 'Тяга верхнего блока одной рукой',
        'rs': [
            'Закрепите одиночную рукоять на верхнем блоке, сядьте или встаньте на колено под ним и возьмите рукоять одной рукой ладонью внутрь.',
            'Полностью выпрямите руку вверх, позволив лопатке подняться, и напрягите живот. Это исходное положение.',
            'На выдохе потяните локоть вниз к рёбрам, сначала опуская лопатку, и сожмите широчайшую мышцу.',
            'На вдохе медленно выпрямите руку обратно вверх и выполните рекомендованное количество повторений, затем смените руку.',
        ],
    },
    'cable_one_arm_twisting_seated_row': {
        't': 'Cable One-Arm Twisting Seated Row',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['back'],
        'ru': 'Тяга нижнего блока одной рукой с разворотом кисти',
        'rs': [
            'Чтобы принять исходное положение, сядьте в тренажёр и поставьте стопы на переднюю платформу или упор, слегка согнув колени и не блокируя их.',
            'Наклонитесь вперёд, сохраняя естественное положение спины, и возьмитесь за одиночную рукоять левой рукой хватом ладонью вниз.',
            'Не сгибая руку, отклонитесь назад, пока корпус не окажется под прямым углом к ногам. Спина слегка прогнута, грудь развёрнута. Удерживая рукоять перед собой, вы должны чувствовать хорошее растяжение широчайшей мышцы. Правую руку можно держать на поясе. Это исходное положение упражнения.',
            'Не двигая корпусом, подтяните рукоять к себе, держа руку близко к телу и разворачивая кисть так, чтобы у живота ладонь была обращена к корпусу. На этом движении делайте выдох. В этой точке сильно сожмите мышцы спины.',
            'Задержитесь в сокращении на секунду и на вдохе медленно вернитесь в исходное положение. Подсказка: возвращаясь, разворачивайте кисть обратно ладонью вниз.',
            'Выполните рекомендованное количество повторений, затем сделайте то же самое правой рукой.',
        ],
    },
    'cable_pulldown': {
        't': 'Cable Pulldown - Close Underhand Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['lats'],
        'ru': 'Тяга верхнего блока узким обратным хватом',
        'rs': [
            'Сядьте в тренажёр для тяги верхнего блока с широкой рукоятью на верхнем блоке. Отрегулируйте валики под свой рост: они не дадут телу подниматься вслед за весом.',
            'Возьмитесь за рукоять ладонями к себе (обратный хват). Кисти поставьте уже ширины плеч.',
            'Удерживая рукоять на прямых руках выбранным хватом, отклоните корпус назад примерно на 30 градусов, прогнув поясницу и развернув грудь. Это исходное положение.',
            'На выдохе тяните рукоять вниз, пока она не коснётся верха груди, опуская и отводя назад плечи и локти. Подсказка: в полностью сокращённом положении сосредоточьтесь на сжатии мышц спины и держите локти близко к корпусу. Корпус остаётся неподвижным, двигаются только руки, а предплечья лишь удерживают рукоять.',
            'После секунды в сокращении на вдохе медленно верните рукоять в исходное положение, пока руки полностью не выпрямятся, а широчайшие не растянутся.',
            'Выполните нужное количество повторений.',
        ],
    },
    'cable_seated_high_row_v_bar': {
        't': 'Cable Seated High Row - V-Bar',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['back'],
        'ru': 'Тяга к поясу сидя с рукоятью для узкого хвата',
        'rs': [
            'Для этого упражнения нужен тренажёр для тяги нижнего блока с рукоятью для узкого хвата. Примечание: такая рукоять даёт нейтральный хват, при котором ладони обращены друг к другу. Чтобы принять исходное положение, сядьте в тренажёр и поставьте стопы на переднюю платформу или упор, слегка согнув колени и не блокируя их.',
            'Наклонитесь вперёд, сохраняя естественное положение спины, и возьмитесь за рукоять.',
            'Не сгибая руки, отклонитесь назад, пока корпус не окажется под прямым углом к ногам. Спина слегка прогнута, грудь развёрнута. Удерживая рукоять перед собой, вы должны чувствовать хорошее растяжение широчайших мышц. Это исходное положение упражнения.',
            'Не двигая корпусом, подтяните рукоять к себе, держа руки близко к телу, до касания живота. На этом движении делайте выдох. В этой точке сильно сожмите мышцы спины. Задержитесь в сокращении на секунду и на вдохе медленно вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'cable_seated_row_normal_grip': {
        't': 'Cable Seated Row - Normal Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit at a low pulley row station with a straight bar attached, feet on the platform and the knees slightly bent.',
            'Take the bar with an overhand grip at shoulder width and sit up until the arms are straight and the lats are stretched. This is the starting position.',
            'Pull the bar into your abdomen as you breathe out, drawing the elbows straight back past your ribs and squeezing the shoulder blades together.',
            'Let the bar travel forward slowly as you breathe in until the arms are straight again, keeping the torso upright rather than following it.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга нижнего блока к поясу обычным хватом',
        'rs': [
            'Сядьте в тренажёр для тяги нижнего блока с прямой рукоятью, поставив стопы на платформу и слегка согнув колени.',
            'Возьмитесь за рукоять прямым хватом на ширине плеч и выпрямитесь так, чтобы руки были прямыми, а широчайшие — растянутыми. Это исходное положение.',
            'На выдохе подтяните рукоять к животу, отводя локти строго назад вдоль рёбер и сводя лопатки.',
            'На вдохе медленно отпустите рукоять вперёд до полного выпрямления рук, удерживая корпус вертикально, а не следуя за весом.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'cable_seated_row_parallel_grip': {
        't': 'Cable Seated Row - Parallel Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit at a low pulley row station with a close parallel handle attached and place your feet on the platform, knees slightly bent.',
            'Take the handle so the palms face each other and sit up with the arms straight. This is the starting position.',
            'Pull the handle into your navel as you breathe out, keeping the elbows brushing your sides — the neutral grip keeps the shoulders in their strongest position.',
            'Let the handle travel forward slowly as you breathe in until the shoulder blades open, without rounding the lower back.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга нижнего блока параллельным хватом',
        'rs': [
            'Сядьте в тренажёр для тяги нижнего блока с узкой параллельной рукоятью и поставьте стопы на платформу, слегка согнув колени.',
            'Возьмитесь за рукоять так, чтобы ладони смотрели друг на друга, и выпрямитесь; руки прямые. Это исходное положение.',
            'На выдохе подтяните рукоять к пупку, ведя локти вплотную к бокам: нейтральный хват удерживает плечевые суставы в самом сильном положении.',
            'На вдохе медленно отпустите рукоять вперёд, позволяя лопаткам разойтись, но не скругляя поясницу.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'cable_seated_row_wide_grip': {
        't': 'Cable Seated Row - Wide Grip',
        'eq': 'cable_machine', 'm': ['back', 'lats', 'shoulders'],
        'p': ['back'],
        'en': [
            'Sit at a low pulley row station with a long straight bar attached, feet on the platform and knees slightly bent.',
            'Take the bar with an overhand grip well outside shoulder width and sit up with the arms straight. This is the starting position.',
            'Pull the bar into your upper abdomen with the elbows flared out to the sides as you breathe out, squeezing the mid-back and the rear shoulders.',
            'Let the bar travel forward slowly as you breathe in until the arms are straight again.',
            'Repeat for the prescribed amount of repetitions; the wide grip shifts the work from the lats onto the middle of the back.',
        ],
        'ru': 'Тяга нижнего блока широким хватом',
        'rs': [
            'Сядьте в тренажёр для тяги нижнего блока с длинной прямой рукоятью, поставив стопы на платформу и слегка согнув колени.',
            'Возьмитесь за рукоять прямым хватом заметно шире плеч и выпрямитесь; руки прямые. Это исходное положение.',
            'На выдохе подтяните рукоять к верху живота, разводя локти в стороны, и сожмите середину спины и задние дельты.',
            'На вдохе медленно отпустите рукоять вперёд до полного выпрямления рук.',
            'Выполните рекомендованное количество повторений: широкий хват смещает нагрузку с широчайших на середину спины.',
        ],
    },
    'cable_straight_back_seated_high_row_reverse_grip': {
        't': 'Cable Straight-Back Seated High Row - Reverse Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit at a row station with the pulley set above shoulder height and take the bar with an underhand grip at shoulder width.',
            'Sit tall with the spine vertical, the feet braced and the arms straight out in front of you. This is the starting position.',
            'Pull the bar down and into your lower ribs as you breathe out, keeping the torso completely upright and the elbows close to your sides.',
            'Let the bar return slowly along the same line as you breathe in, without leaning forward to follow it.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга верхнего блока к поясу сидя обратным хватом',
        'rs': [
            'Сядьте в тренажёр, установив блок выше уровня плеч, и возьмитесь за рукоять обратным хватом на ширине плеч.',
            'Сядьте ровно: позвоночник вертикален, стопы упираются в платформу, руки вытянуты вперёд. Это исходное положение.',
            'На выдохе притяните рукоять вниз и к нижним рёбрам, полностью сохраняя вертикальное положение корпуса и прижимая локти к бокам.',
            'На вдохе медленно верните рукоять по той же линии, не наклоняясь за ней вперёд.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'cable_straight_back_seated_row_v_grip': {
        't': 'Cable Straight-Back Seated Row - V-Grip',
        'eq': 'cable_machine', 'm': _PULL, 'p': ['back'],
        'en': [
            'Sit at a low pulley row station with a V-handle attached, feet on the platform and the knees slightly bent.',
            'Take the handle with the palms facing each other and sit up so the spine is vertical and the arms are straight. This is the starting position.',
            'Pull the handle into your navel as you breathe out while keeping the torso perfectly upright — the back never rocks backward to help.',
            'Let the handle travel forward slowly as you breathe in, allowing only the shoulder blades to open.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга нижнего блока с прямой спиной узким хватом',
        'rs': [
            'Сядьте в тренажёр для тяги нижнего блока с узкой рукоятью, поставив стопы на платформу и слегка согнув колени.',
            'Возьмитесь за рукоять ладонями друг к другу и выпрямитесь так, чтобы позвоночник был вертикален, а руки — прямыми. Это исходное положение.',
            'На выдохе подтяните рукоять к пупку, полностью сохраняя вертикальное положение корпуса: спина ни разу не отклоняется назад, помогая тяге.',
            'На вдохе медленно отпустите рукоять вперёд, позволяя разойтись только лопаткам.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'chin_ups_narrow_parallel_grip': {
        't': 'Chin-Up - Narrow Parallel Grip',
        'eq': 'pullup_bar', 'm': _PULL, 'p': ['lats'], 'd': 'intermediate',
        'en': [
            'Hang from parallel handles or a narrow neutral-grip bar with the palms facing each other and the arms straight.',
            'Pull the shoulders down away from your ears and brace the core. This is the starting position.',
            'Pull yourself up until your chest is close to the handles, breathing out and keeping the elbows travelling straight down rather than flaring.',
            'Lower yourself slowly to a full hang as you breathe in.',
            'Repeat for the prescribed amount of repetitions; the neutral grip is usually the kindest on the elbows and shoulders.',
        ],
        'ru': 'Подтягивания узким параллельным хватом',
        'rs': [
            'Повисните на параллельных рукоятях или на узкой нейтральной перекладине: ладони обращены друг к другу, руки прямые.',
            'Опустите плечи, отдаляя их от ушей, и напрягите живот. Это исходное положение.',
            'На выдохе подтянитесь, пока грудь не окажется близко к рукоятям; локти идут строго вниз, а не в стороны.',
            'На вдохе медленно опуститесь в полный вис.',
            'Выполните рекомендованное количество повторений: нейтральный хват обычно наиболее щадящий для локтей и плеч.',
        ],
    },
    'close_grip_chin_up': {
        't': 'Close-Grip Chin-Up',
        'eq': 'pullup_bar', 'm': _PULL, 'p': ['lats'], 'd': 'intermediate',
        'en': [
            'Hang from a bar with an underhand grip and the hands almost touching, arms straight.',
            'Pull the shoulder blades down and brace the core so the legs stay still. This is the starting position.',
            'Pull yourself up until your chin passes the bar, breathing out and keeping the elbows tight to your ribs.',
            'Lower yourself slowly to a full hang as you breathe in.',
            'Repeat for the prescribed amount of repetitions; the close grip puts more of the work on the biceps than a shoulder-width chin-up.',
        ],
        'ru': 'Подтягивания узким обратным хватом',
        'rs': [
            'Повисните на перекладине обратным хватом, поставив кисти почти вплотную друг к другу; руки прямые.',
            'Опустите лопатки и напрягите живот, чтобы ноги не раскачивались. Это исходное положение.',
            'На выдохе подтянитесь, пока подбородок не окажется выше перекладины, прижимая локти к рёбрам.',
            'На вдохе медленно опуститесь в полный вис.',
            'Выполните рекомендованное количество повторений: узкий хват нагружает бицепсы сильнее, чем подтягивания на ширине плеч.',
        ],
    },
    'commando_pull_up': {
        't': 'Commando Pull-Up',
        'eq': 'pullup_bar', 'm': _PULL, 'p': ['lats'], 'd': 'advanced',
        'en': [
            'Stand under the bar so it runs front to back over your head, and take it with both hands one in front of the other, palms facing each other.',
            'Hang with the arms straight and the body to one side of the bar. This is the starting position.',
            'Pull yourself up alongside the bar so one shoulder passes it and your head comes up on that side, breathing out.',
            'Lower slowly to a full hang, then repeat pulling up on the other side.',
            'Keep alternating sides for the prescribed amount of repetitions.',
        ],
        'ru': 'Подтягивания «коммандо»',
        'rs': [
            'Встаньте под перекладиной так, чтобы она проходила спереди назад над головой, и возьмитесь за неё обеими руками одна за другой, ладонями друг к другу.',
            'Повисните на прямых руках, корпус смещён в одну сторону от перекладины. Это исходное положение.',
            'На выдохе подтянитесь вдоль перекладины так, чтобы одно плечо прошло мимо неё, а голова поднялась с этой стороны.',
            'Медленно опуститесь в полный вис, затем повторите, поднимаясь с другой стороны.',
            'Чередуйте стороны нужное количество повторений.',
        ],
    },
    'dumbbell_bent_over_row': {
        't': 'Dumbbell Bent-Over Row',
        'eq': 'dumbbell', 'm': _PULL, 'p': ['back'], 'min': 8,
        'ru': 'Тяга гантелей в наклоне',
        'rs': [
            'Возьмите по гантели в каждую руку (ладони обращены к корпусу), слегка согните колени и наклоните корпус вперёд от тазобедренных суставов, сохраняя спину прямой, почти до параллели с полом. Подсказка: голову держите поднятой. Гантели висят прямо перед вами, руки перпендикулярны полу и корпусу. Это исходное положение.',
            'Не двигая корпусом, на выдохе поднимите гантели к бокам, держа локти близко к телу (предплечья только удерживают вес). В верхней точке сожмите мышцы спины и задержитесь на секунду.',
            'На вдохе медленно опустите вес обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_deadlift': {
        't': 'Dumbbell Deadlift',
        'eq': 'dumbbell', 'm': _DL, 'p': ['hamstrings'], 'min': 8,
        'en': [
            'Stand with the feet hip width apart and a dumbbell on the floor outside each foot.',
            'Push the hips back, bend the knees and take a dumbbell in each hand with the back flat, the chest up and the arms straight. This is the starting position.',
            'Stand up by driving the floor away with the legs and extending the hips, breathing out and keeping the dumbbells close to your legs.',
            'Reverse the movement to set the dumbbells back down, breathing in and letting the hips travel back before the knees bend.',
            'Repeat for the prescribed amount of repetitions, keeping the back flat on every one.',
        ],
        'ru': 'Становая тяга с гантелями',
        'rs': [
            'Встаньте, стопы на ширине таза, по гантели на полу снаружи от каждой стопы.',
            'Отведите таз назад, согните колени и возьмите по гантели в каждую руку; спина прямая, грудь развёрнута, руки выпрямлены. Это исходное положение.',
            'На выдохе выпрямитесь, отталкиваясь ногами от пола и разгибая таз; гантели идут близко к ногам.',
            'На вдохе повторите движение в обратном порядке и поставьте гантели на пол, сначала отводя таз назад и только затем сгибая колени.',
            'Выполните рекомендованное количество повторений, сохраняя прямую спину в каждом из них.',
        ],
    },
    'dumbbell_hammer_grip_incline_bench_row': {
        't': 'Dumbbell Hammer-Grip Incline Bench Row',
        'eq': 'dumbbell', 'm': _PULL, 'p': ['back'],
        'en': [
            'Set a bench to about 45 degrees and lie face down on it with a dumbbell in each hand, palms facing each other.',
            'Let the arms hang straight down and press the chest into the pad. This is the starting position.',
            'Row both dumbbells up to your ribs as you breathe out, keeping the elbows close to the body and squeezing the shoulder blades together.',
            'Lower the dumbbells slowly back to arm\'s length as you breathe in.',
            'Repeat for the prescribed amount of repetitions; the chest support removes the lower back from the movement entirely.',
        ],
        'ru': 'Тяга гантелей нейтральным хватом лёжа на наклонной скамье',
        'rs': [
            'Установите скамью под углом около 45 градусов и лягте на неё грудью вниз с гантелями в руках, ладони обращены друг к другу.',
            'Позвольте рукам свободно свисать вниз и прижмите грудь к скамье. Это исходное положение.',
            'На выдохе подтяните обе гантели к рёбрам, держа локти близко к корпусу и сводя лопатки.',
            'На вдохе медленно опустите гантели на прямые руки.',
            'Выполните рекомендованное количество повторений: упор в скамью полностью снимает нагрузку с поясницы.',
        ],
    },
    'dumbbell_incline_row': {
        't': 'Dumbbell Incline Row',
        'eq': 'dumbbell', 'm': _PULL, 'p': ['back'],
        'ru': 'Тяга гантелей на наклонной скамье',
        'rs': [
            'Возьмите нейтральный хват и лягте грудью на наклонную скамью.',
            'Возьмите по гантели в каждую руку нейтральным хватом; начните с прямых рук. Это исходное положение.',
            'Сведите лопатки и, сгибая локти, подтяните гантели к бокам.',
            'Задержитесь в верхней точке и вернитесь в исходное положение.',
        ],
    },
    'dumbbell_lying_rear_delt_row': {
        't': 'Dumbbell Lying Rear Delt Row',
        'eq': 'dumbbell', 'm': ['shoulders', 'back'], 'p': ['shoulders'],
        'en': [
            'Set a bench to a shallow incline and lie face down on it with a dumbbell in each hand hanging straight below your shoulders.',
            'Turn the palms to face your feet and keep the chest on the pad. This is the starting position.',
            'Row both dumbbells up with the elbows flared out to the sides, so the upper arms finish level with your shoulders, breathing out.',
            'Lower the dumbbells slowly back to arm\'s length as you breathe in.',
            'Repeat for the prescribed amount of repetitions; flaring the elbows is what moves the work from the lats to the rear shoulders.',
        ],
        'ru': 'Тяга гантелей на заднюю дельту лёжа',
        'rs': [
            'Установите скамью под небольшим наклоном и лягте на неё грудью вниз; гантели свисают прямо под плечами.',
            'Разверните ладони в сторону стоп и прижмите грудь к скамье. Это исходное положение.',
            'На выдохе подтяните обе гантели вверх, разводя локти в стороны так, чтобы плечи оказались на одном уровне с плечевыми суставами.',
            'На вдохе медленно опустите гантели на прямые руки.',
            'Выполните рекомендованное количество повторений: именно разведение локтей переносит нагрузку с широчайших на задние дельты.',
        ],
    },
    'dumbbell_palm_rotational_bent_over_row': {
        't': 'Dumbbell Palm-Rotational Bent-Over Row',
        'eq': 'dumbbell', 'm': _PULL, 'p': ['back'],
        'en': [
            'Stand holding a dumbbell in each hand with the palms facing back, then hinge forward from the hips until the torso is close to parallel with the floor.',
            'Let the dumbbells hang at arm\'s length with the back flat and the head in line with the spine. This is the starting position.',
            'Row both dumbbells to your ribs as you breathe out, rotating the wrists as you pull so the palms face your torso at the top.',
            'Lower the dumbbells slowly and rotate the palms back to face behind you as you breathe in.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга гантелей в наклоне с разворотом кистей',
        'rs': [
            'Встаньте с гантелями в руках, ладони обращены назад, и наклонитесь вперёд от тазобедренных суставов почти до параллели корпуса с полом.',
            'Гантели висят на прямых руках, спина прямая, голова на одной линии с позвоночником. Это исходное положение.',
            'На выдохе подтяните обе гантели к рёбрам, разворачивая кисти по ходу движения так, чтобы в верхней точке ладони смотрели на корпус.',
            'На вдохе медленно опустите гантели, разворачивая ладони обратно назад.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_reverse_grip_row': {
        't': 'Dumbbell Reverse-Grip Row',
        'eq': 'dumbbell', 'm': _PULL, 'p': ['back'],
        'en': [
            'Stand holding a dumbbell in each hand with an underhand grip, palms facing forward, feet hip width apart.',
            'Hinge forward from the hips to about 45 degrees with the back flat and the arms hanging straight. This is the starting position.',
            'Pull both dumbbells into your lower ribs as you breathe out, keeping the elbows tucked tight to your sides.',
            'Lower them slowly back to arm\'s length as you breathe in without letting the torso rise.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга гантелей обратным хватом',
        'rs': [
            'Встаньте с гантелями в руках обратным хватом, ладони обращены вперёд, стопы на ширине таза.',
            'Наклонитесь вперёд от тазобедренных суставов примерно до 45 градусов; спина прямая, руки свободно свисают. Это исходное положение.',
            'На выдохе подтяните обе гантели к нижним рёбрам, плотно прижимая локти к бокам.',
            'На вдохе медленно опустите их на прямые руки, не поднимая корпус.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_stiff_leg_deadlift': {
        't': 'Dumbbell Stiff-Leg Deadlift',
        'eq': 'dumbbell', 'm': _DL, 'p': ['hamstrings'], 'min': 8,
        'ru': 'Становая тяга с гантелями на прямых ногах',
        'rs': [
            'Возьмите пару гантелей и удерживайте их по бокам на прямых руках.',
            'Встаньте прямо, стопы на ширине плеч или уже, колени слегка согнуты. Это исходное положение.',
            'Не меняя угла в коленях, опускайте гантели к стопам, наклоняясь в тазобедренных суставах и сохраняя прямую спину. Продолжайте наклон, будто хотите поднять что-то с пола, пока не почувствуете растяжение задней поверхности бедра. На этом движении делайте выдох.',
            'Начните выпрямлять корпус, разгибая таз и поясницу, пока не вернётесь в исходное положение. На этом движении делайте вдох.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'hammer_grip_pull_up': {
        't': 'Hammer-Grip Pull-Up',
        'eq': 'pullup_bar', 'm': _PULL, 'p': ['lats'], 'd': 'intermediate',
        'en': [
            'Hang from two parallel handles with the palms facing each other and the arms straight.',
            'Pull the shoulders down away from your ears and squeeze the glutes so the body stays rigid. This is the starting position.',
            'Pull yourself up until your chin is level with the handles, breathing out and keeping the elbows driving straight down.',
            'Lower yourself slowly to a full hang as you breathe in.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подтягивания нейтральным хватом',
        'rs': [
            'Повисните на двух параллельных рукоятях ладонями друг к другу; руки прямые.',
            'Опустите плечи, отдаляя их от ушей, и напрягите ягодицы, чтобы тело оставалось жёстким. Это исходное положение.',
            'На выдохе подтянитесь, пока подбородок не окажется на уровне рукоятей; локти идут строго вниз.',
            'На вдохе медленно опуститесь в полный вис.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'inverted_row_between_chairs': {
        't': 'Inverted Row Between Chairs',
        'eq': None, 'm': _PULL, 'p': ['back'],
        'en': [
            'Wedge a solid bar or broom handle between two sturdy chairs at about hip height and check that it takes your weight before you hang from it.',
            'Lie underneath and take the bar with an overhand grip a little wider than shoulder width, heels on the floor and the body straight. This is the starting position.',
            'Pull your chest to the bar as you breathe out, squeezing the shoulder blades together and keeping the hips level with the shoulders.',
            'Lower yourself slowly until the arms are straight as you breathe in.',
            'Repeat for the prescribed amount of repetitions, bending the knees to make it easier.',
        ],
        'ru': 'Австралийские подтягивания между стульями',
        'rs': [
            'Закрепите прочную палку или гриф между двумя устойчивыми стульями примерно на высоте таза и убедитесь, что конструкция выдерживает вес, прежде чем повисать на ней.',
            'Лягте под палку и возьмитесь прямым хватом чуть шире плеч; пятки на полу, тело вытянуто в линию. Это исходное положение.',
            'На выдохе подтяните грудь к палке, сводя лопатки и удерживая таз на одной линии с плечами.',
            'На вдохе медленно опуститесь до полного выпрямления рук.',
            'Выполните рекомендованное количество повторений; чтобы облегчить упражнение, согните колени.',
        ],
    },
    'kettlebell_deadlift': {
        't': 'Kettlebell Deadlift',
        'eq': 'kettlebell', 'm': _DL, 'p': ['hamstrings'], 'min': 8,
        'en': [
            'Stand with the feet hip width apart and a kettlebell on the floor between your arches.',
            'Push the hips back, bend the knees and take the handle with both hands, arms straight, back flat and chest up. This is the starting position.',
            'Stand up by driving through the whole foot and extending the hips, breathing out and keeping the bell close to your shins.',
            'Push the hips back to lower the bell to the floor as you breathe in, letting the knees bend only after the hips have travelled back.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Становая тяга с гирей',
        'rs': [
            'Встаньте, стопы на ширине таза, гиря стоит на полу между сводами стоп.',
            'Отведите таз назад, согните колени и возьмитесь за ручку обеими руками; руки прямые, спина прямая, грудь развёрнута. Это исходное положение.',
            'На выдохе выпрямитесь, отталкиваясь всей стопой и разгибая таз; гиря идёт близко к голеням.',
            'На вдохе отведите таз назад и опустите гирю на пол, сгибая колени только после того, как таз ушёл назад.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_back_extension': {
        't': 'Machine Back Extension',
        'eq': 'back_extension', 'm': ['lower_back', 'glutes'],
        'p': ['lower_back'],
        'en': [
            'Set the seat and the roller of the back extension machine so the pad sits across your upper back and your feet reach the platform.',
            'Sit tall with the belt fastened if the machine has one, and cross the arms over your chest. This is the starting position.',
            'Push back against the pad by extending the hips and the lower back until the torso is roughly in line with the thighs, breathing out.',
            'Return slowly to the upright position as you breathe in, without letting the weight pull you into a rounded back.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Разгибание спины в тренажёре',
        'rs': [
            'Отрегулируйте сиденье и упор тренажёра так, чтобы подушка легла на верх спины, а стопы доставали до платформы.',
            'Сядьте ровно, застегните ремень, если он есть, и скрестите руки на груди. Это исходное положение.',
            'На выдохе отклонитесь назад, продавливая упор за счёт разгибания таза и поясницы, пока корпус не окажется примерно на одной линии с бёдрами.',
            'На вдохе медленно вернитесь в вертикальное положение, не позволяя весу скруглить спину.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_high_row': {
        't': 'Machine High Row',
        'eq': 'seated_row_machine', 'm': _PULL, 'p': ['lats'],
        'en': [
            'Set the chest pad of the high row machine so the handles start just above shoulder height when you sit down.',
            'Take a handle in each hand with the arms straight and the chest pressed into the pad. This is the starting position.',
            'Pull the handles down and back toward your ribs as you breathe out, driving with the elbows and squeezing the lats.',
            'Let the handles travel back up and forward slowly as you breathe in until the shoulder blades open.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Верхняя тяга в тренажёре',
        'rs': [
            'Отрегулируйте упор для груди так, чтобы в положении сидя рукояти начинались чуть выше уровня плеч.',
            'Возьмитесь за рукояти обеими руками; руки прямые, грудь прижата к упору. Это исходное положение.',
            'На выдохе притяните рукояти вниз и назад к рёбрам, ведя движение локтями и сжимая широчайшие мышцы.',
            'На вдохе медленно позвольте рукоятям уйти вверх и вперёд, пока лопатки не разойдутся.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_reverse_t_bar_row': {
        't': 'Machine Reverse-Grip T-Bar Row',
        'eq': 't_bar_row', 'm': _PULL, 'p': ['back'], 'min': 8,
        'en': [
            'Load the T-bar row, stand on the platform and lie your chest against the support pad with the feet flat.',
            'Take the handles with an underhand grip and let the arms hang straight down. This is the starting position.',
            'Pull the bar up into your abdomen as you breathe out, keeping the elbows tucked close to your sides and the chest on the pad.',
            'Lower the bar slowly back to arm\'s length as you breathe in.',
            'Repeat for the prescribed amount of repetitions; the underhand grip brings the lower lats into the pull.',
        ],
        'ru': 'Т-тяга в тренажёре обратным хватом',
        'rs': [
            'Нагрузите тренажёр, встаньте на платформу и лягте грудью на упор, поставив стопы ровно.',
            'Возьмитесь за рукояти обратным хватом и позвольте рукам свободно свисать вниз. Это исходное положение.',
            'На выдохе подтяните гриф к животу, прижимая локти к бокам и не отрывая грудь от упора.',
            'На вдохе медленно опустите гриф на прямые руки.',
            'Выполните рекомендованное количество повторений: обратный хват сильнее включает нижнюю часть широчайших мышц.',
        ],
    },
    'reverse_grip_machine_lat_pulldown': {
        't': 'Reverse-Grip Machine Lat Pulldown',
        'eq': 'lat_pulldown', 'm': _PULL, 'p': ['lats'],
        'en': [
            'Sit at the lat pulldown station and set the thigh pads so they hold you down firmly.',
            'Take the bar with an underhand grip at shoulder width, sit tall and lean back about 20 degrees. This is the starting position.',
            'Pull the bar to the top of your chest as you breathe out, driving the elbows down and back and squeezing the lats at the bottom.',
            'Let the bar rise slowly to full arm extension as you breathe in, keeping the torso still.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга верхнего блока в тренажёре обратным хватом',
        'rs': [
            'Сядьте в тренажёр для тяги верхнего блока и отрегулируйте валики так, чтобы они надёжно фиксировали бёдра.',
            'Возьмитесь за рукоять обратным хватом на ширине плеч, сядьте ровно и отклоните корпус назад примерно на 20 градусов. Это исходное положение.',
            'На выдохе притяните рукоять к верху груди, направляя локти вниз и назад и сжимая широчайшие в нижней точке.',
            'На вдохе медленно позвольте рукояти подняться до полного выпрямления рук, не двигая корпусом.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'reverse_grip_pull_up': {
        't': 'Reverse-Grip Pull-Up',
        'eq': 'pullup_bar', 'm': _PULL, 'p': ['lats'], 'd': 'intermediate',
        'en': [
            'Hang from a bar with an underhand grip slightly wider than shoulder width and the arms straight.',
            'Pull the shoulders down, brace the core and cross the ankles. This is the starting position.',
            'Pull yourself up until your chin clears the bar, breathing out and leading with the chest rather than the head.',
            'Lower yourself slowly to a full hang as you breathe in, resisting all the way down.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подтягивания обратным хватом чуть шире плеч',
        'rs': [
            'Повисните на перекладине обратным хватом чуть шире плеч; руки прямые.',
            'Опустите плечи, напрягите живот и скрестите лодыжки. Это исходное положение.',
            'На выдохе подтянитесь, пока подбородок не окажется выше перекладины, ведя движение грудью, а не головой.',
            'На вдохе медленно опуститесь в полный вис, сопротивляясь на всём пути вниз.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'ring_high_row': {
        't': 'Ring High Row',
        'eq': 'trx', 'm': ['back', 'lats', 'shoulders'], 'p': ['back'],
        'd': 'intermediate',
        'en': [
            'Set a pair of rings or suspension handles at about chest height and take one in each hand with the palms facing down.',
            'Walk the feet forward and lean back with the arms straight, body in a straight line from the heels to the head. This is the starting position.',
            'Pull your chest toward the handles with the elbows flared out to shoulder height, breathing out and squeezing the shoulder blades together.',
            'Lower yourself slowly until the arms are straight again as you breathe in, keeping the hips from sagging.',
            'Repeat for the prescribed amount of repetitions; walk the feet back to make it easier.',
        ],
        'ru': 'Горизонтальная тяга на кольцах к груди',
        'rs': [
            'Установите кольца или петли примерно на высоте груди и возьмитесь за них обеими руками ладонями вниз.',
            'Отшагните стопами вперёд и отклонитесь назад на прямых руках; тело вытянуто в линию от пяток до головы. Это исходное положение.',
            'На выдохе подтяните грудь к рукоятям, разводя локти в стороны на уровень плеч и сводя лопатки.',
            'На вдохе медленно опуститесь до полного выпрямления рук, не позволяя тазу провисать.',
            'Выполните рекомендованное количество повторений; чтобы облегчить упражнение, отойдите стопами назад.',
        ],
    },
    'single_dumbbell_stiff_leg_deadlift': {
        't': 'Single-Dumbbell Stiff-Leg Deadlift',
        'eq': 'dumbbell', 'm': _DL, 'p': ['hamstrings'],
        'en': [
            'Stand with the feet hip width apart holding one dumbbell in both hands in front of your thighs.',
            'Set the back flat, the chest up and the knees almost straight. This is the starting position.',
            'Push the hips back and lower the dumbbell down the front of your legs as you breathe in, keeping it close to them.',
            'Stop when the hamstrings will not lengthen further without the back rounding, then drive the hips forward to stand up as you breathe out.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Становая тяга на прямых ногах с одной гантелью',
        'rs': [
            'Встаньте, стопы на ширине таза, удерживая одну гантель обеими руками перед бёдрами.',
            'Спина прямая, грудь развёрнута, колени почти выпрямлены. Это исходное положение.',
            'На вдохе отведите таз назад и опускайте гантель вдоль передней поверхности ног, удерживая её близко к ним.',
            'Остановитесь там, где задняя поверхность бедра больше не удлиняется без скругления спины, затем на выдохе выпрямитесь, выводя таз вперёд.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'smith_deadlift_deadlift': {
        't': 'Smith Machine Deadlift',
        'eq': 'smith_machine', 'm': _DL, 'p': ['hamstrings'],
        'd': 'intermediate', 'min': 8,
        'en': [
            'Set the bar of the Smith machine at the lowest position and stand with the feet hip width apart, shins close to it.',
            'Push the hips back, bend the knees and take the bar with an overhand grip just outside your legs, back flat and chest up. This is the starting position.',
            'Stand up by pushing the floor away with the legs and extending the hips, breathing out and unlocking the bar as it leaves the catches.',
            'Lower the bar along the rails by pushing the hips back first and then bending the knees, breathing in and keeping the back flat.',
            'Repeat for the prescribed amount of repetitions, then rotate the bar back into its hooks at the bottom.',
        ],
        'ru': 'Становая тяга в машине Смита',
        'rs': [
            'Установите гриф машины Смита в нижнее положение и встаньте, стопы на ширине таза, голени близко к грифу.',
            'Отведите таз назад, согните колени и возьмитесь за гриф прямым хватом чуть шире ног; спина прямая, грудь развёрнута. Это исходное положение.',
            'На выдохе выпрямитесь, отталкиваясь ногами от пола и разгибая таз; снимите гриф со стопоров в момент отрыва.',
            'На вдохе опускайте гриф по направляющим, сначала отводя таз назад и только затем сгибая колени; спина остаётся прямой.',
            'Выполните рекомендованное количество повторений, затем в нижней точке верните гриф на стопоры.',
        ],
    },
    'stretching_dynamic_back_stretch': {
        't': 'Dynamic Back Stretch',
        'eq': None, 'm': ['back', 'shoulders'], 'p': ['back'], 'stretch': True,
        'ru': 'Динамическая растяжка спины',
        'rs': [
            'Встаньте, стопы на ширине плеч. Это исходное положение.',
            'Не сгибая руки, махом поднимайте их прямо перед собой 5–10 раз, с каждым разом увеличивая амплитуду, пока руки не окажутся над головой.',
        ],
    },
    'stretching_elbows_back_stretch': {
        't': 'Elbows Back Stretch',
        'eq': None, 'm': ['back', 'chest', 'shoulders'], 'p': ['back'],
        'stretch': True,
        'en': [
            'Stand tall with the feet hip width apart and interlace the fingers behind your head.',
            'Lift the chest and keep the chin level. This is the starting position.',
            'Draw both elbows back and squeeze the shoulder blades together until the upper back and the front of the chest lengthen.',
            'Hold for 20 to 30 seconds, breathing steadily, then release.',
        ],
        'ru': 'Разведение локтей назад',
        'rs': [
            'Встаньте прямо, стопы на ширине таза, сцепите пальцы за головой.',
            'Приподнимите грудь, подбородок держите ровно. Это исходное положение.',
            'Отведите оба локтя назад и сведите лопатки, пока не удлинятся верх спины и передняя поверхность груди.',
            'Удерживайте 20–30 секунд, дыша ровно, затем расслабьтесь.',
        ],
    },
    'stretching_kneeling_lat_stretch': {
        't': 'Kneeling Lat Stretch',
        'eq': None, 'm': ['lats', 'back'], 'p': ['lats'], 'stretch': True,
        'en': [
            'Kneel in front of a bench or a low box, about an arm\'s length away, and place both hands on its edge.',
            'Sit the hips back toward your heels and keep the arms straight. This is the starting position.',
            'Let the chest sink toward the floor between your arms until you feel the stretch along the sides of your back.',
            'Hold for 20 to 30 seconds, breathing steadily, then sit up to release.',
        ],
        'ru': 'Растяжка широчайших мышц стоя на коленях',
        'rs': [
            'Встаньте на колени перед скамьёй или невысоким боксом примерно на расстоянии вытянутой руки и положите обе ладони на её край.',
            'Отведите таз назад к пяткам, руки остаются прямыми. Это исходное положение.',
            'Опускайте грудь к полу между рук, пока не почувствуете растяжение по бокам спины.',
            'Удерживайте 20–30 секунд, дыша ровно, затем выпрямитесь.',
        ],
    },
    'stretching_middle_back_stretch': {
        't': 'Middle Back Stretch',
        'eq': None, 'm': ['back', 'core'], 'p': ['back'], 'stretch': True,
        'ru': 'Растяжка середины спины',
        'rs': [
            'Встаньте, стопы на ширине плеч, ладони на поясе.',
            'Разворачивайте корпус в талии, пока не почувствуете растяжение. Удерживайте 10–15 секунд, затем разверните корпус в другую сторону.',
        ],
    },
    'stretching_seated_lower_back_stretch': {
        't': 'Seated Lower Back Stretch',
        'eq': None, 'm': ['lower_back'], 'stretch': True,
        'en': [
            'Sit on the front edge of a bench or chair with the feet flat and set wider than your hips.',
            'Sit tall and rest your hands on your thighs. This is the starting position.',
            'Bend forward between your knees and let the arms and head hang toward the floor so the lower back rounds gently.',
            'Hold for 20 to 30 seconds, breathing steadily, then roll up one vertebra at a time.',
        ],
        'ru': 'Растяжка поясницы сидя',
        'rs': [
            'Сядьте на передний край скамьи или стула, поставив стопы на пол шире таза.',
            'Сядьте ровно, положив ладони на бёдра. Это исходное положение.',
            'Наклонитесь вперёд между коленей, позволив рукам и голове свободно свисать к полу, чтобы поясница мягко скруглилась.',
            'Удерживайте 20–30 секунд, дыша ровно, затем поднимитесь, раскатывая позвоночник позвонок за позвонком.',
        ],
    },
    'stretching_seated_wide_angle_pose_sequence': {
        't': 'Seated Wide Angle Pose Sequence',
        'eq': None, 'm': ['adductors', 'hamstrings', 'lower_back'],
        'p': ['adductors'], 'stretch': True,
        'en': [
            'Sit on the floor and open both legs as wide as is comfortable, knees and toes pointing up.',
            'Sit tall on your sitting bones with the hands on the floor in front of you. This is the starting position.',
            'Walk the hands forward between your legs and fold from the hips, holding for 20 to 30 seconds.',
            'Walk the hands over toward one foot and hold for 20 to 30 seconds, then repeat toward the other foot.',
            'Come back to the middle, close the legs and shake them out.',
        ],
        'ru': 'Последовательность растяжки в широком угле сидя',
        'rs': [
            'Сядьте на пол и разведите ноги настолько широко, насколько это комфортно; колени и носки смотрят вверх.',
            'Сядьте ровно на седалищные кости, поставив ладони на пол перед собой. Это исходное положение.',
            'Переставляйте ладони вперёд между ног и складывайтесь от тазобедренных суставов; удерживайте 20–30 секунд.',
            'Переведите ладони к одной стопе и удерживайте 20–30 секунд, затем повторите к другой стопе.',
            'Вернитесь в центр, сведите ноги и потрясите ими, чтобы расслабить.',
        ],
    },
    'stretching_sitting_bent_over_back_stretch': {
        't': 'Sitting Bent-Over Back Stretch',
        'eq': None, 'm': ['back', 'hamstrings', 'lower_back'], 'p': ['back'],
        'stretch': True,
        'en': [
            'Sit on the floor with both legs extended in front of you and the feet hip width apart.',
            'Sit tall and lengthen the spine upward. This is the starting position.',
            'Fold forward from the hips and reach the hands toward your feet, letting the back round softly and the head hang.',
            'Hold for 20 to 30 seconds, breathing steadily, then roll up slowly to sitting.',
        ],
        'ru': 'Наклон вперёд сидя',
        'rs': [
            'Сядьте на пол, вытянув обе ноги перед собой, стопы на ширине таза.',
            'Сядьте ровно и вытяните позвоночник вверх. Это исходное положение.',
            'Складывайтесь вперёд от тазобедренных суставов, тянясь руками к стопам; спина мягко скругляется, голова свободно свисает.',
            'Удерживайте 20–30 секунд, дыша ровно, затем медленно раскатайтесь обратно в положение сидя.',
        ],
    },
    'stretching_spine_stretch': {
        't': 'Spine Stretch',
        'eq': None, 'm': ['back', 'lower_back', 'core'], 'p': ['back'],
        'stretch': True,
        'en': [
            'Kneel on all fours with the hands under the shoulders and the knees under the hips.',
            'Set the spine level from the tailbone to the head. This is the starting position.',
            'Round the back up toward the ceiling as you breathe out, dropping the head and tucking the tailbone under.',
            'Reverse it as you breathe in, letting the belly drop and the chest and tailbone lift so the spine arches the other way.',
            'Alternate slowly for 8 to 10 breaths.',
        ],
        'ru': 'Прогибы и скругления спины на четвереньках',
        'rs': [
            'Встаньте на четвереньки: ладони под плечами, колени под тазом.',
            'Выровняйте позвоночник от копчика до головы. Это исходное положение.',
            'На выдохе скруглите спину вверх, опуская голову и подкручивая копчик под себя.',
            'На вдохе выполните обратное движение: опустите живот, приподняв грудь и копчик, чтобы позвоночник прогнулся в другую сторону.',
            'Медленно чередуйте эти положения в течение 8–10 дыхательных циклов.',
        ],
    },
    'stretching_spine_stretch_forward': {
        't': 'Spine Stretch Forward',
        'eq': None, 'm': ['back', 'hamstrings', 'core'], 'p': ['back'],
        'stretch': True,
        'en': [
            'Sit tall on the floor with the legs extended a little wider than your hips and the feet flexed.',
            'Reach both arms straight forward at shoulder height. This is the starting position.',
            'Drop the chin and roll the spine forward one vertebra at a time as you breathe out, reaching the hands along the floor between your legs.',
            'Roll back up to sitting tall the same way as you breathe in, stacking the spine from the base upward.',
            'Repeat for 5 to 8 slow repetitions.',
        ],
        'ru': 'Скругление позвоночника вперёд сидя',
        'rs': [
            'Сядьте на полу с прямой спиной, разведя ноги чуть шире таза; носки натянуты на себя.',
            'Вытяните обе руки прямо перед собой на уровне плеч. Это исходное положение.',
            'На выдохе опустите подбородок и скругляйте позвоночник вперёд позвонок за позвонком, вытягивая руки по полу между ног.',
            'На вдохе так же, позвонок за позвонком, раскатайтесь обратно в положение сидя, выстраивая позвоночник снизу вверх.',
            'Выполните 5–8 медленных повторений.',
        ],
    },
    'stretching_standing_back_rotation_stretch': {
        't': 'Standing Back Rotation Stretch',
        'eq': None, 'm': ['back', 'core'], 'p': ['back'], 'stretch': True,
        'en': [
            'Stand with the feet shoulder width apart and the knees soft, arms bent and held in front of your chest.',
            'Brace the core and keep the hips facing forward. This is the starting position.',
            'Rotate the upper body to one side as far as it will comfortably go, letting the head follow the chest.',
            'Return to the middle and rotate to the other side, alternating for 20 to 30 seconds.',
        ],
        'ru': 'Развороты корпуса стоя',
        'rs': [
            'Встаньте, стопы на ширине плеч, колени мягкие, руки согнуты перед грудью.',
            'Напрягите живот и удерживайте таз направленным вперёд. Это исходное положение.',
            'Разверните верх тела в одну сторону настолько, насколько это комфортно; голова следует за грудью.',
            'Вернитесь в середину и разверните корпус в другую сторону, чередуя 20–30 секунд.',
        ],
    },
    'stretching_standing_lateral_stretch': {
        't': 'Standing Lateral Stretch',
        'eq': None, 'm': ['core', 'lats'], 'p': ['lats'], 'stretch': True,
        'ru': 'Боковое вытяжение стоя',
        'rs': [
            'Поставьте стопы чуть шире таза, колени слегка согнуты.',
            'Положите правую ладонь на правое бедро, поддерживая позвоночник.',
            'Поднимите левую руку строго вверх и положите левую ладонь на затылок. Удерживая её там, наклоните корпус вправо.',
            'Распределяйте вес поровну между обеими ногами (не заваливайтесь на левое бедро). Смените сторону.',
        ],
    },
    'lever_t_bar_row': {
        't': 'Machine T-Bar Row',
        'eq': 't_bar_row', 'm': ['back', 'lats', 'biceps'], 'p': ['back'],
        'min': 8,
        'ru': 'Т-тяга в тренажёре с упором в грудь',
        'rs': [
            'Нагрузите тренажёр нужным весом и отрегулируйте высоту так, чтобы верх груди оказался у верхнего края упора. Подсказка: в некоторых тренажёрах регулировки нет — тогда встаньте на подходящую ступень, чтобы верх груди был на уровне края подушки.',
            'Лягте грудью на упор и возьмитесь за рукояти. Хват может быть сверху, снизу или нейтральным — в зависимости от того, какую часть спины вы хотите нагрузить сильнее.',
            'Снимите гриф со стоек и выпрямите руки перед собой. Это исходное положение.',
            'На выдохе медленно поднимите вес и в верхней точке сожмите мышцы спины. Подсказка: держите плечи как можно ближе к корпусу, чтобы лучше включить мышцы спины. Не отрывайте тело от упора и не тяните вес бицепсами.',
            'После секундной паузы в верхней точке на вдохе медленно опустите вес в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'pull_up_wide_back_grip': {
        't': 'Pull-Up - Wide Grip Behind the Neck',
        'eq': 'pullup_bar', 'm': ['back', 'lats', 'biceps'], 'p': ['lats'],
        'd': 'advanced',
        'en': [
            'Hang from a pull-up bar with an overhand grip set well outside shoulder width, arms straight.',
            'Pull the shoulder blades down and keep the torso vertical, chin tucked slightly. This is the starting position.',
            'Pull yourself up so the bar passes behind your head and stop when it is level with the base of your neck, breathing out.',
            'Lower yourself slowly to a full hang as you breathe in.',
            'Repeat for the prescribed amount of repetitions, and use the front version instead if the shoulders feel pinched at the top -- behind-the-neck pulling asks for a lot of shoulder rotation.',
        ],
        'ru': 'Подтягивания широким хватом за голову',
        'rs': [
            'Повисните на перекладине прямым хватом заметно шире плеч; руки прямые.',
            'Опустите лопатки, держите корпус вертикально, подбородок слегка подобран. Это исходное положение.',
            'На выдохе подтянитесь так, чтобы перекладина прошла за голову, и остановитесь, когда она окажется на уровне основания шеи.',
            'На вдохе медленно опуститесь в полный вис.',
            'Выполните рекомендованное количество повторений; если в верхней точке в плечах появляется защемление, выбирайте вариант к груди — подтягивания за голову требуют большой подвижности плечевых суставов.',
        ],
    },
    'pull_up_wide_front_grip': {
        't': 'Pull-Up - Wide Grip to the Chest',
        'eq': 'pullup_bar', 'm': ['back', 'lats', 'biceps'], 'p': ['lats'],
        'd': 'intermediate',
        'en': [
            'Hang from a pull-up bar with an overhand grip set well outside shoulder width, arms straight and ankles crossed.',
            'Pull the shoulder blades down away from your ears and brace the core. This is the starting position.',
            'Pull yourself up by driving the elbows down and back until your upper chest is close to the bar, breathing out and keeping the chest lifted.',
            'Lower yourself slowly to a full hang as you breathe in, resisting all the way.',
            'Repeat for the prescribed amount of repetitions; the wide grip puts most of the work on the lats.',
        ],
        'ru': 'Подтягивания широким хватом к груди',
        'rs': [
            'Повисните на перекладине прямым хватом заметно шире плеч: руки прямые, лодыжки скрещены.',
            'Опустите лопатки, отдаляя плечи от ушей, и напрягите живот. Это исходное положение.',
            'На выдохе подтянитесь, направляя локти вниз и назад, пока верх груди не окажется близко к перекладине; грудь держите развёрнутой.',
            'На вдохе медленно опуститесь в полный вис, сопротивляясь на всём пути.',
            'Выполните рекомендованное количество повторений: широкий хват переносит основную работу на широчайшие мышцы.',
        ],
    },
}
