# -*- coding: utf-8 -*-
"""Chest. 32 rows: 1 dropped as a duplicate clip, 6 merge, 25 authored here.

`push_ups` is the one replaced match: upstream paired it with a HANDSTAND
push-up ("kick yourself up against the wall"), which is a different exercise at
a different difficulty and would have shipped as the beginner push-up card.
"""
_CHEST = ['chest', 'shoulders', 'triceps']

ENTRIES = {
    'band_high_fly': {
        't': 'Band High Fly',
        'eq': 'resistance_bands', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Anchor a resistance band above head height behind you and take an end in each hand, stepping forward until the band is under tension.',
            'Stand in a split stance with the arms out to the sides at shoulder height and a soft bend in the elbows. This is the starting position.',
            'Sweep both hands down and together in front of your chest as you breathe out, following an arc rather than pushing straight forward.',
            'Let the bands draw the arms back out to the sides slowly as you breathe in, stopping when you feel the chest stretch, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Сведение рук с лентой сверху',
        'rs': [
            'Закрепите ленту выше уровня головы за собой, возьмите по концу в каждую руку и сделайте шаг вперёд, чтобы лента натянулась.',
            'Встаньте в разножку, руки разведены в стороны на уровне плеч, локти слегка согнуты. Это исходное положение.',
            'На выдохе сведите руки вниз и вперёд перед грудью по дуге, а не толкая их прямо перед собой.',
            'На вдохе медленно позвольте ленте развести руки обратно в стороны, остановившись при ощущении растяжения в груди, и выполните рекомендованное количество повторений.',
        ],
    },
    'cable_lying_fly_flat_bench_cable_fly': {
        't': 'Cable Lying Fly on a Flat Bench',
        'eq': 'cable_machine', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Set a flat bench between two low pulleys and take a handle in each hand before lying back on it.',
            'Press both handles up over your chest with the arms almost straight and the palms facing each other, elbows slightly bent. This is the starting position.',
            'Open the arms out to the sides in a wide arc as you breathe in, until the hands are level with your chest and you feel a stretch across it.',
            'Bring the handles back together above your chest along the same arc as you breathe out, and squeeze for a second at the top.',
            'Repeat for the prescribed amount of repetitions, keeping the elbow angle fixed throughout.',
        ],
        'ru': 'Сведение рук на блоках лёжа на скамье',
        'rs': [
            'Поставьте горизонтальную скамью между двумя нижними блоками, возьмите по рукояти в каждую руку и лягте на скамью.',
            'Выжмите обе рукояти над грудью почти на прямых руках, ладони обращены друг к другу, локти слегка согнуты. Это исходное положение.',
            'На вдохе разведите руки в стороны по широкой дуге, пока кисти не окажутся на уровне груди и не появится растяжение в грудных мышцах.',
            'На выдохе сведите рукояти обратно над грудью по той же дуге и на секунду задержитесь в сокращении.',
            'Выполните рекомендованное количество повторений, сохраняя угол в локтях неизменным.',
        ],
    },
    'cable_standing_fly_crossover_fly': {
        't': 'Standing Cable Crossover Fly',
        'eq': 'cable_machine', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Set both pulleys above head height, take a handle in each hand and step forward into a split stance with the arms out to the sides.',
            'Lean the torso slightly forward with a soft bend in the elbows and the chest lifted. This is the starting position.',
            'Draw both hands down and together in front of your hips as you breathe out, crossing one wrist slightly over the other at the end.',
            'Let the handles pull the arms back out and up along the same arc as you breathe in, until the chest is stretched.',
            'Repeat for the prescribed amount of repetitions, alternating which wrist crosses on top.',
        ],
        'ru': 'Сведение рук на верхних блоках стоя',
        'rs': [
            'Установите оба блока выше уровня головы, возьмите по рукояти в каждую руку и шагните вперёд в разножку, разведя руки в стороны.',
            'Слегка наклоните корпус вперёд, локти немного согнуты, грудь развёрнута. Это исходное положение.',
            'На выдохе сведите обе кисти вниз и вместе перед бёдрами, слегка заводя одно запястье за другое в конце движения.',
            'На вдохе позвольте рукоятям развести руки обратно вверх и в стороны по той же дуге до растяжения грудных мышц.',
            'Выполните рекомендованное количество повторений, чередуя, какое запястье оказывается сверху.',
        ],
    },
    'chest_dips': {
        't': 'Chest Dip',
        'eq': 'dip_station', 'm': _CHEST, 'p': ['chest'], 'd': 'intermediate',
        'ru': 'Отжимания на брусьях для грудных мышц',
        'rs': [
            'Для этого упражнения нужны брусья. Чтобы принять исходное положение, поднимите себя на прямых, зафиксированных руках над брусьями.',
            'На вдохе медленно опускайтесь, наклонив корпус вперёд примерно на 30 градусов и слегка разведя локти, пока не почувствуете лёгкое растяжение в груди.',
            'Почувствовав растяжение, на выдохе усилием грудных мышц вернитесь в исходное положение. Подсказка: в верхней точке на секунду напрягите грудные мышцы.',
            'Выполните нужное количество повторений.',
        ],
    },
    'deep_push_ups': {
        't': 'Deep Push-Up',
        'eq': None, 'm': _CHEST, 'p': ['chest'], 'd': 'intermediate',
        'en': [
            'Place two low parallettes, or a pair of dumbbells set on their ends, at shoulder width and take a push-up position gripping them.',
            'Brace the core and the glutes so the body forms a straight line from the heels to the head. This is the starting position.',
            'Bend the elbows and lower your chest between the handles as you breathe in, going deeper than the floor would allow until the chest stretches.',
            'Press back up to straight arms as you breathe out, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Глубокие отжимания на упорах',
        'rs': [
            'Поставьте на ширине плеч два невысоких упора для отжиманий или пару гантелей на торцы и примите упор лёжа, взявшись за них.',
            'Напрягите живот и ягодицы, чтобы тело вытянулось в прямую линию от пяток до головы. Это исходное положение.',
            'На вдохе согните локти и опустите грудь между упорами глубже, чем позволяет пол, до ощущения растяжения в грудных мышцах.',
            'На выдохе выжмите себя вверх до полного выпрямления рук и выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_decline_fly_45_degree': {
        't': 'Dumbbell Decline Fly',
        'eq': 'dumbbell', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Set a bench to a decline of about 45 degrees, hook your legs over the pads and lie back holding a dumbbell in each hand.',
            'Press both dumbbells up over your chest with the palms facing each other and a slight bend in the elbows. This is the starting position.',
            'Open the arms out to the sides in a wide arc as you breathe in, lowering until the hands are level with your chest.',
            'Bring the dumbbells back together above your chest along the same arc as you breathe out, and squeeze for a second.',
            'Repeat for the prescribed amount of repetitions, keeping the elbow angle fixed rather than pressing.',
        ],
        'ru': 'Разведение гантелей на наклонной скамье головой вниз',
        'rs': [
            'Установите скамью с наклоном вниз примерно 45 градусов, зафиксируйте ноги за валиками и лягте, взяв по гантели в каждую руку.',
            'Выжмите обе гантели над грудью, ладони обращены друг к другу, локти слегка согнуты. Это исходное положение.',
            'На вдохе разведите руки в стороны по широкой дуге, опуская гантели до уровня груди.',
            'На выдохе сведите гантели обратно над грудью по той же дуге и на секунду задержитесь в сокращении.',
            'Выполните рекомендованное количество повторений, сохраняя угол в локтях и не переходя на жим.',
        ],
    },
    'dumbbell_fly': {
        't': 'Dumbbell Fly',
        'eq': 'dumbbell', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Lie back on a flat bench with a dumbbell in each hand resting on your thighs, palms facing each other.',
            'Press the dumbbells up over your chest, then bend the elbows slightly and hold that angle. This is the starting position.',
            'Open the arms out to the sides in a wide arc as you breathe in, until the upper arms are level with the bench and the chest is stretched.',
            'Bring the dumbbells back together above your chest along the same arc as you breathe out, squeezing the chest for a second at the top.',
            'Repeat for the prescribed amount of repetitions, keeping the movement an arc rather than a press.',
        ],
        'ru': 'Разведение гантелей лёжа',
        'rs': [
            'Лягте на горизонтальную скамью, положив гантели на бёдра, ладони обращены друг к другу.',
            'Выжмите гантели над грудью, затем слегка согните локти и сохраняйте этот угол. Это исходное положение.',
            'На вдохе разведите руки в стороны по широкой дуге, пока плечи не окажутся на уровне скамьи, а грудные мышцы не растянутся.',
            'На выдохе сведите гантели обратно над грудью по той же дуге, на секунду напрягая грудные мышцы в верхней точке.',
            'Выполните рекомендованное количество повторений, сохраняя дуговую траекторию, а не жим.',
        ],
    },
    'dumbbell_fly_on_exercise_ball': {
        't': 'Dumbbell Fly on an Exercise Ball',
        'eq': 'dumbbell', 'm': ['chest', 'shoulders', 'triceps', 'core'],
        'p': ['chest'], 'd': 'intermediate',
        'en': [
            'Sit on a stability ball with a dumbbell in each hand, then walk your feet forward and lie back until the ball supports your shoulder blades and head.',
            'Lift the hips so the torso is level with the knees, press the dumbbells over your chest with the palms facing each other and bend the elbows slightly. This is the starting position.',
            'Open the arms out to the sides in a wide arc as you breathe in, keeping the hips high and the ball still.',
            'Bring the dumbbells back together above your chest as you breathe out, and squeeze for a second.',
            'Repeat for the prescribed amount of repetitions, stopping if the hips start to drop.',
        ],
        'ru': 'Разведение гантелей на гимнастическом мяче',
        'rs': [
            'Сядьте на гимнастический мяч с гантелями в руках, затем прошагайте стопами вперёд и лягте так, чтобы мяч поддерживал лопатки и голову.',
            'Поднимите таз, чтобы корпус был на одной линии с коленями, выжмите гантели над грудью ладонями друг к другу и слегка согните локти. Это исходное положение.',
            'На вдохе разведите руки в стороны по широкой дуге, удерживая таз поднятым, а мяч — неподвижным.',
            'На выдохе сведите гантели обратно над грудью и на секунду задержитесь в сокращении.',
            'Выполните рекомендованное количество повторений и прекратите подход, если таз начинает опускаться.',
        ],
    },
    'dumbbell_incline_fly': {
        't': 'Dumbbell Incline Fly',
        'eq': 'dumbbell', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Set a bench to an incline of about 30 to 45 degrees and lie back with a dumbbell in each hand resting on your thighs.',
            'Press both dumbbells up over your upper chest with the palms facing each other and a slight bend in the elbows. This is the starting position.',
            'Open the arms out to the sides in a wide arc as you breathe in, until the upper arms are level with your shoulders.',
            'Bring the dumbbells back together above your chest along the same arc as you breathe out, and squeeze for a second.',
            'Repeat for the prescribed amount of repetitions, keeping the shoulder blades pulled back against the bench.',
        ],
        'ru': 'Разведение гантелей на наклонной скамье',
        'rs': [
            'Установите скамью под наклоном примерно 30–45 градусов и лягте, положив гантели на бёдра.',
            'Выжмите обе гантели над верхом груди ладонями друг к другу, слегка согнув локти. Это исходное положение.',
            'На вдохе разведите руки в стороны по широкой дуге, пока плечи не окажутся на уровне плечевых суставов.',
            'На выдохе сведите гантели обратно над грудью по той же дуге и на секунду задержитесь в сокращении.',
            'Выполните рекомендованное количество повторений, удерживая лопатки сведёнными и прижатыми к скамье.',
        ],
    },
    'dumbbell_incline_fly_on_exercise_ball': {
        't': 'Dumbbell Incline Fly on an Exercise Ball',
        'eq': 'dumbbell', 'm': ['chest', 'shoulders', 'triceps', 'core'],
        'p': ['chest'], 'd': 'intermediate',
        'en': [
            'Sit on a stability ball with a dumbbell in each hand and walk the feet forward only a little, so the ball supports your upper back and you are reclined rather than flat.',
            'Press the dumbbells over your upper chest with the palms facing each other and a slight bend in the elbows. This is the starting position.',
            'Open the arms out to the sides in a wide arc as you breathe in, keeping the hips lifted and the ball still.',
            'Bring the dumbbells back together above your chest as you breathe out, and squeeze the chest for a second.',
            'Repeat for the prescribed amount of repetitions, keeping the head supported throughout.',
        ],
        'ru': 'Разведение гантелей на мяче с наклоном',
        'rs': [
            'Сядьте на гимнастический мяч с гантелями в руках и прошагайте стопами вперёд совсем немного, чтобы мяч поддерживал верх спины, а корпус остался наклонным, а не горизонтальным.',
            'Выжмите гантели над верхом груди ладонями друг к другу, слегка согнув локти. Это исходное положение.',
            'На вдохе разведите руки в стороны по широкой дуге, удерживая таз поднятым, а мяч — неподвижным.',
            'На выдохе сведите гантели обратно над грудью и на секунду напрягите грудные мышцы.',
            'Выполните рекомендованное количество повторений, всё время сохраняя опору под головой.',
        ],
    },
    'dumbbell_lying_hammer_press': {
        't': 'Dumbbell Lying Hammer Press',
        'eq': 'dumbbell', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Lie back on a flat bench with a dumbbell in each hand held at chest level, palms facing each other in a neutral grip.',
            'Tuck the elbows in to about 45 degrees from your ribs rather than flaring them out. This is the starting position.',
            'Press both dumbbells straight up over your chest as you breathe out, keeping the palms facing each other the whole way.',
            'Lower them back to chest level under control as you breathe in, feeling the stretch without letting the elbows drop below the bench.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Жим гантелей лёжа нейтральным хватом',
        'rs': [
            'Лягте на горизонтальную скамью, удерживая по гантели в каждой руке на уровне груди ладонями друг к другу.',
            'Прижмите локти примерно под 45 градусов к рёбрам, а не разводите их в стороны. Это исходное положение.',
            'На выдохе выжмите обе гантели вертикально вверх над грудью, всё время сохраняя нейтральное положение ладоней.',
            'На вдохе подконтрольно опустите гантели к груди, чувствуя растяжение, но не опуская локти ниже уровня скамьи.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'incline_push_ups': {
        't': 'Incline Push-Up',
        'eq': 'adjustable_bench', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Place your hands on the edge of a bench slightly wider than shoulder width and walk your feet back until the body is straight.',
            'Brace the core and the glutes so there is a straight line from the heels to the head. This is the starting position.',
            'Bend the elbows and lower your chest toward the bench as you breathe in, keeping the elbows at about 45 degrees from your ribs.',
            'Press back up to straight arms as you breathe out, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Отжимания от скамьи',
        'rs': [
            'Поставьте ладони на край скамьи чуть шире плеч и отшагните стопами назад, вытянув тело в прямую линию.',
            'Напрягите живот и ягодицы, чтобы линия от пяток до головы оставалась прямой. Это исходное положение.',
            'На вдохе согните локти и опустите грудь к скамье, удерживая локти примерно под 45 градусов к рёбрам.',
            'На выдохе выжмите себя вверх до полного выпрямления рук и выполните рекомендованное количество повторений.',
        ],
    },
    'lever_chest_press': {
        't': 'Machine Chest Press',
        'eq': 'chest_press_machine', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Set the seat so the handles sit level with the middle of your chest, then sit with your back flat against the pad.',
            'Take a handle in each hand with an overhand grip and keep the shoulder blades pulled back. This is the starting position.',
            'Press the handles forward until the arms are straight without locking the elbows, breathing out and keeping the back on the pad.',
            'Let the handles come back slowly until your hands are level with your chest, breathing in and feeling the stretch.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Жим от груди в тренажёре',
        'rs': [
            'Отрегулируйте сиденье так, чтобы рукояти были на уровне середины груди, и сядьте, прижав спину к спинке.',
            'Возьмитесь за рукояти прямым хватом и сведите лопатки. Это исходное положение.',
            'На выдохе выжмите рукояти вперёд до почти полного выпрямления рук, не блокируя локти и не отрывая спину от спинки.',
            'На вдохе медленно позвольте рукоятям вернуться, пока кисти не окажутся на уровне груди, чувствуя растяжение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_incline_hammer_chest_press': {
        't': 'Machine Incline Chest Press',
        'eq': 'chest_press_machine', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Set the seat of an incline press machine so the handles line up with the top of your chest, and sit back against the pad.',
            'Take the handles with a neutral or overhand grip, feet flat and shoulder blades pulled back. This is the starting position.',
            'Press the handles up and forward until the arms are almost straight as you breathe out, keeping the wrists in line with the forearms.',
            'Lower the handles slowly back to the top of your chest as you breathe in.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Жим в наклонном тренажёре для груди',
        'rs': [
            'Отрегулируйте сиденье наклонного тренажёра так, чтобы рукояти совпали с верхом груди, и сядьте, прижав спину к спинке.',
            'Возьмитесь за рукояти нейтральным или прямым хватом; стопы стоят на полу, лопатки сведены. Это исходное положение.',
            'На выдохе выжмите рукояти вверх и вперёд почти до полного выпрямления рук, удерживая запястья на одной линии с предплечьями.',
            'На вдохе медленно опустите рукояти обратно к верху груди.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_lying_chest_press': {
        't': 'Machine Lying Chest Press',
        'eq': 'chest_press_machine', 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Lie back on the bench of a lying press machine with the handles level with the middle of your chest.',
            'Take a handle in each hand with an overhand grip, feet flat on the floor and the lower back in its natural arch. This is the starting position.',
            'Press the handles straight up as you breathe out until the arms are almost straight, without locking the elbows.',
            'Lower the handles slowly back to chest level as you breathe in, keeping the elbows under the wrists.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Жим в тренажёре лёжа',
        'rs': [
            'Лягте на скамью тренажёра для жима лёжа так, чтобы рукояти были на уровне середины груди.',
            'Возьмитесь за рукояти прямым хватом; стопы стоят на полу, поясница сохраняет естественный прогиб. Это исходное положение.',
            'На выдохе выжмите рукояти вертикально вверх почти до полного выпрямления рук, не блокируя локти.',
            'На вдохе медленно опустите рукояти обратно на уровень груди, удерживая локти под запястьями.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_pec_deck_fly': {
        't': 'Pec Deck Fly',
        'eq': 'pec_deck', 'm': ['chest', 'shoulders'], 'p': ['chest'],
        'en': [
            'Set the seat so the handles sit level with your shoulders and sit with your back flat against the pad.',
            'Take a handle in each hand with the elbows slightly bent and the upper arms roughly parallel to the floor. This is the starting position.',
            'Bring the handles together in front of your chest as you breathe out, and hold the squeeze for a second.',
            'Open the arms back out slowly as you breathe in, stopping when the chest is stretched but the shoulders have not rolled forward.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Сведение рук в тренажёре «бабочка»',
        'rs': [
            'Отрегулируйте сиденье так, чтобы рукояти были на уровне плеч, и сядьте, прижав спину к спинке.',
            'Возьмитесь за рукояти, слегка согнув локти; плечи примерно параллельны полу. Это исходное положение.',
            'На выдохе сведите рукояти перед грудью и задержитесь в сокращении на секунду.',
            'На вдохе медленно разведите руки обратно, остановившись, когда грудные мышцы растянуты, но плечи ещё не завалились вперёд.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'push_ups': {
        't': 'Push-Up',
        'eq': None, 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Take a face-down position on the floor with the hands slightly wider than shoulder width and level with your chest.',
            'Push up onto straight arms and the balls of your feet, bracing the core and the glutes so the body forms a straight line. This is the starting position.',
            'Bend the elbows and lower your chest toward the floor as you breathe in, keeping the elbows at about 45 degrees from your ribs.',
            'Press back up to straight arms as you breathe out, keeping the hips level with the shoulders.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Отжимания от пола',
        'rs': [
            'Лягте лицом вниз и поставьте ладони чуть шире плеч на уровне груди.',
            'Выжмите себя вверх на прямые руки и подушечки стоп, напрягая живот и ягодицы, чтобы тело вытянулось в прямую линию. Это исходное положение.',
            'На вдохе согните локти и опустите грудь к полу, удерживая локти примерно под 45 градусов к рёбрам.',
            'На выдохе выжмите себя вверх до прямых рук, сохраняя таз на одной линии с плечами.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'stretching_above_head_chest_stretch': {
        't': 'Above-Head Chest Stretch',
        'eq': None, 'm': ['chest', 'shoulders'], 'p': ['chest'],
        'stretch': True,
        'en': [
            'Stand tall with the feet hip width apart and interlace your fingers behind your head, elbows pointing out to the sides.',
            'Lift the chest and pull the shoulder blades together. This is the starting position.',
            'Draw the elbows back and slightly up until you feel the stretch across the front of the chest and shoulders.',
            'Hold for 20 to 30 seconds, breathing steadily, then release.',
        ],
        'ru': 'Растяжка груди с руками за головой',
        'rs': [
            'Встаньте прямо, стопы на ширине таза, сцепите пальцы за головой, локти разведены в стороны.',
            'Поднимите грудь и сведите лопатки. Это исходное положение.',
            'Отведите локти назад и слегка вверх, пока не почувствуете растяжение по передней поверхности груди и плеч.',
            'Удерживайте 20–30 секунд, дыша ровно, затем расслабьтесь.',
        ],
    },
    'stretching_back_pec_stretch': {
        't': 'Behind-the-Back Pec Stretch',
        'eq': None, 'm': ['chest', 'shoulders'], 'p': ['chest'],
        'stretch': True,
        'en': [
            'Stand tall and clasp your hands together behind your back with the arms straight and the palms facing each other.',
            'Roll the shoulders back and down and lift the chest. This is the starting position.',
            'Raise the clasped hands away from your back until you feel a stretch across the chest and the front of the shoulders.',
            'Hold for 20 to 30 seconds without leaning forward, then lower the arms and release.',
        ],
        'ru': 'Растяжка грудных мышц с замком за спиной',
        'rs': [
            'Встаньте прямо и сцепите руки за спиной, выпрямив их, ладони обращены друг к другу.',
            'Отведите плечи назад и вниз, приподняв грудь. Это исходное положение.',
            'Поднимайте сцепленные руки от спины, пока не почувствуете растяжение в груди и по передней поверхности плеч.',
            'Удерживайте 20–30 секунд, не наклоняя корпус вперёд, затем опустите руки.',
        ],
    },
    'stretching_dynamic_chest_stretch': {
        't': 'Dynamic Chest Stretch',
        'eq': None, 'm': ['chest', 'shoulders'], 'p': ['chest'],
        'stretch': True,
        'ru': 'Динамическая растяжка груди',
        'rs': [
            'Встаньте, соединив ладони и вытянув руки прямо перед собой. Это исходное положение.',
            'Не сгибая руки, быстро разведите их максимально назад и снова сведите — движение похоже на утрированный хлопок. Повторите 5–10 раз, постепенно ускоряясь.',
        ],
    },
    'stretching_kneeling_back_rotation_stretch': {
        't': 'Kneeling Back Rotation Stretch',
        'eq': None, 'm': ['chest', 'back', 'shoulders'], 'p': ['chest'],
        'stretch': True,
        'en': [
            'Kneel on all fours with the hands under the shoulders and the knees under the hips.',
            'Place one hand behind your head with that elbow pointing down toward the supporting arm. This is the starting position.',
            'Rotate the torso to open that elbow up toward the ceiling, following it with your eyes, until the chest and mid-back stretch.',
            'Return slowly, repeat for 8 to 10 rotations, then change sides.',
        ],
        'ru': 'Ротация корпуса стоя на четвереньках',
        'rs': [
            'Встаньте на четвереньки: ладони под плечами, колени под тазом.',
            'Положите одну руку на затылок так, чтобы локоть смотрел вниз, к опорной руке. Это исходное положение.',
            'Разверните корпус, раскрывая этот локоть к потолку и провожая его взглядом, пока не почувствуете растяжение в груди и середине спины.',
            'Медленно вернитесь назад, выполните 8–10 разворотов и смените сторону.',
        ],
    },
    'stretching_standing_reach_up_back_rotation_stretch': {
        't': 'Standing Reach-Up Back Rotation Stretch',
        'eq': None, 'm': ['chest', 'back', 'shoulders'], 'p': ['chest'],
        'stretch': True,
        'en': [
            'Stand with the feet shoulder width apart and the knees soft, arms hanging at your sides.',
            'Reach one arm up and overhead, lengthening that side of the body. This is the starting position.',
            'Turn the chest toward the raised arm and let it travel back behind you, opening the front of the shoulder and the chest.',
            'Come back to the middle and repeat on the other side, alternating for 8 to 10 reaches each way.',
        ],
        'ru': 'Разворот корпуса с вытягиванием руки вверх',
        'rs': [
            'Встаньте, стопы на ширине плеч, колени мягкие, руки вдоль тела.',
            'Вытяните одну руку вверх над головой, удлиняя эту сторону тела. Это исходное положение.',
            'Разверните грудь в сторону поднятой руки и уведите её назад, раскрывая переднюю поверхность плеча и груди.',
            'Вернитесь в середину и повторите в другую сторону, чередуя по 8–10 раз на каждую.',
        ],
    },
    'stretching_standing_wheel_rollout': {
        't': 'Standing Wheel Rollout',
        'eq': None, 'm': ['core', 'lats', 'shoulders'], 'p': ['core'],
        'd': 'advanced', 'stretch': True,
        'en': [
            'Stand with the feet hip width apart, holding an ab wheel by both handles, and hinge forward to set it on the floor in front of your toes.',
            'Brace the core hard and tuck the pelvis so the lower back cannot arch. This is the starting position.',
            'Roll the wheel forward, letting the body extend toward the floor only as far as you can keep the lower back flat, and breathe in as you go.',
            'Pull the wheel back toward your feet with the abdominals as you breathe out, and stand back up.',
            'Repeat for the prescribed amount of repetitions, and stop the set the moment the lower back starts to sag.',
        ],
        'ru': 'Раскатывание ролика из положения стоя',
        'rs': [
            'Встаньте, стопы на ширине таза, возьмите ролик для пресса за обе рукояти и наклонитесь, поставив его на пол перед носками.',
            'Сильно напрягите живот и подкрутите таз так, чтобы поясница не прогибалась. Это исходное положение.',
            'На вдохе катите ролик вперёд, вытягивая тело к полу ровно настолько, насколько удаётся сохранять поясницу плоской.',
            'На выдохе усилием мышц живота подтяните ролик обратно к стопам и выпрямитесь.',
            'Выполните рекомендованное количество повторений и прекратите подход, как только поясница начнёт проваливаться.',
        ],
    },
    'triceps_dips': {
        't': 'Triceps Dip',
        'eq': 'dip_station', 'm': ['triceps', 'chest', 'shoulders'],
        'p': ['triceps'], 'd': 'intermediate',
        'ru': 'Отжимания на брусьях для трицепса',
        'rs': [
            'Чтобы принять исходное положение, поднимите себя на почти выпрямленных руках над брусьями.',
            'На вдохе медленно опускайтесь. Корпус остаётся вертикальным, а локти — прижатыми к телу: так нагрузка лучше ложится на трицепс. Опускайтесь, пока между плечом и предплечьем не образуется прямой угол.',
            'На выдохе усилием трицепсов выжмите корпус обратно в исходное положение.',
            'Выполните нужное количество повторений.',
        ],
    },
    'wide_grip_push_ups': {
        't': 'Wide-Grip Push-Up',
        'eq': None, 'm': _CHEST, 'p': ['chest'],
        'en': [
            'Take a push-up position with the hands well outside shoulder width and level with your chest, fingers pointing forward.',
            'Brace the core and the glutes so the body forms a straight line from the heels to the head. This is the starting position.',
            'Bend the elbows and lower your chest toward the floor as you breathe in; the wide hands put more of the work on the chest and less on the triceps.',
            'Press back up to straight arms as you breathe out, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Отжимания широким хватом',
        'rs': [
            'Примите упор лёжа, поставив ладони заметно шире плеч на уровне груди, пальцы направлены вперёд.',
            'Напрягите живот и ягодицы, чтобы тело вытянулось в прямую линию от пяток до головы. Это исходное положение.',
            'На вдохе согните локти и опустите грудь к полу; широкая постановка рук переносит нагрузку на грудные мышцы и снимает её с трицепсов.',
            'На выдохе выжмите себя вверх до полного выпрямления рук и выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_incline_bench_press': {
        't': 'Dumbbell Incline Bench Press',
        'eq': 'dumbbell', 'm': _CHEST, 'p': ['chest'], 'min': 8,
        'en': [
            'Set a bench to an incline of about 30 to 45 degrees and sit back with a dumbbell resting on each thigh, palms facing each other.',
            'Use your thighs to help bring the dumbbells up one at a time to shoulder width, then rotate the wrists so the palms face forward. This is the starting position.',
            'Press both dumbbells up over your upper chest as you breathe out until the arms are almost straight, without banging them together.',
            'Lower them slowly back to the sides of your chest as you breathe in, taking about twice as long as the press.',
            'Repeat for the prescribed amount of repetitions, then bring the dumbbells down onto your thighs before standing.',
        ],
        'ru': 'Жим гантелей на наклонной скамье',
        'rs': [
            'Установите скамью под наклоном 30–45 градусов и сядьте на неё, положив гантели на бёдра ладонями друг к другу.',
            'Помогая себе бёдрами, поочерёдно поднимите гантели на ширину плеч и разверните кисти ладонями вперёд. Это исходное положение.',
            'На выдохе выжмите обе гантели вверх над верхом груди почти до полного выпрямления рук, не стуча ими друг о друга.',
            'На вдохе медленно опустите их к бокам груди; опускание должно занимать примерно вдвое больше времени, чем жим.',
            'Выполните рекомендованное количество повторений, затем опустите гантели на бёдра и только потом вставайте.',
        ],
    },
}
