# -*- coding: utf-8 -*-
"""Hips and legs. 47 rows: 10 merge into the existing catalog, 37 authored here.

Two replaced matches: `band_hip_adduction` matched a text that raises the leg
OUT to the side, which is abduction and the opposite movement; and
`dumbbell_goblet_squat` matched a squat holding a dumbbell in each hand at the
sides, which is the one thing a goblet squat is not.

`weighted_sissy_squat` takes `weight_plates` from its matched text, which says
the free hand holds a plate on the chest.
"""
_LEG = ['quads', 'glutes', 'hamstrings']

ENTRIES = {
    'band_hip_abduction': {
        't': 'Band Hip Abduction',
        'eq': 'resistance_bands', 'm': ['glutes'],
        'en': [
            'Anchor a band around a solid post at ankle height and loop the free end around the ankle furthest from the post.',
            'Stand side-on with the feet together, holding the post for balance and the band already under tension. This is the starting position.',
            'Keeping the knee straight and the torso upright, raise the working leg out to the side as far as it will go, breathing out.',
            'Return the leg slowly to the middle against the band as you breathe in, and repeat for the prescribed amount of repetitions before changing sides.',
        ],
        'ru': 'Отведение ноги в сторону с лентой',
        'rs': [
            'Закрепите ленту на устойчивой опоре на высоте лодыжки и наденьте свободный конец на дальнюю от опоры лодыжку.',
            'Встаньте боком, стопы вместе; держитесь за опору для равновесия, лента уже натянута. Это исходное положение.',
            'На выдохе отведите рабочую ногу в сторону настолько, насколько возможно, не сгибая колено и не наклоняя корпус.',
            'На вдохе медленно верните ногу к средней линии, сопротивляясь ленте, и выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'band_hip_adduction': {
        't': 'Band Hip Adduction',
        'eq': 'resistance_bands', 'm': ['adductors'],
        'en': [
            'Anchor a band around a solid post at ankle height and loop the free end around the ankle nearest the post.',
            'Stand side-on and step away until the band pulls that leg out to the side, holding the post for balance. This is the starting position.',
            'Keeping the knee straight, pull the working leg in across the midline of your body against the band as you breathe out.',
            'Let the band draw the leg slowly back out to the side as you breathe in, and repeat for the prescribed amount of repetitions before changing sides.',
        ],
        'ru': 'Приведение ноги с лентой',
        'rs': [
            'Закрепите ленту на устойчивой опоре на высоте лодыжки и наденьте свободный конец на ближнюю к опоре лодыжку.',
            'Встаньте боком и отойдите так, чтобы лента тянула эту ногу в сторону; держитесь за опору для равновесия. Это исходное положение.',
            'На выдохе, не сгибая колено, приведите рабочую ногу внутрь через среднюю линию тела, преодолевая сопротивление ленты.',
            'На вдохе медленно позвольте ленте вернуть ногу в сторону и выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'band_leg_curl': {
        't': 'Band Lying Leg Curl',
        'eq': 'resistance_bands', 'm': ['hamstrings'],
        'en': [
            'Anchor a band low behind you and lie face down on a mat with the free end looped around one ankle.',
            'Move forward until the band is under tension with the leg straight. This is the starting position.',
            'Bend the knee to bring the heel toward your glutes as you breathe out, keeping the hip flat on the mat.',
            'Straighten the leg slowly against the band as you breathe in, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Сгибание ноги лёжа с лентой',
        'rs': [
            'Закрепите ленту низко за собой и лягте на коврик лицом вниз, накинув свободный конец на лодыжку.',
            'Продвиньтесь вперёд, чтобы лента натянулась при прямой ноге. Это исходное положение.',
            'На выдохе согните колено, приближая пятку к ягодице и не отрывая таз от коврика.',
            'На вдохе медленно выпрямите ногу, сопротивляясь ленте, и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'band_seated_leg_extension': {
        't': 'Band Seated Leg Extension',
        'eq': 'resistance_bands', 'm': ['quads'],
        'en': [
            'Sit on a bench or chair and anchor a band low behind you, looping the free end around one ankle.',
            'Sit tall with the knee bent to a right angle and the band under tension. This is the starting position.',
            'Straighten the knee until the leg is horizontal as you breathe out, and squeeze the front of the thigh for a second.',
            'Bend the knee slowly back to the right angle as you breathe in, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Разгибание ноги сидя с лентой',
        'rs': [
            'Сядьте на скамью или стул и закрепите ленту низко за собой, накинув свободный конец на лодыжку.',
            'Сядьте ровно: колено согнуто под прямым углом, лента натянута. Это исходное положение.',
            'На выдохе разогните колено до горизонтали и на секунду напрягите переднюю поверхность бедра.',
            'На вдохе медленно согните колено обратно до прямого угла и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'barbell_front_chest_squat': {
        't': 'Barbell Front Squat',
        'eq': 'barbell', 'm': _LEG, 'p': ['quads'], 'd': 'intermediate',
        'min': 8,
        'ru': 'Фронтальные приседания со штангой',
        'rs': [
            'Это упражнение безопаснее выполнять в силовой раме. Установите гриф на стойках на подходящей для вашего роста высоте. Подведите руки под гриф, держа локти высоко, а плечи — чуть выше параллели с полом. Положите гриф на передние дельты и скрестите руки, надёжно удерживая его.',
            'Снимите гриф со стоек, одновременно распрямляя ноги и выпрямляя корпус.',
            'Отойдите от стоек и поставьте стопы на ширине плеч, слегка развернув носки наружу. Всё время держите голову поднятой — взгляд вниз нарушает равновесие — и сохраняйте прямую спину. Это исходное положение. (Примечание: здесь используется средняя постановка стоп, которая развивает мышцы в целом; при желании можно выбрать любую из трёх постановок из раздела о положении стоп.)',
            'Медленно опускайте гриф, сгибая колени и сохраняя прямую осанку и поднятую голову. Опускайтесь, пока угол между бедром и голенью не станет чуть меньше прямого, то есть пока бёдра не окажутся ниже параллели с полом. На этом движении делайте вдох. Подсказка: при правильном выполнении передняя часть коленей образует воображаемую вертикальную линию с носками. Если колени выходят за неё, нагрузка на коленный сустав избыточна и упражнение выполнено неверно.',
            'На выдохе поднимайте гриф, отталкиваясь от пола преимущественно серединой стопы и выпрямляя ноги, и вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'close_feet_leg_press': {
        't': 'Close-Feet Leg Press',
        'eq': 'leg_press', 'm': _LEG, 'p': ['quads'],
        'en': [
            'Sit in the leg press and place both feet on the middle of the platform with the heels almost touching each other.',
            'Press the platform up, release the safety catches and straighten the legs without locking the knees. This is the starting position.',
            'Bend the knees to lower the platform as you breathe in, until the knees are close to your chest and the lower back stays flat against the pad.',
            'Push the platform back up through the middle of your feet as you breathe out, keeping the knees tracking over the toes rather than falling inward.',
            'Repeat for the prescribed amount of repetitions, then re-engage the catches before getting out.',
        ],
        'ru': 'Жим ногами узкой постановкой стоп',
        'rs': [
            'Сядьте в тренажёр для жима ногами и поставьте обе стопы в середину платформы так, чтобы пятки почти касались друг друга.',
            'Выжмите платформу, снимите её со стопоров и выпрямите ноги, не блокируя колени. Это исходное положение.',
            'На вдохе согните колени, опуская платформу, пока колени не приблизятся к груди; поясница всё время остаётся прижатой к спинке.',
            'На выдохе выжмите платформу обратно серединой стоп, следя за тем, чтобы колени шли над носками, а не заваливались внутрь.',
            'Выполните рекомендованное количество повторений, затем верните платформу на стопоры и только потом вставайте.',
        ],
    },
    'dumbbell_bar_grip_sumo_squat': {
        't': 'Dumbbell Sumo Squat',
        'eq': 'dumbbell', 'm': ['quads', 'glutes', 'adductors'], 'p': ['quads'],
        'en': [
            'Stand with the feet well outside shoulder width and the toes turned out to about 45 degrees, holding one dumbbell by the bar with both hands between your legs.',
            'Stand tall with the chest up and the arms straight. This is the starting position.',
            'Sit down between your heels by bending the knees and pushing them out over the toes, breathing in and keeping the torso upright.',
            'Drive back up through the heels as you breathe out, squeezing the glutes and the inner thighs at the top.',
            'Repeat for the prescribed amount of repetitions, keeping the dumbbell close to the body throughout.',
        ],
        'ru': 'Приседания сумо с гантелью',
        'rs': [
            'Встаньте, широко расставив стопы и развернув носки примерно на 45 градусов; удерживайте одну гантель за гриф обеими руками между ног.',
            'Встаньте прямо, грудь развёрнута, руки выпрямлены. Это исходное положение.',
            'На вдохе опуститесь между пяток, сгибая колени и разводя их в стороны над носками; корпус остаётся вертикальным.',
            'На выдохе вернитесь вверх, отталкиваясь пятками и сжимая ягодицы и внутреннюю поверхность бёдер в верхней точке.',
            'Выполните рекомендованное количество повторений, всё время удерживая гантель близко к телу.',
        ],
    },
    'dumbbell_goblet_squat': {
        't': 'Dumbbell Goblet Squat',
        'eq': 'dumbbell', 'm': _LEG, 'p': ['quads'],
        'en': [
            'Hold a single dumbbell vertically against your chest, cupping the top head with both hands and keeping the elbows tucked in.',
            'Stand with the feet shoulder width apart, the toes turned slightly out and the chest up. This is the starting position.',
            'Squat down by pushing the hips back and bending the knees, breathing in and letting the elbows travel inside the knees at the bottom.',
            'Drive back up through the middle of the feet as you breathe out until the legs are straight.',
            'Repeat for the prescribed amount of repetitions, keeping the dumbbell against the chest so the torso stays upright.',
        ],
        'ru': 'Приседания с гантелью у груди',
        'rs': [
            'Возьмите одну гантель вертикально у груди, обхватив её верхний диск обеими руками; локти прижаты к корпусу.',
            'Поставьте стопы на ширине плеч, слегка развернув носки; грудь развёрнута. Это исходное положение.',
            'На вдохе присядьте, отводя таз назад и сгибая колени; в нижней точке локти проходят внутри коленей.',
            'На выдохе вернитесь вверх, отталкиваясь серединой стоп, до полного выпрямления ног.',
            'Выполните рекомендованное количество повторений, удерживая гантель у груди, чтобы корпус оставался вертикальным.',
        ],
    },
    'dumbbell_lunge': {
        't': 'Dumbbell Lunge',
        'eq': 'dumbbell', 'm': _LEG, 'p': ['quads'], 'min': 8,
        'ru': 'Выпады с гантелями',
        'rs': [
            'Встаньте прямо, удерживая по гантели в каждой руке вдоль тела. Это исходное положение.',
            'Сделайте шаг вперёд правой ногой примерно на 60 сантиметров от оставшейся сзади стопы и опустите корпус вниз, сохраняя вертикальное положение и равновесие. На опускании делайте вдох. Примечание: как и в других упражнениях, не выводите колено за носок — это создаёт избыточную нагрузку на коленный сустав. Следите, чтобы голень передней ноги оставалась перпендикулярной полу.',
            'На выдохе оттолкнитесь преимущественно пяткой и вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений, затем сделайте то же самое левой ногой.',
        ],
    },
    'dumbbell_lying_femoral': {
        't': 'Dumbbell Lying Leg Curl',
        'eq': 'dumbbell', 'm': ['hamstrings'],
        'en': [
            'Lie face down on a flat bench with the hips at its edge and ask a partner to place a dumbbell between your feet, or grip it with the soles.',
            'Squeeze the dumbbell between the feet and straighten the legs. This is the starting position.',
            'Bend the knees to curl the dumbbell toward your glutes as you breathe out, keeping the hips pressed into the bench.',
            'Lower the legs slowly back to straight as you breathe in, and repeat for the prescribed amount of repetitions with a light dumbbell you can hold securely.',
        ],
        'ru': 'Сгибание ног с гантелью лёжа',
        'rs': [
            'Лягте лицом вниз на горизонтальную скамью так, чтобы таз был у её края, и попросите напарника вложить гантель между стоп либо зажмите её подошвами сами.',
            'Крепко сожмите гантель стопами и выпрямите ноги. Это исходное положение.',
            'На выдохе согните колени, поднимая гантель к ягодицам и не отрывая таз от скамьи.',
            'На вдохе медленно опустите ноги до полного выпрямления и выполните рекомендованное количество повторений с лёгкой гантелью, которую вы уверенно удерживаете.',
        ],
    },
    'dumbbell_single_leg_squat': {
        't': 'Dumbbell Single-Leg Squat',
        'eq': 'dumbbell', 'm': _LEG, 'p': ['quads'], 'd': 'advanced',
        'en': [
            'Stand on one leg holding a dumbbell in each hand at your sides, with the other foot lifted slightly in front of you.',
            'Stand tall with the chest up and the standing knee soft. This is the starting position.',
            'Push the hips back and bend the standing knee, lowering as far as you can control while keeping the knee tracking over the foot and the free leg off the floor.',
            'Drive back up through the heel as you breathe out until the standing leg is straight.',
            'Repeat for the prescribed amount of repetitions, then change legs — hold a rack with one hand if balance runs out before the muscles do.',
        ],
        'ru': 'Приседания на одной ноге с гантелями',
        'rs': [
            'Встаньте на одну ногу, удерживая по гантели в каждой руке вдоль тела; вторую стопу слегка вынесите вперёд.',
            'Держите корпус прямо, грудь развёрнута, опорное колено мягкое. Это исходное положение.',
            'Отведите таз назад и согните опорное колено, опускаясь настолько, насколько удаётся контролировать движение; колено идёт над стопой, свободная нога не касается пола.',
            'На выдохе вернитесь вверх, отталкиваясь пяткой, до полного выпрямления опорной ноги.',
            'Выполните рекомендованное количество повторений и смените ногу; если равновесие заканчивается раньше мышц, придерживайтесь одной рукой за стойку.',
        ],
    },
    'dumbbell_squat': {
        't': 'Dumbbell Squat',
        'eq': 'dumbbell', 'm': _LEG, 'p': ['quads'], 'min': 8,
        'ru': 'Приседания с гантелями в опущенных руках',
        'rs': [
            'Встаньте прямо, держа по гантели в каждой руке (ладони обращены к бёдрам).',
            'Поставьте стопы на ширине плеч, слегка развернув носки наружу. Всё время держите голову поднятой — взгляд вниз нарушает равновесие — и сохраняйте прямую спину. Это исходное положение. Примечание: здесь используется средняя постановка стоп, которая развивает мышцы в целом; при желании можно выбрать любую из трёх постановок из раздела о положении стоп.',
            'Медленно опускайте корпус, сгибая колени и сохраняя прямую осанку и поднятую голову. Опускайтесь, пока бёдра не станут параллельны полу. Подсказка: при правильном выполнении передняя часть коленей образует воображаемую вертикальную линию с носками. Если колени выходят за неё, нагрузка на коленный сустав избыточна и упражнение выполнено неверно.',
            'На выдохе поднимайте корпус, отталкиваясь от пола преимущественно пяткой и выпрямляя ноги, и вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_horizontal_leg_press': {
        't': 'Machine Horizontal Leg Press',
        'eq': 'leg_press', 'm': _LEG, 'p': ['quads'],
        'en': [
            'Set the seat of the horizontal leg press so that your knees are bent to roughly a right angle when your feet are on the platform.',
            'Sit with your back flat against the pad, feet shoulder width apart in the middle of the platform. This is the starting position.',
            'Press the platform away until the legs are almost straight as you breathe out, without locking the knees.',
            'Let the platform come back slowly as you breathe in, stopping before the lower back rounds off the pad.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Горизонтальный жим ногами в тренажёре',
        'rs': [
            'Отрегулируйте сиденье горизонтального тренажёра так, чтобы при стопах на платформе колени были согнуты примерно под прямым углом.',
            'Сядьте, прижав спину к спинке; стопы на ширине плеч в середине платформы. Это исходное положение.',
            'На выдохе выжмите платформу почти до полного выпрямления ног, не блокируя колени.',
            'На вдохе медленно позвольте платформе вернуться, остановившись до того, как поясница начнёт скругляться и отрываться от спинки.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_kneeling_leg_curl': {
        't': 'Machine Kneeling Leg Curl',
        'eq': 'leg_curl', 'm': ['hamstrings'],
        'en': [
            'Kneel in the machine with one knee on the pad, the other foot on the platform and the roller against the back of the working ankle.',
            'Rest your forearms on the support and keep the back flat with the working leg straight. This is the starting position.',
            'Curl the heel toward your glutes as you breathe out, keeping the hip pressed against the pad, and hold the squeeze for a second.',
            'Lower the roller slowly back to the straight position as you breathe in, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Сгибание ноги в тренажёре стоя на колене',
        'rs': [
            'Встаньте в тренажёр: одно колено на упоре, вторая стопа на платформе, валик — под задней поверхностью рабочей лодыжки.',
            'Положите предплечья на опору, спина прямая, рабочая нога выпрямлена. Это исходное положение.',
            'На выдохе согните ногу, приближая пятку к ягодице и прижимая таз к упору, и задержитесь в сокращении на секунду.',
            'На вдохе медленно верните валик в исходное положение и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'lever_seated_hip_abduction': {
        't': 'Machine Seated Hip Abduction',
        'eq': 'hip_abductor_adductor', 'm': ['glutes'],
        'en': [
            'Sit in the abduction machine with the outside of your thighs against the pads and your back flat on the backrest.',
            'Take the handles and start with the knees together or as close as the machine allows. This is the starting position.',
            'Push the knees apart as far as they will comfortably go as you breathe out, and hold the outer hips squeezed for a second.',
            'Bring the knees back together slowly against the resistance as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Разведение ног в тренажёре сидя',
        'rs': [
            'Сядьте в тренажёр для разведения ног, прижав внешнюю поверхность бёдер к упорам, а спину — к спинке.',
            'Возьмитесь за рукояти; начните с сомкнутых коленей или настолько близко, насколько позволяет тренажёр. Это исходное положение.',
            'На выдохе разведите колени настолько широко, насколько это комфортно, и на секунду задержитесь, сжимая ягодичные мышцы.',
            'На вдохе медленно сведите колени, сопротивляясь нагрузке, и выполните рекомендованное количество повторений.',
        ],
    },
    'lever_seated_hip_adduction': {
        't': 'Machine Seated Hip Adduction',
        'eq': 'hip_abductor_adductor', 'm': ['adductors'],
        'en': [
            'Sit in the adduction machine with the inside of your thighs against the pads and your back flat on the backrest.',
            'Take the handles and let the machine open your knees only as wide as is comfortable. This is the starting position.',
            'Squeeze the knees together as you breathe out, and hold the inner thighs contracted for a second.',
            'Let the knees open slowly back to the stretched position as you breathe in, never letting the weight pull you wider than the start, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Сведение ног в тренажёре сидя',
        'rs': [
            'Сядьте в тренажёр для сведения ног, прижав внутреннюю поверхность бёдер к упорам, а спину — к спинке.',
            'Возьмитесь за рукояти и разведите колени лишь настолько, насколько это комфортно. Это исходное положение.',
            'На выдохе сведите колени и на секунду задержитесь, напрягая внутреннюю поверхность бёдер.',
            'На вдохе медленно разведите колени в растянутое положение, не позволяя весу развести их шире исходного, и выполните рекомендованное количество повторений.',
        ],
    },
    'lever_standing_hip_extension': {
        't': 'Machine Standing Hip Extension',
        'eq': 'glute_kickback_machine', 'm': ['glutes', 'hamstrings'],
        'p': ['glutes'],
        'en': [
            'Stand in the machine facing the pad and place one foot on the platform, with the working foot or shin against the lever.',
            'Hold the handles, stand tall and brace the core so the lower back does not arch. This is the starting position.',
            'Push the working leg straight back and slightly up as you breathe out, squeezing the glute at the end of the range.',
            'Return the leg slowly to the start as you breathe in, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Отведение ноги назад в тренажёре',
        'rs': [
            'Встаньте в тренажёр лицом к упору, поставив одну стопу на платформу; рабочая стопа или голень упирается в рычаг.',
            'Возьмитесь за рукояти, встаньте прямо и напрягите живот, чтобы поясница не прогибалась. Это исходное положение.',
            'На выдохе отведите рабочую ногу прямо назад и слегка вверх, сжимая ягодичную мышцу в конце амплитуды.',
            'На вдохе медленно верните ногу в исходное положение и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'lever_standing_rear_kick': {
        't': 'Machine Standing Rear Kick',
        'eq': 'glute_kickback_machine', 'm': ['glutes', 'hamstrings'],
        'p': ['glutes'],
        'en': [
            'Set the machine so the roller sits behind the working thigh just above the knee, and stand facing the frame holding the handles.',
            'Stand tall on the supporting leg with a slight bend in that knee and the hips square. This is the starting position.',
            'Drive the working knee back and up against the roller as you breathe out, and hold the glute contracted for a second.',
            'Let the roller come forward slowly as you breathe in without letting the lower back arch, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Мах ногой назад в тренажёре',
        'rs': [
            'Отрегулируйте тренажёр так, чтобы валик оказался под задней поверхностью рабочего бедра чуть выше колена, и встаньте лицом к раме, взявшись за рукояти.',
            'Стойте прямо на опорной ноге, слегка согнув её колено; таз развёрнут ровно. Это исходное положение.',
            'На выдохе отведите рабочее колено назад и вверх, продавливая валик, и на секунду задержитесь, сжимая ягодичную мышцу.',
            'На вдохе медленно позвольте валику вернуться вперёд, не прогибая поясницу, и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'rear_decline_bridge': {
        't': 'Rear Decline Bridge',
        'eq': None, 'm': ['glutes', 'hamstrings', 'lower_back'],
        'p': ['glutes'], 'd': 'intermediate',
        'en': [
            'Sit on the floor with the legs straight and the heels on a bench or box, hands on the floor behind your hips.',
            'Press the shoulders down and away from your ears and squeeze the glutes. This is the starting position.',
            'Lift the hips until the body forms a straight line from the shoulders to the heels, breathing out.',
            'Hold the top for two seconds, then lower the hips slowly to the floor as you breathe in.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Обратный мостик с опорой ног',
        'rs': [
            'Сядьте на пол, выпрямив ноги и положив пятки на скамью или бокс; ладони поставьте на пол за тазом.',
            'Опустите плечи, отдаляя их от ушей, и напрягите ягодицы. Это исходное положение.',
            'На выдохе поднимите таз так, чтобы тело вытянулось в прямую линию от плеч до пяток.',
            'Задержитесь в верхней точке на две секунды, затем на вдохе медленно опустите таз на пол.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'sled_45_degree_leg_wide_press': {
        't': 'Sled 45-Degree Wide-Stance Leg Press',
        'eq': 'leg_press', 'm': ['quads', 'glutes', 'adductors'],
        'p': ['quads'], 'min': 8,
        'en': [
            'Sit in the 45-degree leg press and place your feet high and wide on the platform with the toes turned slightly out.',
            'Press the platform up, release the safety catches and straighten the legs without locking the knees. This is the starting position.',
            'Lower the platform slowly as you breathe in, letting the knees travel out over the toes until the thighs approach your chest.',
            'Press back up through the heels as you breathe out, keeping the lower back flat against the pad the whole way.',
            'Repeat for the prescribed amount of repetitions, then re-engage the catches before getting out.',
        ],
        'ru': 'Жим ногами в наклонном тренажёре широкой постановкой',
        'rs': [
            'Сядьте в наклонный тренажёр для жима ногами и поставьте стопы высоко и широко на платформе, слегка развернув носки наружу.',
            'Выжмите платформу, снимите её со стопоров и выпрямите ноги, не блокируя колени. Это исходное положение.',
            'На вдохе медленно опускайте платформу, разводя колени над носками, пока бёдра не приблизятся к груди.',
            'На выдохе выжмите платформу обратно пятками, всё время удерживая поясницу прижатой к спинке.',
            'Выполните рекомендованное количество повторений, затем верните платформу на стопоры и только потом вставайте.',
        ],
    },
    'smith_chair_squat': {
        't': 'Smith Machine Chair Squat',
        'eq': 'smith_machine', 'm': _LEG, 'p': ['quads'], 'min': 8,
        'ru': 'Приседания в машине Смита с выносом стоп вперёд',
        'rs': [
            'Установите гриф на высоте, подходящей вашему росту. Нагрузив его, подойдите под гриф и положите его на верх спины.',
            'Возьмитесь за гриф ладонями вперёд, снимите его со стопоров, выпрямив ноги.',
            'Вынесите стопы примерно на 45 сантиметров вперёд относительно грифа. Поставьте их на ширине плеч, слегка развернув носки наружу. Смотрите прямо перед собой и сохраняйте нейтральный или слегка прогнутый позвоночник. Это исходное положение.',
            'Медленно опускайте гриф, сгибая колени и сохраняя прямую осанку и поднятую голову. Опускайтесь, пока угол между бедром и голенью не станет меньше прямого.',
            'На выдохе поднимайте гриф, отталкиваясь пятками и разгибая колени, и вернитесь в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'stretching_adductor_stretch': {
        't': 'Adductor Stretch',
        'eq': None, 'm': ['adductors'], 'stretch': True,
        'en': [
            'Stand with the feet much wider than shoulder width and the toes pointing forward.',
            'Place your hands on the thigh of one leg for support. This is the starting position.',
            'Shift your weight onto that leg by bending its knee and pushing the hips back, keeping the other leg straight with the foot flat.',
            'Hold for 20 to 30 seconds where the inner thigh of the straight leg stretches, then change sides.',
        ],
        'ru': 'Растяжка приводящих мышц бедра',
        'rs': [
            'Встаньте, расставив стопы значительно шире плеч, носки направлены вперёд.',
            'Положите ладони на бедро одной ноги для опоры. Это исходное положение.',
            'Перенесите вес на эту ногу, сгибая её колено и отводя таз назад; вторая нога остаётся прямой, стопа — прижатой к полу.',
            'Удерживайте 20–30 секунд там, где растягивается внутренняя поверхность прямой ноги, затем смените сторону.',
        ],
    },
    'stretching_all_fours_squad_stretch': {
        't': 'All-Fours Quad Stretch',
        'eq': None, 'm': ['quads'], 'stretch': True,
        'en': [
            'Kneel on all fours with the hands under the shoulders and the knees under the hips.',
            'Shift your weight onto one arm and the opposite knee. This is the starting position.',
            'Reach back with the free hand, take the ankle of the free leg and draw the heel toward your glutes, keeping the hips level and the lower back flat.',
            'Hold for 20 to 30 seconds, then release and change sides.',
        ],
        'ru': 'Растяжка квадрицепса стоя на четвереньках',
        'rs': [
            'Встаньте на четвереньки: ладони под плечами, колени под тазом.',
            'Перенесите вес на одну руку и противоположное колено. Это исходное положение.',
            'Свободной рукой возьмитесь за лодыжку свободной ноги и притяните пятку к ягодице, удерживая таз ровно, а поясницу — без прогиба.',
            'Удерживайте 20–30 секунд, затем отпустите и смените сторону.',
        ],
    },
    'stretching_boat_stretch': {
        't': 'Boat Stretch',
        'eq': None, 'm': ['core', 'hamstrings'], 'p': ['core'], 'stretch': True,
        'd': 'intermediate',
        'en': [
            'Sit on a mat with the knees bent, the feet flat and the hands holding behind your thighs.',
            'Lean back slightly and lift the chest so the spine stays long. This is the starting position.',
            'Lift both feet off the floor until the shins are parallel with it, balancing on the sitting bones, then straighten the legs if you can keep the back flat.',
            'Hold for 15 to 30 seconds, breathing steadily, then lower the feet and release.',
        ],
        'ru': 'Поза лодки',
        'rs': [
            'Сядьте на коврик, согнув колени и поставив стопы на пол; возьмитесь руками за задние поверхности бёдер.',
            'Слегка отклонитесь назад и приподнимите грудь, вытягивая позвоночник. Это исходное положение.',
            'Оторвите обе стопы от пола так, чтобы голени были параллельны ему, балансируя на седалищных костях; затем выпрямите ноги, если удаётся сохранить спину ровной.',
            'Удерживайте 15–30 секунд, дыша ровно, затем опустите стопы.',
        ],
    },
    'stretching_ceiling_look_stretch': {
        't': 'Ceiling Look Stretch',
        'eq': None, 'm': ['quads', 'chest', 'core'], 'p': ['quads'],
        'stretch': True,
        'en': [
            'Kneel on one knee with the other foot flat on the floor in front of you, both knees bent to about a right angle.',
            'Tuck the pelvis under so the lower back flattens. This is the starting position.',
            'Raise the arm on the kneeling side overhead, look up toward the ceiling and press the hip of that side forward.',
            'Hold for 20 to 30 seconds where the front of the hip and the thigh stretch, then change sides.',
        ],
        'ru': 'Растяжка сгибателей бедра со взглядом вверх',
        'rs': [
            'Встаньте на одно колено, вторую стопу поставьте на пол перед собой; оба колена согнуты примерно под прямым углом.',
            'Подкрутите таз так, чтобы поясница выпрямилась. Это исходное положение.',
            'Поднимите руку со стороны опорного колена вверх, посмотрите в потолок и подайте таз этой стороны вперёд.',
            'Удерживайте 20–30 секунд там, где растягиваются передняя поверхность бедра и таза, затем смените сторону.',
        ],
    },
    'stretching_crossover_kneeling_hip_flexor_stretch': {
        't': 'Crossover Kneeling Hip Flexor Stretch',
        'eq': None, 'm': ['quads', 'core'], 'p': ['quads'], 'stretch': True,
        'en': [
            'Kneel on one knee with the other foot flat on the floor in front of you.',
            'Tuck the pelvis under and press the back hip forward until you feel the front of it lengthen. This is the starting position.',
            'Raise the arm on the kneeling side overhead and side-bend away from that knee, adding a small rotation toward the front leg.',
            'Hold for 20 to 30 seconds, breathing steadily, then change sides.',
        ],
        'ru': 'Растяжка сгибателей бедра с наклоном в сторону',
        'rs': [
            'Встаньте на одно колено, вторую стопу поставьте на пол перед собой.',
            'Подкрутите таз и подайте заднее бедро вперёд, пока его передняя поверхность не удлинится. Это исходное положение.',
            'Поднимите руку со стороны опорного колена вверх и наклонитесь в противоположную сторону, добавив небольшой разворот к передней ноге.',
            'Удерживайте 20–30 секунд, дыша ровно, затем смените сторону.',
        ],
    },
    'stretching_hamstring_stretch': {
        't': 'Hamstring Stretch',
        'eq': None, 'm': ['hamstrings', 'calves'], 'p': ['hamstrings'],
        'stretch': True,
        'ru': 'Растяжка задней поверхности бедра',
        'rs': [
            'Лягте на спину и поднимите одну ногу вверх так, чтобы в тазобедренном суставе был прямой угол. Вторая нога остаётся лежать на полу.',
            'Накиньте ремень, ленту или верёвку на подушечку стопы. Это исходное положение.',
            'Потяните ремень, создавая натяжение в икре и задней поверхности бедра. Удерживайте 10–30 секунд и повторите с другой ногой.',
        ],
    },
    'stretching_hip_circles_stretch': {
        't': 'Hip Circles',
        'eq': None, 'm': ['glutes', 'core'], 'p': ['glutes'], 'stretch': True,
        'en': [
            'Stand with the feet shoulder width apart and place your hands on your hips.',
            'Keep the feet flat and the knees soft. This is the starting position.',
            'Circle the hips slowly and widely, letting the pelvis travel forward, to the side, back and around through its full range.',
            'Complete 10 circles in one direction, then 10 in the other.',
        ],
        'ru': 'Круговые движения тазом',
        'rs': [
            'Встаньте, стопы на ширине плеч, ладони положите на пояс.',
            'Стопы плотно стоят на полу, колени мягкие. Это исходное положение.',
            'Медленно и широко описывайте тазом круги, проводя его вперёд, в сторону, назад и по всей доступной амплитуде.',
            'Сделайте 10 кругов в одну сторону и 10 в другую.',
        ],
    },
    'stretching_hip_extension_stretch': {
        't': 'Hip Extension Stretch',
        'eq': None, 'm': ['glutes', 'lower_back'], 'p': ['glutes'],
        'stretch': True,
        'en': [
            'Lie on your back with both knees bent and the feet flat on the floor.',
            'Draw one knee up toward your chest and hold behind the thigh with both hands. This is the starting position.',
            'Pull that knee gently closer while pressing the other leg down into the floor, so the hip and glute lengthen.',
            'Hold for 20 to 30 seconds, then release and change legs.',
        ],
        'ru': 'Растяжка ягодичных мышц лёжа',
        'rs': [
            'Лягте на спину, согнув оба колена и поставив стопы на пол.',
            'Подтяните одно колено к груди и обхватите бедро обеими руками сзади. Это исходное положение.',
            'Мягко притяните колено ближе, одновременно прижимая вторую ногу к полу, чтобы растянулись ягодичная мышца и задняя поверхность таза.',
            'Удерживайте 20–30 секунд, затем отпустите и смените ногу.',
        ],
    },
    'stretching_hip_flexor_stretch_rear_foot_elevated': {
        't': 'Hip Flexor Stretch - Rear Foot Elevated',
        'eq': None, 'm': ['quads', 'core'], 'p': ['quads'], 'stretch': True,
        'en': [
            'Kneel on one knee facing away from a bench and rest the top of the rear foot on it, with the front foot flat on the floor.',
            'Tuck the pelvis under so the lower back flattens and lift the chest. This is the starting position.',
            'Press the rear hip forward until the front of that thigh and hip stretch, without letting the lower back arch.',
            'Hold for 20 to 30 seconds, then step out carefully and change sides.',
        ],
        'ru': 'Растяжка сгибателей бедра с задней ногой на возвышении',
        'rs': [
            'Встаньте на одно колено спиной к скамье и положите на неё подъём задней стопы; передняя стопа стоит на полу.',
            'Подкрутите таз так, чтобы поясница выпрямилась, и приподнимите грудь. Это исходное положение.',
            'Подайте таз задней ноги вперёд, пока не растянутся передняя поверхность бедра и таза, не допуская прогиба в пояснице.',
            'Удерживайте 20–30 секунд, затем аккуратно выйдите из положения и смените сторону.',
        ],
    },
    'stretching_hip_flexor_and_quad_stretch': {
        't': 'Hip Flexor and Quad Stretch',
        'eq': None, 'm': ['quads'], 'stretch': True,
        'ru': 'Растяжка сгибателей бедра и квадрицепса лёжа',
        'rs': [
            'Лягте на пол лицом вниз, накинув верёвку, ремень или ленту на одну стопу.',
            'Согните колено и разогните бедро растягиваемой ноги, подтягивая ремень обеими руками. Колено и бедро должны оторваться от пола, создавая натяжение в сгибателях бедра и квадрицепсе. Удерживайте 10–20 секунд и повторите на другой ноге.',
        ],
    },
    'stretching_knee_raise': {
        't': 'Standing Knee Raise',
        'eq': None, 'm': ['glutes', 'core'], 'p': ['glutes'], 'stretch': True,
        'en': [
            'Stand tall with the feet hip width apart, holding a wall or a rack if you need the balance.',
            'Shift your weight onto one leg and keep that knee soft. This is the starting position.',
            'Draw the other knee up toward your chest and hold it there with both hands, keeping the standing leg straight and the torso upright.',
            'Hold for 15 to 20 seconds, then lower the leg and change sides.',
        ],
        'ru': 'Подтягивание колена к груди стоя',
        'rs': [
            'Встаньте прямо, стопы на ширине таза; при необходимости придерживайтесь за стену или стойку.',
            'Перенесите вес на одну ногу, оставив её колено мягким. Это исходное положение.',
            'Подтяните второе колено к груди и удерживайте его обеими руками, сохраняя опорную ногу прямой, а корпус — вертикальным.',
            'Удерживайте 15–20 секунд, затем опустите ногу и смените сторону.',
        ],
    },
    'stretching_quadriceps_lying_stretch': {
        't': 'Lying Quadriceps Stretch',
        'eq': None, 'm': ['quads'], 'stretch': True,
        'en': [
            'Lie on one side with the bottom arm supporting your head and both legs stacked and straight.',
            'Bend the top knee and take that ankle with the free hand. This is the starting position.',
            'Draw the heel toward your glutes and the knee slightly back, keeping the hips stacked and the lower back flat.',
            'Hold for 20 to 30 seconds, then release and turn over to the other side.',
        ],
        'ru': 'Растяжка квадрицепса лёжа на боку',
        'rs': [
            'Лягте на бок, подложив нижнюю руку под голову; обе ноги выпрямлены и лежат одна на другой.',
            'Согните верхнее колено и возьмитесь свободной рукой за лодыжку. Это исходное положение.',
            'Притяните пятку к ягодице и слегка отведите колено назад, удерживая таз ровно, а поясницу — без прогиба.',
            'Удерживайте 20–30 секунд, затем отпустите и перевернитесь на другой бок.',
        ],
    },
    'stretching_quadriceps_stretch': {
        't': 'Standing Quadriceps Stretch',
        'eq': None, 'm': ['quads'], 'stretch': True,
        'en': [
            'Stand tall with the feet together, holding a wall or a rack with one hand for balance.',
            'Shift your weight onto one leg. This is the starting position.',
            'Bend the other knee, take that ankle behind you with the free hand and draw the heel toward your glutes, keeping the knees side by side and the pelvis tucked.',
            'Hold for 20 to 30 seconds, then release and change legs.',
        ],
        'ru': 'Растяжка квадрицепса стоя',
        'rs': [
            'Встаньте прямо, стопы вместе; одной рукой держитесь за стену или стойку для равновесия.',
            'Перенесите вес на одну ногу. Это исходное положение.',
            'Согните вторую ногу, возьмитесь свободной рукой за лодыжку сзади и притяните пятку к ягодице, удерживая колени рядом и подкрутив таз.',
            'Удерживайте 20–30 секунд, затем отпустите и смените ногу.',
        ],
    },
    'stretching_runners_stretch': {
        't': 'Runner\'s Stretch',
        'eq': None, 'm': ['hamstrings', 'calves', 'quads'], 'p': ['hamstrings'],
        'stretch': True,
        'en': [
            'Step one foot well forward into a long lunge and place both hands on the floor either side of that foot.',
            'Keep the back leg straight with the heel pressing back. This is the starting position.',
            'Sink the hips down and forward to stretch the front of the rear hip, then push the hips back and straighten the front leg to move the stretch into its hamstring.',
            'Alternate between the two positions for 20 to 30 seconds, then change legs.',
        ],
        'ru': 'Растяжка бегуна',
        'rs': [
            'Сделайте длинный выпад вперёд одной ногой и поставьте обе ладони на пол по сторонам от передней стопы.',
            'Задняя нога остаётся прямой, пятка тянется назад. Это исходное положение.',
            'Опустите таз вниз и вперёд, растягивая переднюю поверхность заднего бедра, затем отведите таз назад и выпрямите переднюю ногу, переводя растяжение на её заднюю поверхность.',
            'Чередуйте два положения 20–30 секунд, затем смените ногу.',
        ],
    },
    'weighted_sissy_squat': {
        't': 'Weighted Sissy Squat',
        'eq': 'weight_plates', 'm': ['quads'], 'd': 'advanced',
        'ru': 'Сисси-приседания с блином',
        'rs': [
            'Встаньте прямо, стопы на ширине плеч, носки приподняты; одной рукой держитесь за стойку, а другой прижмите блин к груди. Это исходное положение.',
            'Удерживаясь одной рукой, согните колени и медленно опускайте корпус к полу, выводя таз и колени вперёд. На опускании делайте вдох и остановитесь, когда между бедром и голенью останется угол чуть больше прямого. Задержитесь в растянутом положении на секунду.',
            'После секундной паузы усилием мышц бедра поднимите корпус обратно в исходное положение. На подъёме делайте выдох.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'band_bent_over_hip_extension': {
        't': 'Band Bent-Over Hip Extension',
        'eq': 'resistance_bands', 'm': ['glutes', 'hamstrings'], 'p': ['glutes'],
        'en': [
            'Secure one end of a band low on a post and loop the other around one ankle, then face the post and hold it with both hands.',
            'Hinge forward from the hips until your torso is at about 45 degrees, back flat and the working leg straight. This is the starting position.',
            'Sweep the resisted leg straight back and up as far as it will go without the lower back arching, breathing out and squeezing the glute.',
            'Return the leg slowly to the start against the band as you breathe in, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Отведение ноги назад с лентой в наклоне',
        'rs': [
            'Закрепите один конец ленты низко на опоре, а другой наденьте на лодыжку; встаньте лицом к опоре и возьмитесь за неё обеими руками.',
            'Наклонитесь вперёд от тазобедренных суставов примерно до 45 градусов; спина прямая, рабочая нога выпрямлена. Это исходное положение.',
            'На выдохе отведите ногу с лентой прямо назад и вверх настолько, насколько получается без прогиба в пояснице, и сожмите ягодицу.',
            'На вдохе медленно верните ногу в исходное положение, сопротивляясь ленте, и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
}
