# -*- coding: utf-8 -*-
"""Mix (the women-only folder: floor work, Pilates, stability ball). 27 rows:
4 merge into the existing catalog, 23 authored here.

Two replaced matches: `ball_sit_up_on_stability_ball` matched a FLOOR sit-up
with the feet anchored, and `side_bend_on_stability_ball` matched a BARBELL
side bend performed standing. Neither has a ball in it.

Titles here are deliberately spelled out ("on an Exercise Ball") because the
same movement exists on the floor elsewhere in the catalog and the two must not
collide -- exact-duplicate titles are a shipped defect (registry_test.dart).
The "(female)" suffix is a vendor artefact of the drop and is dropped.
"""
_C = ['core']

ENTRIES = {
    'ball_sit_up_on_stability_ball': {
        't': 'Sit-Up on a Stability Ball',
        'eq': None, 'm': _C,
        'en': [
            'Sit on a stability ball and walk the feet forward until the ball supports your lower back, knees bent to a right angle and feet flat.',
            'Place your hands lightly behind your head with the elbows wide. This is the starting position.',
            'Curl the torso up off the ball as you breathe out, lifting the ribs toward the hips.',
            'Lower back over the ball slowly as you breathe in, letting the abdominals lengthen at the bottom.',
            'Repeat for the prescribed amount of repetitions, keeping the ball still throughout.',
        ],
        'ru': 'Подъёмы корпуса на фитболе',
        'rs': [
            'Сядьте на фитбол и прошагайте стопами вперёд, пока мяч не окажется под поясницей; колени согнуты под прямым углом, стопы стоят на полу.',
            'Положите ладони за голову без нажима, локти разведены. Это исходное положение.',
            'На выдохе поднимите корпус с мяча, направляя рёбра к тазу.',
            'На вдохе медленно опуститесь назад через мяч, позволяя мышцам живота удлиниться в нижней точке.',
            'Выполните рекомендованное количество повторений, удерживая мяч неподвижным.',
        ],
    },
    'bent_knee_lying_twist_on_stability_ball': {
        't': 'Bent Knee Lying Twist on a Stability Ball',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the arms out to the sides in a T and rest both calves on a stability ball, knees bent to a right angle.',
            'Press both shoulder blades into the floor and squeeze the ball lightly between your shins. This is the starting position.',
            'Roll the ball and the knees together to one side as far as you can go without a shoulder leaving the floor, breathing out.',
            'Bring them back to the middle using the side of your waist as you breathe in, then repeat to the other side.',
            'Keep alternating for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания лёжа с фитболом под ногами',
        'rs': [
            'Лягте на спину, разведите руки в стороны буквой «Т» и положите обе голени на фитбол; колени согнуты под прямым углом.',
            'Прижмите обе лопатки к полу и слегка сожмите мяч голенями. Это исходное положение.',
            'На выдохе уведите мяч вместе с коленями в одну сторону настолько, насколько это возможно, не отрывая плечи от пола.',
            'На вдохе вернитесь в середину усилием боковых мышц живота, затем повторите в другую сторону.',
            'Чередуйте стороны нужное количество повторений.',
        ],
    },
    'chest_lift_with_rotation': {
        't': 'Chest Lift with Rotation',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the knees bent, the feet flat on the floor and the hands lightly behind your head.',
            'Draw the navel toward the spine and curl the head and shoulders off the mat. This is the starting position.',
            'Rotate the ribcage to one side as you breathe out, reaching that shoulder toward the opposite knee without pulling on your neck.',
            'Return to the centre, still curled up, as you breathe in, then rotate to the other side.',
            'Keep alternating for the prescribed amount of repetitions, then lower the head last.',
        ],
        'ru': 'Подъём грудного отдела с поворотом',
        'rs': [
            'Лягте на спину, согните колени, поставьте стопы на пол и положите ладони за голову без нажима.',
            'Подтяните живот к позвоночнику и оторвите голову и плечи от коврика. Это исходное положение.',
            'На выдохе разверните грудную клетку в одну сторону, направляя плечо к противоположному колену и не подтягивая себя за шею.',
            'На вдохе вернитесь в центр, не опуская голову, затем разверните корпус в другую сторону.',
            'Чередуйте стороны нужное количество повторений и только в конце опустите голову.',
        ],
    },
    'corkscrew_pilates': {
        't': 'Pilates Corkscrew',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie on your back with the arms long by your sides, palms down, and both legs extended toward the ceiling with the inner thighs pressed together.',
            'Anchor the shoulders and press the lower back into the mat. This is the starting position.',
            'Circle both legs to one side, down toward the floor as far as your back can stay flat, then across and back up to vertical.',
            'Repeat the circle in the other direction, so the legs draw a corkscrew above you.',
            'Alternate directions for the prescribed amount of repetitions, keeping the circles small enough that the hips never lift.',
        ],
        'ru': 'Пилатес «штопор»',
        'rs': [
            'Лягте на спину, руки вытянуты вдоль тела ладонями вниз, обе ноги подняты к потолку и сомкнуты внутренними поверхностями бёдер.',
            'Зафиксируйте плечи и прижмите поясницу к коврику. Это исходное положение.',
            'Опишите ногами круг в одну сторону: вниз к полу настолько, насколько поясница остаётся прижатой, затем поперёк и обратно вверх.',
            'Повторите круг в другую сторону, чтобы ноги вычертили над вами спираль.',
            'Чередуйте направления нужное количество повторений, делая круги такими, чтобы таз ни разу не отрывался от пола.',
        ],
    },
    'crunch_leg_raise': {
        't': 'Crunch with Leg Raise',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the hands lightly behind your head and the knees bent, feet off the floor.',
            'Press the lower back down and curl the head and shoulders up slightly. This is the starting position.',
            'Crunch the ribs toward the hips while at the same time drawing the knees toward the chest, so both ends of the body meet.',
            'Extend the legs away and lower the shoulders slightly as you breathe in, without letting the feet touch the floor.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания с подъёмом ног',
        'rs': [
            'Лягте на спину, положите ладони за голову без нажима, колени согнуты, стопы оторваны от пола.',
            'Прижмите поясницу и слегка приподнимите голову и плечи. Это исходное положение.',
            'Скрутите рёбра к тазу, одновременно подтягивая колени к груди, чтобы верх и низ тела шли навстречу друг другу.',
            'На вдохе вытяните ноги вперёд и слегка опустите плечи, не касаясь стопами пола.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'crunch_legs_on_stability_ball': {
        't': 'Crunch with Legs on a Stability Ball',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with both calves resting on a stability ball, knees bent to a right angle and hands lightly behind your head.',
            'Press the lower back into the floor and keep the ball still. This is the starting position.',
            'Curl the head, shoulders and upper back off the floor as you breathe out, and hold the squeeze for a second.',
            'Lower back down slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания с ногами на фитболе',
        'rs': [
            'Лягте на спину, положив обе голени на фитбол; колени согнуты под прямым углом, ладони — за головой без нажима.',
            'Прижмите поясницу к полу и удерживайте мяч неподвижным. Это исходное положение.',
            'На выдохе оторвите от пола голову, плечи и верх спины и задержитесь в сокращении на секунду.',
            'На вдохе медленно опуститесь и выполните рекомендованное количество повторений.',
        ],
    },
    'crunch_straight_leg_up': {
        't': 'Crunch with Straight Leg Up',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with one leg bent and that foot on the floor, and the other leg extended straight up toward the ceiling.',
            'Reach both hands toward the raised foot and press the lower back down. This is the starting position.',
            'Curl the head and shoulders off the floor as you breathe out, reaching the fingers toward the raised toes.',
            'Lower slowly as you breathe in without letting the raised leg drift, and repeat for the prescribed amount of repetitions before changing legs.',
        ],
        'ru': 'Скручивания с поднятой прямой ногой',
        'rs': [
            'Лягте на спину: одна нога согнута, стопа стоит на полу, вторая выпрямлена и поднята к потолку.',
            'Вытяните обе руки к поднятой стопе и прижмите поясницу к полу. Это исходное положение.',
            'На выдохе оторвите голову и плечи от пола, тянясь пальцами к носку поднятой ноги.',
            'На вдохе медленно опуститесь, не позволяя поднятой ноге уходить в сторону, и выполните рекомендованное количество повторений, затем смените ногу.',
        ],
    },
    'crunch_floor_female': {
        't': 'Floor Crunch',
        'eq': None, 'm': _C,
        'en': [
            'Lie on your back with the knees bent, the feet flat on the floor and the hands crossed over your chest.',
            'Press the lower back into the floor and keep a fist\'s width between your chin and your chest. This is the starting position.',
            'Curl the head, shoulders and upper back off the floor as you breathe out, lifting only until the shoulder blades clear the mat.',
            'Lower back down slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Скручивания на полу',
        'rs': [
            'Лягте на спину, согните колени, поставьте стопы на пол и скрестите руки на груди.',
            'Прижмите поясницу к полу; между подбородком и грудью оставьте расстояние в кулак. Это исходное положение.',
            'На выдохе оторвите от пола голову, плечи и верх спины, поднимаясь ровно настолько, чтобы лопатки оторвались от коврика.',
            'На вдохе медленно опуститесь и выполните рекомендованное количество повторений.',
        ],
    },
    'front_plank_female': {
        't': 'Front Plank',
        'eq': None, 'm': _C,
        'en': [
            'Lie face down and set your forearms on the floor with the elbows directly under your shoulders.',
            'Push up onto the forearms and the balls of the feet so the body forms a straight line from the heels to the head. This is the starting position.',
            'Squeeze the glutes and draw the navel in so the hips neither sag nor pike, and breathe steadily.',
            'Hold for 20 to 60 seconds, or until the lower back starts to drop, then lower the knees to finish.',
        ],
        'ru': 'Планка на предплечьях',
        'rs': [
            'Лягте лицом вниз и поставьте предплечья на пол так, чтобы локти были точно под плечами.',
            'Поднимитесь на предплечья и подушечки стоп, вытянув тело в прямую линию от пяток до головы. Это исходное положение.',
            'Напрягите ягодицы и подтяните живот, чтобы таз не провисал и не поднимался вверх; дышите ровно.',
            'Удерживайте 20–60 секунд или до момента, когда поясница начнёт проваливаться, затем опуститесь на колени.',
        ],
    },
    'hip_raise_bridge': {
        't': 'Hip Raise Bridge',
        'eq': None, 'm': ['glutes', 'hamstrings', 'core'], 'p': ['glutes'],
        'en': [
            'Lie on your back with the knees bent, the feet flat on the floor hip width apart and the arms by your sides.',
            'Press the lower back gently into the floor and take the weight into your heels. This is the starting position.',
            'Drive through the heels and lift the hips until the body forms a straight line from the shoulders to the knees, breathing out and squeezing the glutes.',
            'Lower the hips back to the floor slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Ягодичный мостик',
        'rs': [
            'Лягте на спину, согните колени, поставьте стопы на пол на ширине таза, руки вдоль тела.',
            'Мягко прижмите поясницу к полу и перенесите вес на пятки. Это исходное положение.',
            'На выдохе оттолкнитесь пятками и поднимите таз так, чтобы тело вытянулось в прямую линию от плеч до коленей, сжимая ягодицы.',
            'На вдохе медленно опустите таз на пол и выполните рекомендованное количество повторений.',
        ],
    },
    'hundred_pilates': {
        't': 'Pilates Hundred',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie on your back, draw both knees over your hips with the shins parallel to the floor and curl the head and shoulders up.',
            'Reach the arms long by your sides a few centimetres off the mat, palms down. This is the starting position.',
            'Extend the legs to about 45 degrees, or keep them bent if the lower back lifts, and pump the arms up and down in small, brisk beats.',
            'Breathe in for five beats and out for five beats, keeping the ribs down and the neck long.',
            'Continue to one hundred beats, then bend the knees in and lower the head to finish.',
        ],
        'ru': 'Пилатес «сотня»',
        'rs': [
            'Лягте на спину, подтяните оба колена над тазом так, чтобы голени были параллельны полу, и оторвите голову и плечи от коврика.',
            'Вытяните руки вдоль тела в нескольких сантиметрах от пола ладонями вниз. Это исходное положение.',
            'Выпрямите ноги примерно под 45 градусов (если поясница отрывается — оставьте их согнутыми) и делайте руками короткие энергичные движения вверх-вниз.',
            'Вдох на пять движений, выдох на пять; рёбра остаются опущенными, шея — вытянутой.',
            'Доведите счёт до ста, затем подтяните колени и опустите голову.',
        ],
    },
    'jack_split_crunches': {
        't': 'Split Jackknife Crunch',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie flat on your back with the legs straight and the arms extended overhead on the floor.',
            'Press the lower back down and lift both heels slightly off the mat. This is the starting position.',
            'Lift one straight leg while curling the torso up and reaching both hands toward that foot, breathing out.',
            'Lower back to the flat position as you breathe in, then repeat with the other leg.',
            'Keep alternating legs for the prescribed amount of repetitions.',
        ],
        'ru': 'Складка к одной ноге попеременно',
        'rs': [
            'Лягте на спину, ноги выпрямлены, руки вытянуты за головой на полу.',
            'Прижмите поясницу и слегка приподнимите обе пятки над ковриком. Это исходное положение.',
            'На выдохе поднимите одну прямую ногу, одновременно скручивая корпус и тянясь обеими руками к её стопе.',
            'На вдохе вернитесь в вытянутое положение, затем повторите с другой ногой.',
            'Чередуйте ноги нужное количество повторений.',
        ],
    },
    'jack_knife_floor': {
        't': 'Floor Jackknife',
        'eq': None, 'm': _C,
        'en': [
            'Lie flat on your back with the arms extended overhead and the legs straight.',
            'Press the lower back into the floor and lift the heels and the hands a few centimetres off the mat. This is the starting position.',
            'Draw both knees toward your chest while curling the torso up and reaching the hands past the knees, breathing out.',
            'Extend the arms and legs back out to the long position as you breathe in, without letting the heels or hands touch down.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Складка с подтягиванием коленей',
        'rs': [
            'Лягте на спину, вытяните руки за головой, ноги выпрямлены.',
            'Прижмите поясницу к полу и приподнимите пятки и кисти на несколько сантиметров над ковриком. Это исходное положение.',
            'На выдохе подтяните оба колена к груди, одновременно скручивая корпус и вынося руки за колени.',
            'На вдохе снова вытяните руки и ноги, не касаясь пола пятками и кистями.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'jackknife_pilates': {
        't': 'Pilates Jackknife',
        'eq': None, 'm': _C, 'd': 'advanced',
        'en': [
            'Lie on your back with the arms long by your sides, palms pressing down, and both legs extended toward the ceiling.',
            'Draw the ribs down and lengthen the neck. This is the starting position.',
            'Roll the hips off the mat and take the legs overhead, then press them up toward the ceiling so the weight sits on your shoulder blades, never the neck.',
            'Roll the spine back down one vertebra at a time as you breathe in, keeping the legs vertical for as long as you can.',
            'Repeat for 3 to 5 controlled repetitions, and skip the exercise entirely if you have any neck complaint.',
        ],
        'ru': 'Пилатес «складной нож»',
        'rs': [
            'Лягте на спину, руки вытянуты вдоль тела и прижаты ладонями к полу, обе ноги подняты к потолку.',
            'Опустите рёбра и вытяните шею. Это исходное положение.',
            'Оторвите таз от коврика и уведите ноги за голову, затем выжмите их вверх так, чтобы вес приходился на лопатки, но ни в коем случае не на шею.',
            'На вдохе раскатывайте позвоночник обратно на пол позвонок за позвонком, как можно дольше удерживая ноги вертикально.',
            'Выполните 3–5 подконтрольных повторений; при любых жалобах на шею упражнение делать нельзя.',
        ],
    },
    'leg_raise_hip_lift': {
        't': 'Leg Raise Hip Lift',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie flat on your back with the arms by your sides, palms down, and both legs extended straight toward the ceiling.',
            'Press the lower back into the floor and the palms into the mat. This is the starting position.',
            'Push the feet straight up so the hips lift a few centimetres off the floor, breathing out and using the abdominals rather than swinging.',
            'Lower the hips back to the floor slowly as you breathe in, keeping the legs vertical throughout.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подъём таза с вертикальными ногами',
        'rs': [
            'Лягте на спину, руки вдоль тела ладонями вниз, обе ноги выпрямлены и подняты к потолку.',
            'Прижмите поясницу к полу, а ладони — к коврику. Это исходное положение.',
            'На выдохе толкните стопы строго вверх так, чтобы таз оторвался от пола на несколько сантиметров; работайте мышцами живота, а не махом.',
            'На вдохе медленно опустите таз на пол, всё время удерживая ноги вертикально.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lying_hip_lift_on_stability_ball': {
        't': 'Lying Hip Lift on a Stability Ball',
        'eq': None, 'm': ['glutes', 'hamstrings', 'core'], 'p': ['glutes'],
        'd': 'intermediate',
        'en': [
            'Lie on your back with both heels on top of a stability ball, legs straight, and the arms by your sides for balance.',
            'Press the heels into the ball and the arms into the floor. This is the starting position.',
            'Lift the hips until the body forms a straight line from the shoulders to the heels, breathing out and squeezing the glutes.',
            'Lower the hips slowly back to the floor as you breathe in, keeping the ball from rolling.',
            'Repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подъём таза с пятками на фитболе',
        'rs': [
            'Лягте на спину, положив обе пятки на фитбол; ноги прямые, руки вдоль тела для устойчивости.',
            'Вдавите пятки в мяч, а руки — в пол. Это исходное положение.',
            'На выдохе поднимите таз так, чтобы тело вытянулось в прямую линию от плеч до пяток, сжимая ягодицы.',
            'На вдохе медленно опустите таз на пол, не позволяя мячу катиться.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lying_scissor_kick_female': {
        't': 'Lying Scissor Kick',
        'eq': None, 'm': _C,
        'ru': 'Скрестные махи ногами лёжа',
        'rs': [
            'Лягте на спину, прижав её к полу или к коврику. Руки полностью вытянуты в стороны ладонями вниз. Примечание: руки остаются неподвижными всё упражнение.',
            'Слегка согнув колени, поднимите ноги так, чтобы пятки были примерно в 15 сантиметрах от пола. Это исходное положение.',
            'Поднимите левую ногу примерно до угла 45 градусов, одновременно опуская правую, пока её пятка не окажется в 5–8 сантиметрах от пола.',
            'Смените движение: поднимите правую ногу и опустите левую. Не задерживайте дыхание.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'medicine_ball_sit_up_wall': {
        't': 'Medicine Ball Wall Sit-Up',
        'eq': 'medicine_ball', 'm': _C, 'd': 'intermediate',
        'en': [
            'Sit about a metre from a solid wall with the knees bent and the feet flat, holding a medicine ball at your chest.',
            'Lower your back to the floor and hold the ball above your chest. This is the starting position.',
            'Sit up fast and throw the ball against the wall as you reach the top, breathing out.',
            'Catch the rebound with both hands and lower back to the floor with the ball under control.',
            'Repeat for the prescribed amount of repetitions, using a ball light enough to catch cleanly.',
        ],
        'ru': 'Подъёмы корпуса с броском набивного мяча в стену',
        'rs': [
            'Сядьте примерно в метре от прочной стены, согнув колени и поставив стопы на пол; держите набивной мяч у груди.',
            'Опустите спину на пол и удерживайте мяч над грудью. Это исходное положение.',
            'На выдохе быстро поднимите корпус и в верхней точке бросьте мяч в стену.',
            'Поймайте отскок обеими руками и подконтрольно опуститесь с мячом обратно на пол.',
            'Выполните рекомендованное количество повторений, взяв мяч такого веса, который вы уверенно ловите.',
        ],
    },
    'reverse_crunch_female': {
        't': 'Reverse Crunch',
        'eq': None, 'm': _C,
        'ru': 'Обратные скручивания',
        'rs': [
            'Лягте на пол, полностью выпрямив ноги; руки вдоль корпуса ладонями вниз. Руки остаются неподвижными всё упражнение.',
            'Поднимите ноги так, чтобы бёдра были перпендикулярны полу, стопы сомкнуты и параллельны полу. Это исходное положение.',
            'На вдохе подтяните ноги к корпусу, подкручивая таз назад и отрывая его от пола. В конце движения колени касаются груди.',
            'Задержитесь в сокращении на секунду и на выдохе верните ноги в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'rotate_push_up_female': {
        't': 'Rotating Push-Up',
        'eq': None, 'm': ['chest', 'core', 'shoulders', 'triceps'],
        'p': ['chest'], 'd': 'intermediate',
        'en': [
            'Take a push-up position with the hands under your shoulders and the body in a straight line from the heels to the head.',
            'Brace the core and the glutes. This is the starting position.',
            'Lower your chest toward the floor as you breathe in, then press back up to straight arms as you breathe out.',
            'At the top, shift your weight onto one hand, rotate the hips and chest to that side and reach the free arm toward the ceiling into a side plank.',
            'Return the hand to the floor and repeat, alternating the rotation side each repetition.',
        ],
        'ru': 'Отжимания с поворотом',
        'rs': [
            'Примите упор лёжа: ладони под плечами, тело вытянуто в прямую линию от пяток до головы.',
            'Напрягите живот и ягодицы. Это исходное положение.',
            'На вдохе опустите грудь к полу, затем на выдохе выжмите себя вверх до прямых рук.',
            'В верхней точке перенесите вес на одну руку, разверните таз и грудь в эту сторону и вытяните свободную руку к потолку, переходя в боковую планку.',
            'Верните ладонь на пол и повторите, меняя сторону поворота в каждом повторении.',
        ],
    },
    'side_bend_on_stability_ball': {
        't': 'Side Bend on a Stability Ball',
        'eq': None, 'm': _C,
        'en': [
            'Lie sideways over a stability ball so the ball supports the side of your hip and ribs, legs stacked and braced against a wall or spread for balance.',
            'Place the hands lightly behind your head with the elbows wide. This is the starting position.',
            'Bend sideways over the ball as you breathe in, letting the top side of the waist lengthen.',
            'Lift the torso up sideways until it is in line with your legs as you breathe out, and hold the squeeze for a second.',
            'Repeat for the prescribed amount of repetitions, then turn over and work the other side.',
        ],
        'ru': 'Боковые наклоны на фитболе',
        'rs': [
            'Лягте боком на фитбол так, чтобы он поддерживал бок таза и рёбра; ноги одна на другой, упритесь ими в стену или расставьте для устойчивости.',
            'Положите ладони за голову без нажима, локти разведены. Это исходное положение.',
            'На вдохе наклонитесь вбок через мяч, позволяя верхней стороне талии удлиниться.',
            'На выдохе поднимите корпус вбок до одной линии с ногами и задержитесь в сокращении на секунду.',
            'Выполните рекомендованное количество повторений, затем перевернитесь и проработайте другую сторону.',
        ],
    },
    'sit_up': {
        't': 'Anchored Sit-Up',
        'eq': None, 'm': _C,
        'ru': 'Подъёмы корпуса с фиксацией стоп',
        'rs': [
            'Лягте на пол, заведя стопы под неподвижную опору или попросив напарника их удержать. Колени согнуты.',
            'Положите ладони за голову и сцепите пальцы в замок. Это исходное положение.',
            'Поднимите верх тела так, чтобы он образовал с бёдрами воображаемую букву «V». На этом движении делайте выдох.',
            'Почувствовав сокращение, задержитесь на секунду и на вдохе опустите верх тела обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'weighted_lying_twist': {
        't': 'Weighted Lying Twist',
        'eq': None, 'm': _C, 'd': 'intermediate',
        'en': [
            'Lie on your back holding a weight plate or a dumbbell in both hands with the arms pointing straight up over your chest.',
            'Bend the knees over your hips so the shins are parallel to the floor, and press the lower back down. This is the starting position.',
            'Let the knees travel slowly to one side as far as you can go while both shoulders stay on the floor and the arms stay vertical.',
            'Bring the knees back to the middle using the side of your waist, then repeat to the other side.',
            'Keep alternating for the prescribed amount of repetitions, using a weight light enough to hold the arms still.',
        ],
        'ru': 'Скручивания лёжа с отягощением',
        'rs': [
            'Лягте на спину, удерживая блин или гантель обеими руками на прямых руках над грудью.',
            'Согните колени над тазом так, чтобы голени были параллельны полу, и прижмите поясницу. Это исходное положение.',
            'Медленно уведите колени в одну сторону настолько, насколько это возможно, оставляя обе лопатки на полу, а руки — вертикальными.',
            'Верните колени в середину усилием боковых мышц живота, затем повторите в другую сторону.',
            'Чередуйте стороны нужное количество повторений, взяв такой вес, при котором руки остаются неподвижными.',
        ],
    },
    'seated_twist_straight_arm': {
        't': 'Seated Twist - Straight Arm',
        'eq': None, 'm': ['core'],
        'en': [
            'Sit tall on a mat with the knees bent and the feet flat, or with the legs crossed if that is more comfortable.',
            'Reach both arms straight forward at shoulder height with the palms facing each other. This is the starting position.',
            'Rotate the torso to one side, keeping the arms straight and level and the hips facing forward, and pause for a moment at the end.',
            'Return through the middle and rotate to the other side, moving from the ribs rather than throwing the arms.',
            'Keep alternating for the prescribed amount of repetitions.',
        ],
        'ru': 'Повороты корпуса сидя с вытянутыми руками',
        'rs': [
            'Сядьте на коврик с прямой спиной: колени согнуты, стопы на полу, либо ноги скрещены, если так удобнее.',
            'Вытяните обе руки прямо перед собой на уровне плеч ладонями друг к другу. Это исходное положение.',
            'Разверните корпус в одну сторону, удерживая руки прямыми и на одном уровне, а таз — направленным вперёд, и на мгновение задержитесь.',
            'Вернитесь через середину и разверните корпус в другую сторону, поворачиваясь от рёбер, а не забрасывая руки.',
            'Чередуйте стороны нужное количество повторений.',
        ],
    },
}
