# -*- coding: utf-8 -*-
"""Shoulders. 35 rows: 6 merge into the existing catalog, 29 authored here.

This group had the most wrong upstream matches of any folder, because "lateral
raise", "rear lateral raise" and "front raise" tokenise almost identically. Nine
matched texts described a different setup from the title and are replaced:
every seated variant matched a standing one, every one-arm lateral raise matched
a lying REAR raise, the wide-grip upright row matched a narrow-grip one, the
Smith press matched a cable machine, and the hammer press matched a text that
rotates the palms forward -- which is the grip a hammer press does not use.
"""
_D = ['shoulders']
_DT = ['shoulders', 'triceps']
_RD = ['shoulders', 'back']

ENTRIES = {
    'band_bent_over_rear_lateral_raise': {
        't': 'Band Bent-Over Rear Lateral Raise',
        'eq': 'resistance_bands', 'm': _RD, 'p': ['shoulders'],
        'en': [
            'Stand on the middle of a resistance band and take an end in each hand, then hinge forward from the hips until your torso is close to parallel with the floor.',
            'Let the hands hang under your chest with the elbows slightly bent and the back flat. This is the starting position.',
            'Raise both arms out to the sides until the elbows reach shoulder height as you breathe out, leading with the elbows and keeping the torso still.',
            'Lower the hands back under your chest slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Разведение рук с лентой в наклоне',
        'rs': [
            'Встаньте на середину ленты и возьмите по концу в каждую руку, затем наклонитесь вперёд от тазобедренных суставов почти до параллели корпуса с полом.',
            'Руки свободно свисают под грудью, локти слегка согнуты, спина прямая. Это исходное положение.',
            'На выдохе разведите руки в стороны, пока локти не окажутся на уровне плеч; ведите движение локтями и не двигайте корпусом.',
            'На вдохе медленно опустите кисти обратно под грудь и выполните рекомендованное количество повторений.',
        ],
    },
    'band_one_arm_forward_raise': {
        't': 'Band One-Arm Front Raise',
        'eq': 'resistance_bands', 'm': _D,
        'en': [
            'Stand on one end of a resistance band and hold the other end in the opposite hand, arm straight down in front of your thigh.',
            'Stand tall with the feet hip width apart and a slight bend in the working elbow. This is the starting position.',
            'Raise the arm straight out in front of you to shoulder height as you breathe out, with the palm facing down and no swing in the torso.',
            'Lower the hand slowly back to your thigh as you breathe in, and repeat for the prescribed amount of repetitions before changing arms.',
        ],
        'ru': 'Подъём одной руки перед собой с лентой',
        'rs': [
            'Встаньте на один конец ленты и возьмите другой конец противоположной рукой; рука выпрямлена перед бедром.',
            'Встаньте прямо, стопы на ширине таза, рабочий локоть слегка согнут. Это исходное положение.',
            'На выдохе поднимите руку прямо перед собой до уровня плеча ладонью вниз, не помогая себе корпусом.',
            'На вдохе медленно опустите кисть обратно к бедру и выполните рекомендованное количество повторений, затем смените руку.',
        ],
    },
    'band_standing_rear_delt_row': {
        't': 'Band Standing Rear Delt Row',
        'eq': 'resistance_bands', 'm': _RD, 'p': ['shoulders'],
        'en': [
            'Anchor a resistance band at chest height and stand back from it holding an end in each hand, arms straight out in front of you.',
            'Stand tall with the feet hip width apart and the band already under tension. This is the starting position.',
            'Pull the hands back toward your chest with the elbows high and wide, so the upper arms travel out to the sides rather than along your ribs.',
            'Squeeze the shoulder blades together for a second, then let the arms straighten slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Тяга ленты к лицу стоя',
        'rs': [
            'Закрепите ленту на уровне груди, отойдите от неё и возьмите по концу в каждую руку; руки вытянуты прямо перед собой.',
            'Встаньте прямо, стопы на ширине таза, лента уже натянута. Это исходное положение.',
            'Потяните кисти к груди, разводя локти высоко и в стороны, чтобы плечи уходили наружу, а не вдоль рёбер.',
            'На секунду сведите лопатки, затем на вдохе медленно выпрямите руки и выполните рекомендованное количество повторений.',
        ],
    },
    'barbell_front_raise': {
        't': 'Barbell Front Raise',
        'eq': 'barbell', 'm': _D,
        'en': [
            'Stand upright holding a barbell with an overhand grip at shoulder width, the bar resting against the front of your thighs.',
            'Keep the arms straight with a slight bend at the elbows and brace the core. This is the starting position.',
            'Raise the bar in an arc straight out in front of you until it reaches shoulder height, breathing out and keeping the torso still.',
            'Lower the bar slowly back to your thighs as you breathe in, and repeat for the prescribed amount of repetitions without swinging.',
        ],
        'ru': 'Подъём штанги перед собой',
        'rs': [
            'Встаньте прямо, удерживая штангу прямым хватом на ширине плеч; гриф касается передней поверхности бёдер.',
            'Руки прямые, локти слегка согнуты, живот подтянут. Это исходное положение.',
            'На выдохе поднимите гриф по дуге прямо перед собой до уровня плеч, не двигая корпусом.',
            'На вдохе медленно опустите гриф обратно к бёдрам и выполните рекомендованное количество повторений без раскачивания.',
        ],
    },
    'barbell_seated_behind_head_military_press': {
        't': 'Barbell Seated Behind-the-Head Press',
        'eq': 'barbell', 'm': _DT, 'd': 'intermediate', 'min': 8,
        'ru': 'Жим штанги из-за головы сидя',
        'rs': [
            'Сядьте на скамью для жима сидя со штангой за головой: попросите напарника подать гриф (так безопаснее для вращательной манжеты) или аккуратно снимите его сами прямым хватом (ладони вперёд). Подсказка: хват шире плеч, чтобы в нижней точке между предплечьем и плечом получался прямой угол.',
            'Взяв гриф правильным хватом, поднимите его над головой и выпрямите руки. Удерживайте его примерно на уровне плеч, чуть впереди головы. Это исходное положение.',
            'На вдохе медленно опустите гриф до уровня ключиц.',
            'На выдохе выжмите гриф обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'barbell_upright_row_wide_grip': {
        't': 'Barbell Upright Row - Wide Grip',
        'eq': 'barbell', 'm': ['shoulders', 'traps'], 'p': ['shoulders'],
        'en': [
            'Stand upright holding a barbell with an overhand grip set wider than shoulder width, the bar resting on your thighs.',
            'Keep the back straight, the chest up and a slight bend in the elbows. This is the starting position.',
            'Lift the bar close to your body up to about chest height as you breathe out, driving with the elbows so they stay higher than the wrists.',
            'Lower the bar slowly back to your thighs as you breathe in. The wide grip keeps the shoulders in a safer position than a narrow one.',
            'Repeat for the prescribed amount of repetitions, stopping if the shoulders feel pinched at the top.',
        ],
        'ru': 'Тяга штанги к груди широким хватом',
        'rs': [
            'Встаньте прямо, удерживая штангу прямым хватом шире плеч; гриф лежит на бёдрах.',
            'Спина прямая, грудь развёрнута, локти слегка согнуты. Это исходное положение.',
            'На выдохе поднимите гриф вдоль тела примерно до уровня груди, ведя движение локтями так, чтобы они оставались выше запястий.',
            'На вдохе медленно опустите гриф обратно к бёдрам. Широкий хват удерживает плечевые суставы в более безопасном положении, чем узкий.',
            'Выполните рекомендованное количество повторений и прекратите подход, если в верхней точке появляется ощущение защемления в плече.',
        ],
    },
    'cable_crossover_reverse_fly': {
        't': 'Cable Crossover Reverse Fly',
        'eq': 'cable_machine', 'm': _RD, 'p': ['shoulders'],
        'en': [
            'Set both pulleys to shoulder height, stand in the middle and take the left handle in your right hand and the right handle in your left, so the cables cross in front of you.',
            'Stand tall with the arms out in front at shoulder height and a slight bend in the elbows. This is the starting position.',
            'Pull the handles apart and back until your arms are out to the sides in line with your shoulders, breathing out and squeezing the shoulder blades together.',
            'Let the cables draw the arms back in front of you slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Обратное сведение рук на блоках',
        'rs': [
            'Установите оба блока на высоте плеч, встаньте посередине и возьмите левую рукоять правой рукой, а правую — левой, чтобы тросы перекрещивались перед вами.',
            'Встаньте прямо: руки вытянуты вперёд на уровне плеч, локти слегка согнуты. Это исходное положение.',
            'На выдохе разведите рукояти в стороны и назад, пока руки не окажутся на одной линии с плечами, сводя лопатки.',
            'На вдохе медленно позвольте тросам свести руки обратно перед собой и выполните рекомендованное количество повторений.',
        ],
    },
    'cable_front_raise': {
        't': 'Cable Front Raise',
        'eq': 'cable_machine', 'm': _D,
        'en': [
            'Attach a straight bar to a low pulley, stand with your back to the stack and hold the bar in front of your thighs with an overhand grip.',
            'Step forward until the cable is under tension, stand tall and keep a slight bend in the elbows. This is the starting position.',
            'Raise the bar straight out in front of you to shoulder height as you breathe out, keeping the torso still and the palms facing down.',
            'Lower the bar slowly back to your thighs as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Подъём рукояти перед собой на нижнем блоке',
        'rs': [
            'Закрепите прямую рукоять на нижнем блоке, встаньте спиной к стойке и возьмите рукоять прямым хватом перед бёдрами.',
            'Отойдите вперёд, чтобы трос натянулся; встаньте прямо, локти слегка согнуты. Это исходное положение.',
            'На выдохе поднимите рукоять прямо перед собой до уровня плеч, не двигая корпусом и удерживая ладони вниз.',
            'На вдохе медленно опустите рукоять обратно к бёдрам и выполните рекомендованное количество повторений.',
        ],
    },
    'cable_lateral_raise': {
        't': 'Cable Lateral Raise',
        'eq': 'cable_machine', 'm': _D,
        'en': [
            'Set a low pulley and stand side-on to it, taking the handle in the hand furthest from the stack so the cable passes in front of your body.',
            'Let the working arm hang across your thighs with a slight bend in the elbow, and hold the frame with the other hand. This is the starting position.',
            'Raise the arm out to the side until the hand reaches shoulder height as you breathe out, leading with the elbow.',
            'Lower the arm slowly back across your body as you breathe in, and repeat for the prescribed amount of repetitions before changing sides.',
        ],
        'ru': 'Отведение руки в сторону на нижнем блоке',
        'rs': [
            'Встаньте боком к нижнему блоку и возьмите рукоять дальней от стойки рукой, чтобы трос проходил перед корпусом.',
            'Рабочая рука свободно висит поперёк бёдер, локоть слегка согнут; свободной рукой держитесь за раму. Это исходное положение.',
            'На выдохе поднимите руку в сторону до уровня плеча, ведя движение локтем.',
            'На вдохе медленно опустите руку обратно поперёк корпуса и выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'cable_one_arm_forward_raise': {
        't': 'Cable One-Arm Front Raise',
        'eq': 'cable_machine', 'm': _D,
        'en': [
            'Attach a single handle to a low pulley, face away from the stack and hold the handle in one hand in front of your thigh, palm facing back.',
            'Stand tall with the feet staggered for balance and a slight bend in the working elbow. This is the starting position.',
            'Raise the arm straight out in front of you until it is slightly above parallel with the floor, breathing out and pausing for a second at the top.',
            'Lower the hand slowly back to your thigh as you breathe in, and repeat for the prescribed amount of repetitions before changing arms.',
        ],
        'ru': 'Подъём одной руки перед собой на нижнем блоке',
        'rs': [
            'Закрепите одиночную рукоять на нижнем блоке, встаньте спиной к стойке и держите рукоять одной рукой перед бедром ладонью назад.',
            'Встаньте прямо, одну ногу выведите вперёд для устойчивости; рабочий локоть слегка согнут. Это исходное положение.',
            'На выдохе поднимите руку прямо перед собой чуть выше параллели с полом и задержитесь в верхней точке на секунду.',
            'На вдохе медленно опустите кисть обратно к бедру и выполните рекомендованное количество повторений, затем смените руку.',
        ],
    },
    'cable_one_arm_lateral_raise': {
        't': 'Cable One-Arm Lateral Raise',
        'eq': 'cable_machine', 'm': _D,
        'en': [
            'Set a single handle on a low pulley and stand side-on to the stack, taking the handle in the far hand so the cable crosses your body.',
            'Stand tall with the working arm across the front of your thighs and the elbow slightly bent. This is the starting position.',
            'Raise the arm out to the side in one smooth arc until the elbow is level with your shoulder, breathing out and holding for a second.',
            'Lower the arm slowly along the same arc as you breathe in, and repeat for the prescribed amount of repetitions before changing sides.',
        ],
        'ru': 'Отведение руки в сторону на блоке одной рукой',
        'rs': [
            'Закрепите одиночную рукоять на нижнем блоке и встаньте боком к стойке, взяв рукоять дальней рукой, чтобы трос пересекал корпус.',
            'Встаньте прямо: рабочая рука перед бёдрами, локоть слегка согнут. Это исходное положение.',
            'На выдохе поднимите руку в сторону по плавной дуге, пока локоть не окажется на уровне плеча, и задержитесь на секунду.',
            'На вдохе медленно опустите руку по той же дуге и выполните рекомендованное количество повторений, затем смените сторону.',
        ],
    },
    'dumbbell_front_raise': {
        't': 'Dumbbell Front Raise',
        'eq': 'dumbbell', 'm': _D,
        'ru': 'Подъём гантелей перед собой',
        'rs': [
            'Возьмите пару гантелей и встаньте прямо; гантели находятся перед бёдрами на прямых руках, ладони обращены к бёдрам. Это исходное положение.',
            'Не двигая корпусом (без раскачивания), поднимите левую гантель вперёд, слегка согнув локоть и всё время удерживая ладонь вниз. Поднимайте, пока рука не окажется чуть выше параллели с полом. На этом движении делайте выдох и задержитесь в верхней точке на секунду. После паузы сделайте вдох.',
            'Медленно опустите гантель обратно в исходное положение, одновременно поднимая правую.',
            'Продолжайте чередовать руки, пока не выполните рекомендованное количество повторений каждой.',
        ],
    },
    'dumbbell_incline_hammer_press': {
        't': 'Dumbbell Incline Hammer Press',
        'eq': 'dumbbell', 'm': ['shoulders', 'chest', 'triceps'],
        'p': ['shoulders'],
        'en': [
            'Set a bench to a steep incline of about 60 degrees and sit back with a dumbbell in each hand resting on your thighs.',
            'Bring the dumbbells up to shoulder height with the palms facing each other, elbows under the wrists. This is the starting position.',
            'Press both dumbbells straight up until the arms are almost locked out as you breathe out, keeping the palms facing each other the whole way.',
            'Lower them back to shoulder height under control as you breathe in, taking about twice as long as the press.',
            'Repeat for the prescribed amount of repetitions, then bring the dumbbells down onto your thighs before standing.',
        ],
        'ru': 'Жим гантелей на наклонной скамье нейтральным хватом',
        'rs': [
            'Установите скамью под крутым наклоном около 60 градусов и сядьте, положив гантели на бёдра.',
            'Поднимите гантели на уровень плеч ладонями друг к другу, локти под запястьями. Это исходное положение.',
            'На выдохе выжмите обе гантели вертикально вверх почти до полного выпрямления рук, всё время сохраняя нейтральное положение ладоней.',
            'На вдохе подконтрольно опустите гантели на уровень плеч; опускание должно занимать примерно вдвое больше времени, чем жим.',
            'Выполните рекомендованное количество повторений, затем опустите гантели на бёдра и только потом вставайте.',
        ],
    },
    'dumbbell_incline_rear_lateral_raise': {
        't': 'Dumbbell Incline Rear Lateral Raise',
        'eq': 'dumbbell', 'm': _RD, 'p': ['shoulders'],
        'ru': 'Разведение гантелей лёжа на наклонной скамье',
        'rs': [
            'Держа по гантели в каждой руке, лягте грудью вниз на скамью с небольшим наклоном (около 15 градусов от пола).',
            'Расположите ладони нейтрально (обращены к корпусу), руки выпрямлены, локти слегка согнуты. Это исходное положение.',
            'На выдохе разведите руки в стороны, пока локти не окажутся на уровне плеч, а руки — примерно параллельно полу. Подсказка: удерживайте руки перпендикулярно корпусу и выпрямленными на всём движении, а в верхней точке задержитесь на секунду.',
            'На вдохе медленно опустите гантели в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_iron_cross': {
        't': 'Dumbbell Iron Cross',
        'eq': 'dumbbell', 'm': ['shoulders', 'chest'], 'p': ['shoulders'],
        'd': 'intermediate',
        'en': [
            'Stand upright with a dumbbell in each hand at your sides, feet hip width apart and the core braced.',
            'Keep the arms straight with only a slight bend at the elbows. This is the starting position.',
            'Raise both arms out to the sides to shoulder height as you breathe out, so the body forms a cross.',
            'Without lowering them, sweep the arms forward until the dumbbells meet in front of your chest, then open them back out to the sides.',
            'Lower the arms to your sides as you breathe in, and repeat for the prescribed amount of repetitions with a weight light enough to keep the path clean.',
        ],
        'ru': 'Упражнение «крест» с гантелями',
        'rs': [
            'Встаньте прямо, держа по гантели в каждой руке вдоль тела; стопы на ширине таза, живот подтянут.',
            'Руки прямые, локти лишь слегка согнуты. Это исходное положение.',
            'На выдохе разведите обе руки в стороны до уровня плеч так, чтобы тело образовало крест.',
            'Не опуская руки, сведите их вперёд, пока гантели не встретятся перед грудью, затем снова разведите в стороны.',
            'На вдохе опустите руки вдоль тела и выполните рекомендованное количество повторений с весом, который позволяет сохранять чистую траекторию.',
        ],
    },
    'dumbbell_lateral_raise': {
        't': 'Dumbbell Lateral Raise',
        'eq': 'dumbbell', 'm': _D,
        'ru': 'Разведение гантелей в стороны стоя',
        'rs': [
            'Возьмите по гантели в каждую руку и встаньте прямо: руки опущены по бокам, локти слегка согнуты, спина прямая. Это исходное положение. Подсказка: гантели находятся рядом с бёдрами, ладони обращены назад.',
            'На выдохе поднимите гантели усилием средних дельт. Гантели идут по сторонам тела. Поднимайте их почти до уровня подбородка. Подсказка: движение ведут локти — они всё время выше предплечий. Корпус остаётся неподвижным, в верхней точке задержитесь на секунду.',
            'На вдохе медленно опустите гантели обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_one_arm_lateral_raise': {
        't': 'Dumbbell One-Arm Lateral Raise',
        'eq': 'dumbbell', 'm': _D,
        'en': [
            'Stand upright with a dumbbell in one hand at your side and hold a rack upright with the other hand for balance.',
            'Keep the working arm straight with a slight bend at the elbow and the palm facing your thigh. This is the starting position.',
            'Raise the dumbbell out to the side until the elbow reaches shoulder height as you breathe out, leading with the elbow and keeping the torso still.',
            'Lower the dumbbell slowly back to your side as you breathe in, and repeat for the prescribed amount of repetitions before changing arms.',
        ],
        'ru': 'Разведение гантели в сторону одной рукой',
        'rs': [
            'Встаньте прямо, взяв гантель в одну руку; другой рукой держитесь за стойку для равновесия.',
            'Рабочая рука прямая, локоть слегка согнут, ладонь обращена к бедру. Это исходное положение.',
            'На выдохе поднимите гантель в сторону, пока локоть не окажется на уровне плеча; ведите движение локтем, не двигая корпусом.',
            'На вдохе медленно опустите гантель обратно к бедру и выполните рекомендованное количество повторений, затем смените руку.',
        ],
    },
    'dumbbell_rear_lateral_raise': {
        't': 'Dumbbell Bent-Over Rear Lateral Raise',
        'eq': 'dumbbell', 'm': _RD, 'p': ['shoulders'],
        'en': [
            'Stand holding a dumbbell in each hand and hinge forward from the hips until your torso is close to parallel with the floor, knees slightly bent.',
            'Let the dumbbells hang under your chest with the palms facing each other and the elbows slightly bent. This is the starting position.',
            'Raise both arms out to the sides until the elbows are level with your shoulders as you breathe out, keeping the back flat.',
            'Lower the dumbbells slowly back under your chest as you breathe in, and repeat for the prescribed amount of repetitions without using the lower back to swing.',
        ],
        'ru': 'Разведение гантелей в наклоне',
        'rs': [
            'Возьмите по гантели в каждую руку и наклонитесь вперёд от тазобедренных суставов почти до параллели корпуса с полом, слегка согнув колени.',
            'Гантели свободно свисают под грудью ладонями друг к другу, локти слегка согнуты. Это исходное положение.',
            'На выдохе разведите руки в стороны, пока локти не окажутся на уровне плеч, сохраняя спину прямой.',
            'На вдохе медленно опустите гантели обратно под грудь и выполните рекомендованное количество повторений, не помогая себе поясницей.',
        ],
    },
    'dumbbell_seated_front_raise': {
        't': 'Dumbbell Seated Front Raise',
        'eq': 'dumbbell', 'm': _D,
        'en': [
            'Sit on the end of a bench with your feet flat on the floor and a dumbbell in each hand resting on your thighs, palms facing down.',
            'Sit tall with the back straight and the core braced. This is the starting position.',
            'Raise one dumbbell straight out in front of you to shoulder height as you breathe out, keeping the elbow slightly bent.',
            'Lower it slowly back to your thigh as you breathe in while the other arm begins to rise.',
            'Keep alternating until you have completed the prescribed amount of repetitions with each arm. Sitting removes the leg drive, so use a lighter weight than standing.',
        ],
        'ru': 'Подъём гантелей перед собой сидя',
        'rs': [
            'Сядьте на край скамьи, поставив стопы на пол; гантели лежат на бёдрах ладонями вниз.',
            'Сядьте ровно, спина прямая, живот подтянут. Это исходное положение.',
            'На выдохе поднимите одну гантель прямо перед собой до уровня плеча, слегка согнув локоть.',
            'На вдохе медленно опустите её обратно на бедро, одновременно начиная поднимать вторую руку.',
            'Чередуйте руки, пока не выполните рекомендованное количество повторений каждой. Сидя нельзя помочь себе ногами, поэтому берите вес меньше, чем стоя.',
        ],
    },
    'dumbbell_seated_lateral_raise': {
        't': 'Dumbbell Seated Lateral Raise',
        'eq': 'dumbbell', 'm': _D,
        'en': [
            'Sit on the end of a bench with your feet flat on the floor and a dumbbell in each hand hanging beside your hips, palms facing each other.',
            'Sit tall with the back straight and the elbows slightly bent. This is the starting position.',
            'Raise both dumbbells out to the sides until the elbows reach shoulder height as you breathe out, leading with the elbows.',
            'Lower them slowly back beside your hips as you breathe in.',
            'Repeat for the prescribed amount of repetitions; seated, there is no way to swing the weight up, so the shoulders do all the work.',
        ],
        'ru': 'Разведение гантелей в стороны сидя',
        'rs': [
            'Сядьте на край скамьи, поставив стопы на пол; гантели висят по бокам от таза ладонями друг к другу.',
            'Сядьте ровно, спина прямая, локти слегка согнуты. Это исходное положение.',
            'На выдохе разведите обе гантели в стороны, пока локти не окажутся на уровне плеч, ведя движение локтями.',
            'На вдохе медленно опустите их обратно к бокам.',
            'Выполните рекомендованное количество повторений: сидя закинуть вес рывком невозможно, поэтому всю работу делают дельтовидные мышцы.',
        ],
    },
    'dumbbell_upright_row': {
        't': 'Dumbbell Upright Row',
        'eq': 'dumbbell', 'm': ['shoulders', 'traps'], 'p': ['shoulders'],
        'ru': 'Тяга гантелей к подбородку',
        'rs': [
            'Возьмите по гантели в каждую руку прямым хватом (ладони вперёд) чуть уже ширины плеч. Гантели лежат на бёдрах, руки выпрямлены с лёгким сгибом в локтях, спина прямая. Это исходное положение.',
            'На выдохе поднимите гантели усилием средних дельт. Гантели идут близко к телу, движение ведут локти. Поднимайте почти до касания подбородка. Подсказка: локти всё время выше предплечий, корпус неподвижен, в верхней точке задержитесь на секунду.',
            'На вдохе медленно опустите гантели обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'lever_lateral_raise': {
        't': 'Machine Lateral Raise',
        'eq': None, 'm': _D,
        'en': [
            'Set the seat of the lateral raise machine so the pads sit against the outside of your upper arms just above the elbows.',
            'Sit with your back against the pad, take the handles and keep the arms bent at your sides. This is the starting position.',
            'Push the pads out and up with the upper arms until the elbows reach shoulder height as you breathe out, and hold for a second.',
            'Lower the pads slowly back to your sides as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Разведение рук в стороны в тренажёре',
        'rs': [
            'Отрегулируйте сиденье тренажёра так, чтобы упоры легли на внешнюю поверхность плеч чуть выше локтей.',
            'Сядьте, прижав спину к спинке, возьмитесь за рукояти; руки согнуты и прижаты к бокам. Это исходное положение.',
            'На выдохе разведите упоры вверх и в стороны усилием плеч, пока локти не окажутся на уровне плечевых суставов, и задержитесь на секунду.',
            'На вдохе медленно верните упоры к бокам и выполните рекомендованное количество повторений.',
        ],
    },
    'lever_military_press': {
        't': 'Machine Shoulder Press',
        'eq': 'shoulder_press_machine', 'm': _DT,
        'en': [
            'Set the seat so the handles start level with the tops of your shoulders and sit with your back flat against the pad.',
            'Take a handle in each hand with an overhand grip and keep the feet flat on the floor. This is the starting position.',
            'Press the handles overhead until the arms are almost straight as you breathe out, without locking the elbows or arching the lower back.',
            'Lower the handles slowly back to shoulder height as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Жим над головой в тренажёре',
        'rs': [
            'Отрегулируйте сиденье так, чтобы рукояти начинались на уровне верха плеч, и сядьте, прижав спину к спинке.',
            'Возьмитесь за рукояти прямым хватом, стопы стоят на полу. Это исходное положение.',
            'На выдохе выжмите рукояти над головой почти до полного выпрямления рук, не блокируя локти и не прогибая поясницу.',
            'На вдохе медленно опустите рукояти на уровень плеч и выполните рекомендованное количество повторений.',
        ],
    },
    'lever_seated_reverse_fly': {
        't': 'Machine Seated Reverse Fly',
        'eq': 'pec_deck', 'm': _RD, 'p': ['shoulders'],
        'en': [
            'Turn the pec deck around so you sit facing the pad, and set the handles so they start in front of your chest at shoulder height.',
            'Take a handle in each hand with the arms straight in front of you and a slight bend in the elbows. This is the starting position.',
            'Sweep both arms out and back until they are in line with your shoulders as you breathe out, squeezing the shoulder blades together.',
            'Let the handles come back together in front of your chest slowly as you breathe in, and repeat for the prescribed amount of repetitions.',
        ],
        'ru': 'Обратное разведение рук в тренажёре',
        'rs': [
            'Развернитесь в тренажёре «бабочка» лицом к спинке и выставьте рукояти так, чтобы они начинались перед грудью на уровне плеч.',
            'Возьмитесь за рукояти, руки вытянуты вперёд и слегка согнуты в локтях. Это исходное положение.',
            'На выдохе разведите руки в стороны и назад, пока они не окажутся на одной линии с плечами, сводя лопатки.',
            'На вдохе медленно позвольте рукоятям вернуться вперёд и выполните рекомендованное количество повторений.',
        ],
    },
    'military_press': {
        't': 'Military Press',
        'eq': 'barbell', 'm': _DT, 'd': 'intermediate', 'min': 8,
        'ru': 'Армейский жим стоя',
        'rs': [
            'Поставьте штангу на стойки примерно на уровне груди. Выбрав вес, возьмитесь за гриф прямым хватом (ладони вперёд) шире плеч.',
            'Слегка согните колени и положите гриф на ключицы. Снимите штангу со стоек, удерживая её на груди, отшагните назад и поставьте стопы на ширине плеч.',
            'Выжмите гриф над головой, выпрямив руки. Удерживайте его примерно на уровне плеч, чуть впереди головы. Это исходное положение.',
            'На вдохе медленно опустите гриф до ключиц.',
            'На выдохе выжмите гриф обратно в исходное положение.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'smith_seated_shoulder_press': {
        't': 'Smith Machine Seated Shoulder Press',
        'eq': 'smith_machine', 'm': _DT, 'min': 8,
        'en': [
            'Set an upright bench inside the Smith machine so the bar lines up just above your collarbones when you sit down.',
            'Unhook the bar and hold it with an overhand grip a little wider than shoulder width, elbows under the wrists. This is the starting position.',
            'Press the bar straight up until the arms are almost locked out as you breathe out, keeping the back against the pad.',
            'Lower the bar slowly back to just above your collarbones as you breathe in.',
            'Repeat for the prescribed amount of repetitions, then rotate the bar back into its hooks before letting go.',
        ],
        'ru': 'Жим сидя в машине Смита',
        'rs': [
            'Поставьте скамью со спинкой в машину Смита так, чтобы в положении сидя гриф оказался чуть выше ключиц.',
            'Снимите гриф со стопоров и возьмитесь прямым хватом чуть шире плеч, локти под запястьями. Это исходное положение.',
            'На выдохе выжмите гриф вертикально вверх почти до полного выпрямления рук, не отрывая спину от спинки.',
            'На вдохе медленно опустите гриф обратно чуть выше ключиц.',
            'Выполните рекомендованное количество повторений, затем поверните гриф обратно на стопоры и только после этого отпустите его.',
        ],
    },
    'stretching_band_warm_up_shoulder_stretch': {
        't': 'Band Warm-Up Shoulder Stretch',
        'eq': 'resistance_bands', 'm': ['shoulders', 'chest'], 'p': ['shoulders'],
        'stretch': True,
        'en': [
            'Hold a light resistance band in both hands in front of your thighs, wider than shoulder width, with the arms straight.',
            'Stand tall with the shoulders down and the core braced. This is the starting position.',
            'Keeping the arms straight, raise the band overhead and continue back behind your head as far as the shoulders allow without pain.',
            'Bring it slowly back over the front and repeat 8 to 10 times, widening the grip if the shoulders feel tight.',
        ],
        'ru': 'Разминка плеч с лентой',
        'rs': [
            'Возьмите лёгкую ленту обеими руками перед бёдрами хватом шире плеч, руки выпрямлены.',
            'Встаньте прямо, плечи опущены, живот подтянут. Это исходное положение.',
            'Не сгибая руки, поднимите ленту над головой и уведите её назад за голову настолько, насколько позволяют плечи и пока это не вызывает боли.',
            'Медленно верните ленту вперёд и повторите 8–10 раз; если в плечах тесно, возьмитесь шире.',
        ],
    },
    'stretching_rear_deltoid_stretch': {
        't': 'Rear Deltoid Stretch',
        'eq': None, 'm': ['shoulders', 'back'], 'p': ['shoulders'],
        'stretch': True,
        'en': [
            'Stand or sit tall with the shoulders relaxed and down.',
            'Bring one straight arm across your chest at shoulder height. This is the starting position.',
            'Hook the other forearm above the elbow and draw the arm closer to your chest until the back of the shoulder stretches.',
            'Hold for 20 to 30 seconds without shrugging, then release and change sides.',
        ],
        'ru': 'Растяжка задней дельты',
        'rs': [
            'Встаньте или сядьте прямо, плечи расслаблены и опущены.',
            'Заведите прямую руку поперёк груди на уровне плеча. Это исходное положение.',
            'Подхватите её другим предплечьем выше локтя и притяните ближе к груди, пока не растянется задняя часть плеча.',
            'Удерживайте 20–30 секунд, не поднимая плечо, затем отпустите и смените сторону.',
        ],
    },
    'stretching_seated_shoulder_flexor_depresor_retractor': {
        't': 'Seated Shoulder Flexor and Retractor Stretch',
        'eq': None, 'm': ['shoulders', 'chest', 'back'], 'p': ['shoulders'],
        'stretch': True,
        'en': [
            'Sit on the floor with the knees bent and place your hands on the floor behind you, fingers pointing away.',
            'Sit tall and let the arms take some of your weight. This is the starting position.',
            'Slide the hands further back and lift the chest so the shoulders draw down and the shoulder blades pull together.',
            'Hold for 20 to 30 seconds, breathing steadily, then walk the hands back in to release.',
        ],
        'ru': 'Растяжка передней поверхности плеч сидя',
        'rs': [
            'Сядьте на пол, согнув колени, и поставьте ладони на пол за спиной пальцами назад.',
            'Сядьте ровно, перенеся часть веса на руки. Это исходное положение.',
            'Отодвиньте ладони дальше назад и приподнимите грудь так, чтобы плечи опустились, а лопатки сошлись.',
            'Удерживайте 20–30 секунд, дыша ровно, затем подвиньте ладони обратно и расслабьтесь.',
        ],
    },
    'cable_rear_delt_row_with_rope': {
        't': 'Cable Rear Delt Row with a Rope',
        'eq': 'cable_machine', 'm': _RD, 'p': ['shoulders'],
        'ru': 'Тяга канатной рукояти к груди на заднюю дельту',
        'rs': [
            'Сядьте в тренажёр для тяги нижнего блока так же, как для обычной тяги к поясу.',
            'Закрепите канатную рукоять и возьмитесь за неё прямым хватом. Руки вытянуты и параллельны полу, локти разведены в стороны.',
            'Держите поясницу прямой и отведите таз назад так, чтобы колени были слегка согнуты. Это исходное положение.',
            'Тяните рукоять к верху груди, чуть ниже шеи, удерживая локти поднятыми и разведёнными в стороны. Продолжайте движение на выдохе, пока локти не уйдут немного за спину. Подсказка: плечи всё время остаются горизонтальными, перпендикулярными корпусу и параллельными полу.',
            'Вернитесь в исходное положение, где руки выпрямлены, а плечи вытянуты вперёд. На этом движении делайте вдох.',
            'Выполните рекомендованное количество повторений.',
        ],
    },
    'dumbbell_bench_seated_press': {
        't': 'Dumbbell Seated Press with Back Support',
        'eq': 'dumbbell', 'm': _DT, 'min': 8,
        'en': [
            'Set a bench upright and sit back against it with a dumbbell resting on each thigh, feet flat on the floor.',
            'Use your thighs to bring the dumbbells up to shoulder height and turn the palms to face forward, elbows under the wrists. This is the starting position.',
            'Press both dumbbells straight overhead as you breathe out until the arms are almost straight, without letting them clash at the top.',
            'Lower them slowly back to shoulder height as you breathe in, keeping the back against the pad so the lower back does not arch.',
            'Repeat for the prescribed amount of repetitions, then bring the dumbbells down onto your thighs before standing.',
        ],
        'ru': 'Жим гантелей сидя с опорой на спинку',
        'rs': [
            'Поставьте скамью вертикально и сядьте, прижав спину к спинке; гантели лежат на бёдрах, стопы на полу.',
            'Помогая себе бёдрами, поднимите гантели на уровень плеч и разверните ладони вперёд; локти под запястьями. Это исходное положение.',
            'На выдохе выжмите обе гантели над головой почти до полного выпрямления рук, не сталкивая их в верхней точке.',
            'На вдохе медленно опустите их на уровень плеч, не отрывая спину от спинки, чтобы поясница не прогибалась.',
            'Выполните рекомендованное количество повторений, затем опустите гантели на бёдра и только потом вставайте.',
        ],
    },
    'dumbbell_rear_delt_row': {
        't': 'Dumbbell Rear Delt Row',
        'eq': 'dumbbell', 'm': _RD, 'p': ['shoulders'],
        'en': [
            'Stand holding a dumbbell in each hand with an overhand grip and hinge forward from the hips, knees slightly bent, until the torso is close to parallel with the floor.',
            'Let the dumbbells hang below your shoulders and flare the elbows out to the sides. This is the starting position.',
            'Row both dumbbells up toward your upper chest with the upper arms staying perpendicular to the torso, breathing out and squeezing the rear shoulders.',
            'Lower them slowly back below your shoulders as you breathe in.',
            'Repeat for the prescribed amount of repetitions; the arms are only hooks here, so do not pull with the biceps.',
        ],
        'ru': 'Тяга гантелей к груди в наклоне на заднюю дельту',
        'rs': [
            'Возьмите по гантели в каждую руку прямым хватом и наклонитесь вперёд от тазобедренных суставов, слегка согнув колени, почти до параллели корпуса с полом.',
            'Гантели висят под плечами, локти разведены в стороны. Это исходное положение.',
            'На выдохе подтяните обе гантели к верху груди, удерживая плечи перпендикулярно корпусу, и сожмите задние дельты.',
            'На вдохе медленно опустите гантели обратно под плечи.',
            'Выполните рекомендованное количество повторений: руки здесь работают только как крючья, тянуть бицепсами не нужно.',
        ],
    },
}
