import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';

import 'package:fitness_app/features/form_check/data/pose_landmark.dart';
import 'package:fitness_app/features/form_check/data/pose_target.dart';

/// Matching a body against a target shape.
///
/// This replaces two rules that were withdrawn for the same reason: both asked
/// whether technique was correct by reading an absolute number out of a 2D
/// projection, and in both cases correct and incorrect execution produced
/// overlapping numbers. The properties below are what make this different --
/// and if any of them stops holding, the approach is back to being a threshold
/// in disguise.

PoseFrame frameFrom(Map<LandmarkType, (double, double)> joints,
        {double likelihood = 0.95}) =>
    PoseFrame(timestampMs: 0, landmarks: {
      for (final e in joints.entries)
        e.key: PoseLandmark(
          type: e.key,
          x: e.value.$1,
          y: e.value.$2,
          likelihood: likelihood,
        ),
    });

/// The target's own joints, optionally moved and resized as a rigid body.
PoseFrame poseOf(PoseTarget t,
    {double dx = 0, double dy = 0, double scale = 1}) {
  return frameFrom({
    for (final e in t.joints.entries)
      e.key: (e.value.$1 * scale + dx, e.value.$2 * scale + dy),
  });
}

/// The target's own pose with every joint nudged in a different direction:
/// what a real body standing correctly looks like, since nobody is exact.
///
/// Derived from [t] rather than written out, deliberately. Two tests below
/// used to carry a hand-copied duplicate of `squatBottomTarget`'s numbers as
/// their "nearly right" fixture, and when that target was re-authored from
/// measurement (`FORMCOACH_SQUAT_BOTTOM_MEASURED_2026-09-01`) both silently
/// became "the OLD shape, nudged" -- so they failed for the right reason but
/// described the wrong thing. A fixture that cannot go stale is the fix.
/// The default nudge is calibrated, not chosen. Four correct reps measured on
/// an S23 score 0.882-0.934 against the re-authored target, i.e. a mean joint
/// offset of 0.042-0.072 normalised body radii. `by: 0.01` on every joint in
/// both axes lands at ~0.074 -- the harsh end of what a real correct rep
/// actually produces. The previous 0.02 sat at ~0.147, two to three times
/// worse than any measured correct repetition, so demanding that it pass was
/// demanding a looseness reality never asks for, at the cost of the
/// discrimination this whole feature exists to provide.
PoseFrame nudgedPoseOf(PoseTarget t, {double by = 0.01}) {
  const dirs = [(1, 1), (-1, 1), (1, -1), (-1, -1), (1, 0), (0, -1)];
  final joints = <LandmarkType, (double, double)>{};
  var i = 0;
  for (final e in t.joints.entries) {
    final d = dirs[i % dirs.length];
    joints[e.key] = (e.value.$1 + d.$1 * by, e.value.$2 + d.$2 * by);
    i++;
  }
  return frameFrom(joints);
}

/// A capture of [t] on a frame shaped [aspectRatio], with optional jitter.
///
/// Since `FORMCOACH_TARGET_ISOTROPIC_2026-09-01` the target's own x is already
/// in the frame's isotropic space, so this copies it rather than converting it.
/// It kept its name and its [aspectRatio] parameter deliberately: the parameter
/// is now what the multi-aspect invariance tests VARY, and a helper that still
/// takes it is the one that can prove the shape no longer depends on it.
PoseFrame isotropicPoseOf(
  PoseTarget t,
  double aspectRatio, {
  double dx = 0,
  double dy = 0,
  double jitterX = 0,
  double jitterY = 0,
  math.Random? rng,
}) {
  final r = rng ?? math.Random(1);
  return PoseFrame(
    timestampMs: 0,
    aspectRatio: aspectRatio,
    landmarks: {
      for (final e in t.joints.entries)
        e.key: PoseLandmark(
          type: e.key,
          x: e.value.$1 +
              dx +
              (jitterX == 0 ? 0 : (r.nextDouble() * 2 - 1) * jitterX),
          y: e.value.$2 +
              dy +
              (jitterY == 0 ? 0 : (r.nextDouble() * 2 - 1) * jitterY),
          likelihood: 0.95,
        ),
    },
  );
}

/// Every shipped target's joints exactly as they stood in the commit before
/// the isotropic migration, generated by reading that commit out of git rather
/// than retyped. `squat.bottom` is absent on purpose -- see the group below.
const preMigrationJoints = <String, Map<LandmarkType, (double, double)>>{
  'squat.top': {
    LandmarkType.leftShoulder: (0.47, 0.26),
    LandmarkType.leftElbow: (0.48, 0.40),
    LandmarkType.leftWrist: (0.49, 0.53),
    LandmarkType.leftHip: (0.50, 0.53),
    LandmarkType.leftKnee: (0.50, 0.74),
    LandmarkType.leftAnkle: (0.49, 0.93),
  },
  'pushup.top': {
    LandmarkType.leftShoulder: (0.35, 0.55),
    LandmarkType.leftElbow: (0.35, 0.68),
    LandmarkType.leftWrist: (0.35, 0.80),
    LandmarkType.leftHip: (0.55, 0.62),
    LandmarkType.leftKnee: (0.72, 0.70),
    LandmarkType.leftAnkle: (0.88, 0.78),
  },
  'pushup.bottom': {
    LandmarkType.leftShoulder: (0.31, 0.72),
    LandmarkType.leftElbow: (0.44, 0.72),
    LandmarkType.leftWrist: (0.35, 0.80),
    LandmarkType.leftHip: (0.52, 0.73),
    LandmarkType.leftKnee: (0.70, 0.75),
    LandmarkType.leftAnkle: (0.88, 0.78),
  },
  'curl.bottom': {
    LandmarkType.leftShoulder: (0.47, 0.30),
    LandmarkType.leftElbow: (0.48, 0.46),
    LandmarkType.leftWrist: (0.49, 0.62),
    LandmarkType.leftHip: (0.50, 0.57),
    LandmarkType.leftKnee: (0.50, 0.77),
    LandmarkType.leftAnkle: (0.49, 0.95),
  },
  'curl.top': {
    LandmarkType.leftShoulder: (0.47, 0.30),
    LandmarkType.leftElbow: (0.48, 0.46),
    LandmarkType.leftWrist: (0.44, 0.31),
    LandmarkType.leftHip: (0.50, 0.57),
    LandmarkType.leftKnee: (0.50, 0.77),
    LandmarkType.leftAnkle: (0.49, 0.95),
  },
  'hinge.top': {
    LandmarkType.leftShoulder: (0.47, 0.26),
    LandmarkType.leftElbow: (0.48, 0.40),
    LandmarkType.leftWrist: (0.49, 0.53),
    LandmarkType.leftHip: (0.50, 0.53),
    LandmarkType.leftKnee: (0.50, 0.74),
    LandmarkType.leftAnkle: (0.49, 0.93),
  },
  'hinge.bottom': {
    LandmarkType.leftShoulder: (0.62, 0.43),
    LandmarkType.leftElbow: (0.62, 0.57),
    LandmarkType.leftWrist: (0.62, 0.70),
    LandmarkType.leftHip: (0.40, 0.58),
    LandmarkType.leftKnee: (0.53, 0.75),
    LandmarkType.leftAnkle: (0.49, 0.93),
  },
  'lunge.top': {
    LandmarkType.leftShoulder: (0.47, 0.26),
    LandmarkType.leftElbow: (0.48, 0.40),
    LandmarkType.leftWrist: (0.49, 0.53),
    LandmarkType.leftHip: (0.50, 0.53),
    LandmarkType.leftKnee: (0.50, 0.74),
    LandmarkType.leftAnkle: (0.49, 0.93),
  },
  'lunge.bottom': {
    LandmarkType.leftShoulder: (0.42, 0.35),
    LandmarkType.leftElbow: (0.43, 0.49),
    LandmarkType.leftWrist: (0.44, 0.62),
    LandmarkType.leftHip: (0.45, 0.62),
    LandmarkType.leftKnee: (0.60, 0.77),
    LandmarkType.leftAnkle: (0.61, 0.95),
  },
  'situp.bottom': {
    LandmarkType.leftShoulder: (0.30, 0.72),
    LandmarkType.leftElbow: (0.22, 0.61),
    LandmarkType.leftWrist: (0.34, 0.57),
    LandmarkType.leftHip: (0.55, 0.75),
    LandmarkType.leftKnee: (0.72, 0.68),
    LandmarkType.leftAnkle: (0.85, 0.78),
  },
  'situp.top': {
    LandmarkType.leftShoulder: (0.36, 0.59),
    LandmarkType.leftElbow: (0.27, 0.49),
    LandmarkType.leftWrist: (0.39, 0.45),
    LandmarkType.leftHip: (0.55, 0.75),
    LandmarkType.leftKnee: (0.72, 0.68),
    LandmarkType.leftAnkle: (0.85, 0.78),
  },
  'overhead_press.bottom': {
    LandmarkType.leftShoulder: (0.47, 0.36),
    LandmarkType.leftElbow: (0.44, 0.50),
    LandmarkType.leftWrist: (0.50, 0.39),
    LandmarkType.leftHip: (0.50, 0.62),
    LandmarkType.leftKnee: (0.50, 0.80),
    LandmarkType.leftAnkle: (0.49, 0.96),
  },
  'overhead_press.top': {
    LandmarkType.leftShoulder: (0.47, 0.36),
    LandmarkType.leftElbow: (0.47, 0.22),
    LandmarkType.leftWrist: (0.47, 0.09),
    LandmarkType.leftHip: (0.50, 0.62),
    LandmarkType.leftKnee: (0.50, 0.80),
    LandmarkType.leftAnkle: (0.49, 0.96),
  },
};

void main() {
  // FORMCOACH_TARGET_ISOTROPIC_2026-09-01. This group used to prove that the
  // score APPLIED an aspect-ratio correction. It now proves the opposite and
  // stronger property: the comparison does not depend on the frame's aspect
  // ratio at all, because target and landmark now live in one space. That is
  // the invariant whose absence let the same target be a different shape on
  // every handset -- measured at 0.1366 normalised radii of drift between a
  // 9:16 and a 3:4 camera, 22.8% of the offset that zeroes a score.
  group('the shape being compared does not depend on the shape of the frame',
      () {
    const frameAspect916 = 9 / 16;

    test('a landmark set that IS the target pose, captured correctly, '
        'scores 1', () {
      final live = isotropicPoseOf(squatBottomTarget, frameAspect916);
      expect(poseMatchScore(live, squatBottomTarget), closeTo(1.0, 1e-9),
          reason: 'this is the best possible match -- if it does not score '
              '1, nothing can ever pass, no matter how correct the form');
    });

    test('a small, realistic perturbation still passes', () {
      final live = isotropicPoseOf(squatBottomTarget, frameAspect916,
          jitterX: 0.02, jitterY: 0.02);
      final score = poseMatchScore(live, squatBottomTarget);
      expect(score, isNotNull);
      expect(score!, greaterThanOrEqualTo(kPoseMatchPassing),
          reason: 'scored ${score.toStringAsFixed(3)} -- a body correctly in '
              'position, captured on a real 9:16 frame, must pass');
    });

    test('standing tall, correctly captured, still fails the bottom target',
        () {
      final live = isotropicPoseOf(squatTopTarget, frameAspect916);
      final score = poseMatchScore(live, squatBottomTarget);
      expect(score, isNotNull);
      expect(score!, lessThan(kPoseMatchPassing),
          reason: 'the fix must not have flattened the discrimination this '
              'feature exists for -- scored ${score.toStringAsFixed(3)}');
    });

    test('translation and scale invariance still hold on a real frame', () {
      final base = isotropicPoseOf(squatBottomTarget, frameAspect916);
      final moved = isotropicPoseOf(squatBottomTarget, frameAspect916,
          dx: 0.05, dy: -0.08);
      expect(poseMatchScore(moved, squatBottomTarget),
          closeTo(poseMatchScore(base, squatBottomTarget)!, 1e-9));
    });

    test('sliding a whole target sideways costs nothing, on every movement',
        () {
      // FORMCOACH_TARGET_FITS_NARROW_FRAME_2026-09-01. Squat, pushup and situp
      // were each moved left by a fixed amount so their DRAWN outline fits a
      // 9:16 phone (see pose_silhouette_test). That edit touched 36 authored
      // numbers, and it is only safe because a rigid translation is invisible
      // to scoring -- `poseMatchScore` centres both poses on their centroid
      // first. The test above proves that for one target; the edit relied on
      // it for six, so it is proven for all of them here rather than assumed
      // to generalise.
      for (final t in allShippedTargets) {
        final base = poseMatchScore(isotropicPoseOf(t, frameAspect916), t)!;
        for (final dx in [-0.05, 0.016, 0.05]) {
          final moved = isotropicPoseOf(t, frameAspect916, dx: dx);
          expect(poseMatchScore(moved, t), closeTo(base, 1e-9),
              reason: '${t.id} changed score when moved $dx sideways');
        }
      }
    });

    test('the same physical pose scores the same on every frame shape', () {
      // The invariant the migration exists for, stated as a test rather than
      // as a claim in a comment. One pose, four plausible cameras.
      //
      // Every shipped target, not a hand-picked seven. The first version of
      // this test listed one phase of each movement, which left the other
      // phase of all seven uncovered -- a target missed by the mechanical
      // multiply would have been anisotropically stretched relative to the
      // rest and gone unnoticed here. Caught in review of this gate.
      for (final t in allShippedTargets) {
        final scores = [
          for (final ar in [9 / 16, 2 / 3, 3 / 4, 1.0])
            poseMatchScore(isotropicPoseOf(t, ar), t)!
        ];
        for (final s in scores) {
          expect(s, closeTo(scores.first, 1e-9),
              reason: '${t.id} scored ${scores.map((v) => v.toStringAsFixed(3))}'
                  ' across 9:16, 2:3, 3:4 and square frames');
        }
      }
    });

    test('a body that is NOT the target still fails on every frame shape', () {
      // The negative half: invariance must not have been bought by flattening
      // the comparison into something that says yes to everything.
      for (final ar in [9 / 16, 2 / 3, 3 / 4, 1.0]) {
        final standing = isotropicPoseOf(squatTopTarget, ar);
        expect(poseMatchScore(standing, squatBottomTarget)!,
            lessThan(kPoseMatchPassing));
      }
    });
  });

  group('the score means what it claims', () {
    test('the target matched exactly scores 1', () {
      expect(poseMatchScore(poseOf(squatBottomTarget), squatBottomTarget),
          closeTo(1.0, 1e-9));
    });

    test('standing somewhere else scores exactly the same', () {
      // Translation invariance. Without it the user would have to stand on a
      // specific spot on the floor, and every step sideways would read as bad
      // technique.
      final moved = poseOf(squatBottomTarget, dx: 0.21, dy: -0.13);
      expect(poseMatchScore(moved, squatBottomTarget), closeTo(1.0, 1e-9));
    });

    test('standing closer or further away scores exactly the same', () {
      // Scale invariance -- the property whose ABSENCE broke the depth rule.
      // Camera distance changed every number that rule compared.
      for (final s in [0.4, 0.75, 1.6, 2.5]) {
        final resized = poseOf(squatBottomTarget, scale: s, dx: 0.1);
        expect(poseMatchScore(resized, squatBottomTarget), closeTo(1.0, 1e-9),
            reason: 'scale $s must not change the verdict');
      }
    });

    test('standing tall does NOT match the bottom of a squat', () {
      // The discriminating case. If this scored high the whole idea is
      // decorative: the top and the bottom of a squat are the two poses the
      // coach most needs to tell apart.
      final score = poseMatchScore(poseOf(squatTopTarget), squatBottomTarget);
      expect(score, isNotNull);
      expect(score!, lessThan(kPoseMatchPassing),
          reason: 'a standing body scored ${score.toStringAsFixed(2)} against '
              'the bottom position');
    });

    test('a genuinely shallow squat FAILS', () {
      // The case that decides whether this feature is worth anything. Operator,
      // on the build that stopped judging: "все повторения правильные даже если
      // я неправильно делаю". Silence was the honest answer while the coach had
      // no target to compare against; it is not an acceptable resting place.
      //
      // Hips well above knees, torso upright — the fault the old depth rule was
      // trying and failing to detect.
      final shallow = frameFrom({
        LandmarkType.leftShoulder: (0.49, 0.36),
        LandmarkType.leftElbow: (0.50, 0.48),
        LandmarkType.leftWrist: (0.51, 0.60),
        LandmarkType.leftHip: (0.48, 0.62),
        LandmarkType.leftKnee: (0.52, 0.75),
        LandmarkType.leftAnkle: (0.49, 0.93),
      });
      final score = poseMatchScore(shallow, squatBottomTarget)!;
      expect(score, lessThan(kPoseMatchPassing),
          reason: 'scored ${score.toStringAsFixed(2)} — a half squat must not '
              'be accepted as a full one');
    });

    test('the passing threshold is not a knife edge', () {
      // A separation this narrow would mean the measure is not really
      // distinguishing the poses, just landing near the line. Both withdrawn
      // rules failed exactly here: correct and incorrect execution differed by
      // less than the noise.
      final good =
          poseMatchScore(nudgedPoseOf(squatBottomTarget), squatBottomTarget)!;
      final bad = poseMatchScore(poseOf(squatTopTarget), squatBottomTarget)!;
      expect(good - bad, greaterThan(0.4),
          reason:
              'good=${good.toStringAsFixed(2)} bad=${bad.toStringAsFixed(2)}'
              ' — the gap between a real rep and a non-rep must be wide');
    });

    test('a push-up does not pass as a squat', () {
      final score = poseMatchScore(poseOf(pushupTopTarget), squatBottomTarget);
      expect(score!, lessThan(kPoseMatchPassing));
    });

    test('a nearly-right squat still passes', () {
      // The threshold has to admit real bodies, which are never exact. Every
      // joint nudged, in different directions.
      final score =
          poseMatchScore(nudgedPoseOf(squatBottomTarget), squatBottomTarget);
      expect(score!, greaterThanOrEqualTo(kPoseMatchPassing),
          reason: 'scored ${score.toStringAsFixed(2)}; a real body that is '
              'clearly in position must not be failed for being human');
    });
  });

  group('it refuses to guess', () {
    test('too few shared joints returns null, not a low score', () {
      // "Your knee is out of shot" and "your form is wrong" are different
      // statements. Reporting the first as the second is the failure this
      // whole feature exists to stop making.
      final partial = frameFrom({
        LandmarkType.leftShoulder: (0.5, 0.5),
        LandmarkType.leftHip: (0.5, 0.7),
      });
      expect(poseMatchScore(partial, squatBottomTarget), isNull);
    });

    test('three joints is still a fragment, not a pose', () {
      final three = frameFrom({
        LandmarkType.leftShoulder: (0.5, 0.5),
        LandmarkType.leftHip: (0.5, 0.7),
        LandmarkType.leftKnee: (0.5, 0.8),
      });
      expect(poseMatchScore(three, squatBottomTarget), isNull,
          reason: 'normalisation can fit any three points onto any other '
              'three well enough to look like a match');
    });

    test('low-confidence joints do not count towards the shape', () {
      final unsure = poseOf(squatBottomTarget);
      final degraded = PoseFrame(
        timestampMs: 0,
        landmarks: {
          for (final e in unsure.landmarks.entries)
            e.key: PoseLandmark(
              type: e.key,
              x: e.value.x,
              y: e.value.y,
              likelihood: 0.2,
            ),
        },
      );
      expect(poseMatchScore(degraded, squatBottomTarget), isNull);
    });

    test('a body collapsed to a point has no shape to compare', () {
      final collapsed = frameFrom({
        for (final k in squatBottomTarget.joints.keys) k: (0.5, 0.5),
      });
      expect(poseMatchScore(collapsed, squatBottomTarget), isNull);
    });
  });

  group('every target is drawable and self-consistent', () {
    test('every target carries enough joints to be scorable at all', () {
      // The constructor cannot assert this — const expressions cannot read
      // Map.length — so it is checked here, across every shipped target. A
      // target with three joints would silently return null forever, which
      // reads on screen as "the coach cannot see you" for a target that is
      // simply malformed.
      for (final t in allShippedTargets) {
        expect(t.joints.length, greaterThanOrEqualTo(4), reason: t.id);
      }
    });

    test('bones only connect joints the target actually has', () {
      for (final t in allShippedTargets) {
        for (final (a, b) in t.bones) {
          expect(t.joints.keys, contains(a), reason: '${t.id} bone start');
          expect(t.joints.keys, contains(b), reason: '${t.id} bone end');
        }
      }
    });

    test('targets sit inside a portrait frame, so they can be drawn', () {
      // Scoring normalises these away, but the same numbers are painted on
      // screen as the outline to stand in.
      for (final t in allShippedTargets) {
        for (final j in t.joints.values) {
          expect(j.$1, inInclusiveRange(0.0, 1.0), reason: t.id);
          expect(j.$2, inInclusiveRange(0.0, 1.0), reason: t.id);
        }
      }
    });

    test('the two squat phases are genuinely different shapes', () {
      // Guards the targets themselves, not the maths: if someone edits these
      // numbers until the two phases converge, rep detection against them
      // becomes meaningless and nothing else would notice.
      final score = poseMatchScore(poseOf(squatTopTarget), squatBottomTarget)!;
      expect(score, lessThan(0.6),
          reason: 'top vs bottom scored ${score.toStringAsFixed(2)}');
    });

    test('EVERY movement has two genuinely different phases', () {
      // The same guard, generalised — and the one that decides whether a
      // movement can live in this representation at all.
      //
      // `poseMatchScore` normalises away position and size, so a movement
      // whose two ends differ ONLY by where the body is cannot be expressed
      // here: both phases normalise to one shape and every attempt scores the
      // same, including a rep never performed. That is exactly why
      // `calf_raise` is absent from `poseTargetsByTag` despite the catalogue
      // tagging 17 exercises with it — a pure vertical translation on an
      // unchanging skeleton. Adding it would fail here, which is the point.
      for (final e in poseTargetsByTag.entries) {
        final (top, bottom) = e.value;
        final score = poseMatchScore(poseOf(top), bottom);
        expect(score, isNotNull, reason: '${e.key}: phases are not comparable');
        expect(score!, lessThan(0.6),
            reason: '${e.key}: top vs bottom scored '
                '${score.toStringAsFixed(2)} — the two ends are the same '
                'shape, so this movement cannot be judged by matching');
      }
    });

    test('limbs keep their length between the two phases', () {
      // `pushupBottomTarget`'s comment states the rule and nothing enforced
      // it: a limb that changes length mid-demonstration reads as a glitch
      // rather than as a movement, because `lerpPoseTarget` interpolates the
      // ENDPOINTS and lets the segment stretch on the way through.
      //
      // 15% is loose on purpose. These are drawn figures, and a side view
      // genuinely foreshortens a limb that rotates towards the camera; the
      // bound is here to catch a typo'd coordinate, not to impose rigid-body
      // kinematics on a stick figure.
      //
      // The exception list is a FINDING, not housekeeping, and it changed
      // twice on 2026-09-01.
      //
      // `squat` came OFF it. It was excluded because its thigh measured 0.210
      // at the top and 0.150 at the bottom -- 28% shorter, in a movement that
      // happens in the sagittal plane where a true side view foreshortens
      // nothing. Re-authoring `squatBottomTarget` from measurement closed that
      // (`FORMCOACH_SQUAT_BOTTOM_MEASURED_2026-09-01`); the worst segment is now
      // 9.7%, comfortably inside the bound. The note said new numbers picked to
      // satisfy a test would trade a measured flaw for an unmeasured one --
      // which is exactly why the replacement came off a device rather than out
      // of an editor.
      //
      // `pushup`, `hinge` and `situp` went ON it, and they were not introduced
      // that day. They were INVISIBLE until it: before
      // `FORMCOACH_TARGET_ISOTROPIC_2026-09-01` these coordinates mixed a
      // width-normalised x with a height-normalised y, so a "length" computed
      // from them was not a length and this assertion was measuring a quantity
      // with no physical meaning. Now that x and y share a unit the numbers are
      // real, and three targets stretch a limb between their phases: pushup
      // 33.8% (shoulder-elbow), hinge 22.7% (shoulder-hip), situp 16.9%
      // (shoulder-hip).
      //
      // Deliberately not fixed here. GPT-PM's instruction for the migration
      // gate was explicit -- keep it mechanical, do not mix target redesign in
      // -- and correcting three movements' geometry is redesign, which belongs
      // with the same device measurement the squat got rather than with a
      // coordinate conversion. Left failing-by-exception so it stays visible.
      const knownDeviation = {'pushup', 'hinge', 'situp'};
      for (final e in poseTargetsByTag.entries) {
        if (knownDeviation.contains(e.key)) continue;
        final (top, bottom) = e.value;
        for (final (a, b) in top.bones) {
          final ta = top.joints[a], tb = top.joints[b];
          final ba = bottom.joints[a], bb = bottom.joints[b];
          if (ta == null || tb == null || ba == null || bb == null) continue;
          double len((double, double) p, (double, double) q) =>
              math.sqrt(math.pow(p.$1 - q.$1, 2) + math.pow(p.$2 - q.$2, 2));
          final lt = len(ta, tb), lb = len(ba, bb);
          final longer = math.max(lt, lb);
          if (longer < 1e-9) continue;
          expect((lt - lb).abs() / longer, lessThan(0.15),
              reason: '${e.key}: $a-$b is ${lt.toStringAsFixed(3)} at the top '
                  'and ${lb.toStringAsFixed(3)} at the bottom');
        }
      }
    });
  });

  group('the figure reads as a body', () {
    // Operator, looking at the shipped outline on his phone: *"человеческий
    // силует привратился а закорючку"*. He was right — six joints and five
    // lines is geometrically a person and visually a zigzag. The instruction
    // the whole feature rests on is "stand inside this shape", which needs the
    // shape to be recognisable at a glance, in motion, from across a room.
    //
    // The head is DERIVED and DRAWN, never scored. From the side one arm and
    // one leg are behind the body, so the detector's estimates for them are
    // guesses; comparing against a guess is how a target starts failing people
    // for standing at a slightly different angle.

    test('every drawable target has a head', () {
      for (final t in [
        squatTopTarget,
        squatBottomTarget,
        pushupTopTarget,
        pushupBottomTarget
      ]) {
        expect(t.head, isNotNull, reason: t.id);
      }
    });

    test('the head is above the shoulder, along the torso', () {
      // Not "above" in screen terms — along the hip-to-shoulder line. At the
      // bottom of a squat the torso inclines about 45 degrees, and a head
      // pinned to screen-vertical would float off the chest into the air.
      final head = squatBottomTarget.head!;
      final sh = squatBottomTarget.joints[LandmarkType.leftShoulder]!;
      final hip = squatBottomTarget.joints[LandmarkType.leftHip]!;
      // Same direction as hip -> shoulder, continued past the shoulder.
      final tx = sh.$1 - hip.$1, ty = sh.$2 - hip.$2;
      final hx = head.$1 - sh.$1, hy = head.$2 - sh.$2;
      final cross = tx * hy - ty * hx;
      expect(cross.abs(), lessThan(1e-9), reason: 'head is off the torso line');
      expect(tx * hx + ty * hy, greaterThan(0),
          reason: 'head is on the hip side of the shoulder');
    });

    test('the head scales with the body, and stays a head', () {
      for (final t in [squatTopTarget, squatBottomTarget]) {
        final sh = t.joints[LandmarkType.leftShoulder]!;
        final hip = t.joints[LandmarkType.leftHip]!;
        final torso = math
            .sqrt(math.pow(sh.$1 - hip.$1, 2) + math.pow(sh.$2 - hip.$2, 2));
        final r = t.head!.$3;
        expect(r, greaterThan(torso * 0.10),
            reason: '${t.id}: too small to see');
        expect(r, lessThan(torso * 0.30),
            reason: '${t.id}: a head that big is a balloon');
      }
    });

    test('a target with no torso draws no head rather than guessing', () {
      const armOnly = PoseTarget(
        id: 'test.arm',
        joints: {
          LandmarkType.leftElbow: (0.5, 0.4),
          LandmarkType.leftWrist: (0.5, 0.6),
        },
        bones: [(LandmarkType.leftElbow, LandmarkType.leftWrist)],
      );
      expect(armOnly.head, isNull);
    });

    test('the head is not part of what gets scored', () {
      // The guard that keeps drawing and measuring separate. If a head ever
      // reached `joints`, `poseMatchScore` would start comparing against a
      // landmark no detector reports.
      for (final t in [squatTopTarget, squatBottomTarget, pushupTopTarget]) {
        expect(t.joints.containsKey(LandmarkType.nose), isFalse, reason: t.id);
      }
    });
  });

  group('the demonstration', () {
    // Operator: *"лучше добавить анимацию как правильно надо делать"*. A single
    // outline says where to arrive and not how to get there, and for a squat
    // the how is the whole difference between the shape that scores and the
    // shape that does not.
    //
    // The motion lives here rather than in a widget test: what a widget test
    // can prove is that the page draws a demonstration instead of a target,
    // and what it cannot easily prove is that the drawing MOVES. This can.

    test('the ends of the movement are the authored poses', () {
      for (final (from, to) in [
        (squatTopTarget, squatBottomTarget),
        (pushupTopTarget, pushupBottomTarget),
      ]) {
        expect(lerpPoseTarget(from, to, 0).joints, equals(from.joints));
        expect(lerpPoseTarget(from, to, 1).joints, equals(to.joints));
      }
    });

    test('a limb never changes length on the way through', () {
      // The defect this replaced a straight-line lerp for. Every joint moving
      // independently along its own straight line does not keep the bone
      // between two of them the same length: the shipped squat's thigh is
      // 0.210 at both ends and measured 0.134 at t=0.5 — 36% shorter — so the
      // figure demonstrating the movement pulled its legs in and pushed them
      // back out once per loop.
      //
      // Nothing was measuring it. "limbs keep their length between the two
      // phases", above, compares the two AUTHORED poses and passed correctly;
      // the stretch lived only in the frames between them, and nothing drew
      // one until `test/golden/form_coach_golden_test.dart`.
      //
      // The bound is the two authored lengths themselves, with room for
      // arithmetic: a bone may interpolate between its own ends, and may not
      // leave them. Every shipped movement, not just the squat — this is a
      // property of the interpolation, and a per-movement exception list here
      // would only ever be hiding the same defect somewhere else.
      double len((double, double) p, (double, double) q) =>
          math.sqrt(math.pow(p.$1 - q.$1, 2) + math.pow(p.$2 - q.$2, 2));

      for (final e in poseTargetsByTag.entries) {
        final (top, bottom) = e.value;
        for (final (a, b) in top.bones) {
          final ta = top.joints[a], tb = top.joints[b];
          final ba = bottom.joints[a], bb = bottom.joints[b];
          if (ta == null || tb == null || ba == null || bb == null) continue;
          final ends = [len(ta, tb), len(ba, bb)];
          final low = ends.reduce(math.min) - 1e-9;
          final high = ends.reduce(math.max) + 1e-9;
          for (var i = 0; i <= 20; i++) {
            final mid = lerpPoseTarget(top, bottom, i / 20);
            final l = len(mid.joints[a]!, mid.joints[b]!);
            expect(l, inInclusiveRange(low, high),
                reason: '${e.key}: $a-$b is ${l.toStringAsFixed(3)} at '
                    't=${i / 20}, outside its own ends '
                    '${ends.map((v) => v.toStringAsFixed(3)).join('..')}');
          }
        }
      }
    });

    test('and the movement turns over its planted foot', () {
      // The other half of the same choice. Keeping bone lengths is not enough
      // on its own: a chain is anchored somewhere, and anchoring it at the
      // joint the bone list happens to start from — the shoulder — would hold
      // the shoulder still and slide the feet along the floor to meet it.
      //
      // The squat's ankle is authored identically in both phases, so the
      // anchor rule ("the joint that moves least") has an unambiguous answer
      // here and the foot must not move at all.
      for (var i = 0; i <= 20; i++) {
        final mid = lerpPoseTarget(squatTopTarget, squatBottomTarget, i / 20);
        expect(mid.joints[LandmarkType.leftAnkle],
            squatTopTarget.joints[LandmarkType.leftAnkle],
            reason: 'the foot slid at t=${i / 20}');
      }
      // Positive control: something else in the same pose genuinely did move,
      // so the assertion above is not passing over a frozen figure.
      final mid = lerpPoseTarget(squatTopTarget, squatBottomTarget, 0.5);
      expect(mid.joints[LandmarkType.leftHip],
          isNot(squatTopTarget.joints[LandmarkType.leftHip]));
    });

    test('the middle is half way through the movement, not near either end',
        () {
      // What replaced the old "exactly the arithmetic mean" assertion, which
      // was a restatement of the implementation rather than a claim about the
      // movement — and which the fix above necessarily breaks, since a joint
      // swinging on a bone travels an arc and an arc does not pass through the
      // midpoint of its own chord.
      //
      // The band is wide because that is what the geometry allows: for a pure
      // rotation through an angle t, the chord from the start at half way is
      // sin(t/4)/sin(t/2) of the full chord — 0.5 for a small turn, rising to
      // about 0.54 for a half circle. Anything outside 0.3..0.7 is not a half
      // way pose.
      double len((double, double) p, (double, double) q) =>
          math.sqrt(math.pow(p.$1 - q.$1, 2) + math.pow(p.$2 - q.$2, 2));
      final mid = lerpPoseTarget(squatTopTarget, squatBottomTarget, 0.5);
      expect(mid.joints, isNotEmpty);
      var moved = 0;
      mid.joints.forEach((k, m) {
        final a = squatTopTarget.joints[k]!;
        final b = squatBottomTarget.joints[k]!;
        final travel = len(a, b);
        if (travel < 1e-6) return; // the planted foot, asserted above
        moved++;
        expect(len(a, m) / travel, inInclusiveRange(0.3, 0.7), reason: '$k');
      });
      expect(moved, greaterThan(3),
          reason: 'positive control: most of the body moves in a squat');
    });

    test('a limb the straight line collapses keeps pointing where it did', () {
      // The direction comes from the straight-line pose, so the one input that
      // has no direction in it is a frame where that pose puts both ends of a
      // bone in the same place. Constructed: a knee that swings from one side
      // of the hip to the other, straight through it, which is a pose an
      // author can write and no shipped target happens to contain today.
      //
      // A property that holds only because no current input exercises it is
      // not one anybody can rely on — and the alternative here is a division
      // by zero that reaches the screen as a limb at NaN, drawing nothing at
      // all for one frame of every loop.
      const from = PoseTarget(
        id: 'test.collapse.from',
        joints: {
          LandmarkType.leftHip: (0.30, 0.50),
          LandmarkType.leftKnee: (0.20, 0.50),
        },
        bones: [(LandmarkType.leftHip, LandmarkType.leftKnee)],
      );
      const to = PoseTarget(
        id: 'test.collapse.to',
        joints: {
          LandmarkType.leftHip: (0.30, 0.50),
          LandmarkType.leftKnee: (0.40, 0.50),
        },
        bones: [(LandmarkType.leftHip, LandmarkType.leftKnee)],
      );
      // At half way the straight line puts the knee exactly on the hip.
      final mid = lerpPoseTarget(from, to, 0.5).joints[LandmarkType.leftKnee]!;
      expect(mid.$1, closeTo(0.20, 1e-9), reason: 'the length it started with');
      expect(mid.$2, closeTo(0.50, 1e-9));
      // And every other frame is finite, which is the failure this guards.
      for (var i = 0; i <= 20; i++) {
        final knee = lerpPoseTarget(from, to, i / 20).joints[
            LandmarkType.leftKnee]!;
        expect(knee.$1.isFinite && knee.$2.isFinite, isTrue,
            reason: 'NaN knee at t=${i / 20}');
      }
    });

    test('a joint no bone reaches still travels', () {
      // The leftover branch: nothing constrains its length or its angle, so a
      // straight line is the only honest answer for it. Reachable from any
      // target whose `bones` do not name every joint in `joints`.
      const from = PoseTarget(
        id: 'test.orphan.from',
        joints: {
          LandmarkType.leftHip: (0.30, 0.50),
          LandmarkType.leftWrist: (0.10, 0.10),
        },
        bones: [],
      );
      const to = PoseTarget(
        id: 'test.orphan.to',
        joints: {
          LandmarkType.leftHip: (0.30, 0.50),
          LandmarkType.leftWrist: (0.30, 0.30),
        },
        bones: [],
      );
      expect(lerpPoseTarget(from, to, 0.5).joints[LandmarkType.leftWrist],
          (0.20, 0.20));
    });

    test('it actually moves — every frame is a different pose', () {
      // A demonstration that renders one frozen frame is the bug this feature
      // would most plausibly ship with, and it looks exactly like a static
      // outline.
      final seen = <String>{};
      for (var i = 0; i <= 10; i++) {
        final p = lerpPoseTarget(squatTopTarget, squatBottomTarget, i / 10);
        seen.add(p.joints.entries
            .map((e) => '${e.key}:${e.value.$1},${e.value.$2}')
            .join('|'));
      }
      expect(seen, hasLength(11));
    });

    test('overshoot is clamped to the ends of the movement', () {
      // An eased or springy curve can pass either end. Limbs must not fly
      // past the bottom of the squat because the animation overshot.
      expect(lerpPoseTarget(squatTopTarget, squatBottomTarget, 1.4).joints,
          equals(squatBottomTarget.joints));
      expect(lerpPoseTarget(squatTopTarget, squatBottomTarget, -0.3).joints,
          equals(squatTopTarget.joints));
    });

    test('a joint missing from either end is dropped, along with its bone', () {
      // A joint that appeared halfway through would pop into existence
      // mid-movement, and a bone drawn to a joint that is not there throws.
      const partial = PoseTarget(
        id: 'test.partial',
        joints: {
          LandmarkType.leftShoulder: (0.5, 0.3),
          LandmarkType.leftHip: (0.5, 0.5),
        },
        bones: [
          (LandmarkType.leftShoulder, LandmarkType.leftHip),
          (LandmarkType.leftHip, LandmarkType.leftKnee),
        ],
      );
      final mid = lerpPoseTarget(partial, squatBottomTarget, 0.5);

      expect(mid.joints.keys,
          unorderedEquals([LandmarkType.leftShoulder, LandmarkType.leftHip]));
      expect(mid.bones, hasLength(1),
          reason: 'the hip-to-knee bone has no knee to reach');
      for (final (a, b) in mid.bones) {
        expect(mid.joints.containsKey(a), isTrue);
        expect(mid.joints.containsKey(b), isTrue);
      }
    });

    test('the push-up ends are different shapes, and both are drawable', () {
      final score =
          poseMatchScore(poseOf(pushupTopTarget), pushupBottomTarget)!;
      expect(score, lessThan(0.8),
          reason: 'top vs bottom scored ${score.toStringAsFixed(2)} — a '
              'demonstration between two near-identical poses shows nothing');
      for (final j in pushupBottomTarget.joints.values) {
        expect(j.$1, inInclusiveRange(0.0, 1.0));
        expect(j.$2, inInclusiveRange(0.0, 1.0));
      }
    });
  });

  // FORMCOACH_TARGET_MIRROR_2026-09-01. Operator, on a build whose silhouette
  // was finally centred and whose reps were counted correctly: "не дошли до
  // силуэта по прежнему осталось", then "на каждом без исключений".
  group('which side the lifter turns to the camera is not a technique error',
      () {
    const frameAspect = 2 / 3;

    /// The same pose executed facing the other way: x reflected about the
    /// pose's own midline, y untouched.
    PoseFrame mirroredPoseOf(PoseTarget t, double aspectRatio) {
      final xs = [for (final j in t.joints.values) j.$1];
      final axis = xs.reduce((a, b) => a + b) / xs.length;
      return PoseFrame(
        timestampMs: 0,
        aspectRatio: aspectRatio,
        landmarks: {
          for (final e in t.joints.entries)
            e.key: PoseLandmark(
              type: e.key,
              x: 2 * axis - e.value.$1,
              y: e.value.$2,
              likelihood: 0.95,
            ),
        },
      );
    }

    test('a perfect squat filmed from the other side still scores 1', () {
      final live = mirroredPoseOf(squatBottomTarget, frameAspect);
      final score = poseMatchScore(live, squatBottomTarget)!;
      expect(score, closeTo(1.0, 1e-9),
          reason: 'scored ${score.toStringAsFixed(2)} — before the mirror was '
              'allowed this was 0.21, so standing the wrong way round made '
              'kPoseMatchPassing unreachable at any skill level');
    });

    test('every shipped target is reachable from both sides', () {
      for (final t in [
        squatBottomTarget,
        pushupTopTarget,
        pushupBottomTarget,
        curlBottomTarget,
        curlTopTarget,
      ]) {
        final score = poseMatchScore(mirroredPoseOf(t, frameAspect), t)!;
        expect(score, greaterThan(kPoseMatchPassing),
            reason: '${t.id} scored ${score.toStringAsFixed(2)} mirrored');
      }
    });

    test('the mirror does not make a different movement pass', () {
      // Depth is carried entirely by y, which mirroring leaves alone, so the
      // leniency this adds must not reach across two genuinely different
      // shapes.
      final standing = poseMatchScore(
        mirroredPoseOf(curlBottomTarget, frameAspect),
        squatBottomTarget,
      )!;
      expect(standing, lessThan(kPoseMatchPassing),
          reason: 'standing tall scored ${standing.toStringAsFixed(2)} '
              'against the squat target');
    });
  });

  // FORMCOACH_SQUAT_BOTTOM_MEASURED_2026-09-01. The acceptance set GPT-PM
  // required before the re-authored squat target could close. Proving only the
  // positive half would reproduce the old defect in the other direction -- a
  // coach that calls everything clean, which the operator already rejected
  // once: "все повторения правильные даже если я неправильно делаю".
  group('the re-authored squat bottom, against real device measurements', () {
    // The deepest frame of each of four correct, below-parallel repetitions,
    // logged raw off an S23 at aspect 2:3. NOT synthesised from the target --
    // deriving fixtures from the target's own joints is the circularity that
    // hid every earlier defect in this file.
    const measuredDeepReps = <Map<LandmarkType, (double, double)>>[
      {
        LandmarkType.leftShoulder: (0.417, 0.535),
        LandmarkType.leftElbow: (0.446, 0.678),
        LandmarkType.leftWrist: (0.495, 0.713),
        LandmarkType.leftHip: (0.238, 0.707),
        LandmarkType.leftKnee: (0.440, 0.683),
        LandmarkType.leftAnkle: (0.383, 0.877),
      },
      {
        LandmarkType.leftShoulder: (0.389, 0.557),
        LandmarkType.leftElbow: (0.451, 0.685),
        LandmarkType.leftWrist: (0.527, 0.643),
        LandmarkType.leftHip: (0.230, 0.744),
        LandmarkType.leftKnee: (0.422, 0.689),
        LandmarkType.leftAnkle: (0.366, 0.882),
      },
      {
        LandmarkType.leftShoulder: (0.406, 0.563),
        LandmarkType.leftElbow: (0.444, 0.708),
        LandmarkType.leftWrist: (0.507, 0.729),
        LandmarkType.leftHip: (0.240, 0.739),
        LandmarkType.leftKnee: (0.435, 0.697),
        LandmarkType.leftAnkle: (0.367, 0.883),
      },
      {
        LandmarkType.leftShoulder: (0.399, 0.541),
        LandmarkType.leftElbow: (0.459, 0.676),
        LandmarkType.leftWrist: (0.521, 0.686),
        LandmarkType.leftHip: (0.243, 0.738),
        LandmarkType.leftKnee: (0.424, 0.680),
        LandmarkType.leftAnkle: (0.363, 0.881),
      },
    ];

    const deviceAspect = 2 / 3;

    PoseFrame frameOf(Map<LandmarkType, (double, double)> joints) => PoseFrame(
          timestampMs: 0,
          aspectRatio: deviceAspect,
          landmarks: {
            for (final e in joints.entries)
              e.key: PoseLandmark(
                type: e.key,
                x: e.value.$1,
                y: e.value.$2,
                likelihood: 0.95,
              ),
          },
        );

    /// The same pose executed facing the other way.
    Map<LandmarkType, (double, double)> mirror(
        Map<LandmarkType, (double, double)> j) {
      final axis =
          j.values.map((p) => p.$1).reduce((a, b) => a + b) / j.length;
      return {
        for (final e in j.entries) e.key: (2 * axis - e.value.$1, e.value.$2),
      };
    }

    test('every measured correct rep passes', () {
      for (var i = 0; i < measuredDeepReps.length; i++) {
        final s =
            poseMatchScore(frameOf(measuredDeepReps[i]), squatBottomTarget)!;
        expect(s, greaterThan(kPoseMatchPassing),
            reason: 'rep $i scored ${s.toStringAsFixed(3)}; against the old '
                'target these same four frames scored '
                '0.257 / 0.092 / 0.162 / 0.191');
      }
    });

    test('the fixtures really are deep reps, not a flattering sample', () {
      // y grows downward, so a hip below the knee is a below-parallel squat.
      for (final rep in measuredDeepReps) {
        expect(rep[LandmarkType.leftHip]!.$2,
            greaterThan(rep[LandmarkType.leftKnee]!.$2));
      }
    });

    test('a shallow squat still fails', () {
      // The same rep stopped short: hip and shoulder lifted together so the
      // torso keeps its shape and only DEPTH is on trial.
      for (final rep in measuredDeepReps) {
        final hip = rep[LandmarkType.leftHip]!;
        final knee = rep[LandmarkType.leftKnee]!;
        final lift = (knee.$2 - hip.$2).abs() + 0.09;
        final shoulder = rep[LandmarkType.leftShoulder]!;
        final shallow = {
          ...rep,
          LandmarkType.leftHip: (hip.$1, hip.$2 - lift),
          LandmarkType.leftShoulder: (shoulder.$1, shoulder.$2 - lift),
        };
        final s = poseMatchScore(frameOf(shallow), squatBottomTarget)!;
        expect(s, lessThan(kPoseMatchPassing),
            reason: 'a shallow rep scored ${s.toStringAsFixed(3)}');
      }
    });

    test('standing tall still fails', () {
      final s = poseMatchScore(
          isotropicPoseOf(squatTopTarget, deviceAspect), squatBottomTarget)!;
      expect(s, lessThan(kPoseMatchPassing),
          reason: 'standing scored ${s.toStringAsFixed(3)}');
    });

    test('the same rep filmed from the other side scores the same', () {
      for (final rep in measuredDeepReps) {
        final direct = poseMatchScore(frameOf(rep), squatBottomTarget)!;
        final flipped =
            poseMatchScore(frameOf(mirror(rep)), squatBottomTarget)!;
        expect(flipped, closeTo(direct, 1e-9));
      }
    });

    test('moving the wrist a long way changes nothing', () {
      // What `unscoredJoints` is for: drawn, not judged.
      for (final rep in measuredDeepReps) {
        final before = poseMatchScore(frameOf(rep), squatBottomTarget)!;
        final wrist = rep[LandmarkType.leftWrist]!;
        final moved = {
          ...rep,
          LandmarkType.leftWrist: (wrist.$1 + 0.25, wrist.$2 - 0.30),
        };
        expect(poseMatchScore(frameOf(moved), squatBottomTarget)!,
            closeTo(before, 1e-9));
      }
    });

    test('moving a scored joint the same distance does change it', () {
      // Negative control for the test above: the exclusion has to be specific
      // to the wrist, not a scorer that quietly stopped reacting to anything.
      for (final rep in measuredDeepReps) {
        final before = poseMatchScore(frameOf(rep), squatBottomTarget)!;
        final knee = rep[LandmarkType.leftKnee]!;
        final moved = {
          ...rep,
          LandmarkType.leftKnee: (knee.$1 + 0.25, knee.$2 - 0.30),
        };
        final after = poseMatchScore(frameOf(moved), squatBottomTarget)!;
        expect(after, lessThan(kPoseMatchPassing));
        expect(after, lessThan(before - 0.2));
      }
    });

    test('the pass mark was not relaxed to make this work', () {
      expect(kPoseMatchPassing, 0.80);
    });

    test('the wrist is still drawn, only unjudged', () {
      expect(
          squatBottomTarget.joints.containsKey(LandmarkType.leftWrist), isTrue);
      expect(
          squatBottomTarget.bones.any((b) =>
              b.$1 == LandmarkType.leftWrist || b.$2 == LandmarkType.leftWrist),
          isTrue);
      expect(
          squatBottomTarget.unscoredJoints, contains(LandmarkType.leftWrist));
    });

    test('where the hands are held does not change the score at all', () {
      // FORMCOACH_SQUAT_ARMS_INVARIANT_2026-09-01. The operator, on the device,
      // minutes after the target was re-authored: a rep counted and the avatar
      // glowed green ONLY with the arms held forward; tucked at the sides it
      // failed with the same cue. Reproduced here by changing the DIRECTION of
      // the arms while taking each limb's length from that same frame, so
      // anatomy is held constant and only placement moves.
      //
      // GPT-PM required this be asserted as an equality rather than as "both
      // pass": two scores either side of the line would satisfy the weaker
      // assertion while leaving the coach sensitive to a degree of freedom that
      // has nothing to do with squatting.
      for (final rep in measuredDeepReps) {
        final shoulder = rep[LandmarkType.leftShoulder]!;
        final elbow = rep[LandmarkType.leftElbow]!;
        final wrist = rep[LandmarkType.leftWrist]!;
        final upper = math.sqrt(math.pow(elbow.$1 - shoulder.$1, 2) +
            math.pow(elbow.$2 - shoulder.$2, 2));
        final fore = math.sqrt(math.pow(wrist.$1 - elbow.$1, 2) +
            math.pow(wrist.$2 - elbow.$2, 2));
        final tucked = {
          ...rep,
          LandmarkType.leftElbow: (shoulder.$1, shoulder.$2 + upper),
          LandmarkType.leftWrist: (shoulder.$1, shoulder.$2 + upper + fore),
        };

        final forward = poseMatchScore(frameOf(rep), squatBottomTarget)!;
        final down = poseMatchScore(frameOf(tucked), squatBottomTarget)!;
        expect(down, closeTo(forward, 1e-9),
            reason: 'arms forward ${forward.toStringAsFixed(3)} vs arms down '
                '${down.toStringAsFixed(3)}; before the elbow was excluded '
                'these were 0.891 and 0.772, i.e. pass and fail');
        expect(forward, greaterThan(kPoseMatchPassing));
      }
    });

    test('the scored set is exactly shoulder, hip, knee and ankle', () {
      // Named explicitly so a future edit to `unscoredJoints` has to confront
      // the four-joint minimum below rather than discover it in production.
      final scored = squatBottomTarget.joints.keys
          .where((j) => !squatBottomTarget.unscoredJoints.contains(j))
          .toSet();
      expect(
          scored,
          unorderedEquals([
            LandmarkType.leftShoulder,
            LandmarkType.leftHip,
            LandmarkType.leftKnee,
            LandmarkType.leftAnkle,
          ]));
    });

    test('losing any one scored joint yields no answer, never a low score', () {
      // Four scored joints is exactly `poseMatchScore`'s minimum, so the squat
      // now has no slack: GPT-PM chose to keep that conservative failure mode
      // (option (a)) rather than relax the minimum to three, because "cannot
      // tell" must never be reported as "bad technique". This asserts the
      // consequence rather than leaving it implicit.
      for (final missing in [
        LandmarkType.leftShoulder,
        LandmarkType.leftHip,
        LandmarkType.leftKnee,
        LandmarkType.leftAnkle,
      ]) {
        final rep = Map.of(measuredDeepReps.first)..remove(missing);
        expect(poseMatchScore(frameOf(rep), squatBottomTarget), isNull,
            reason: 'dropping ${missing.name} must produce no score');
      }
      // ...while losing an UNSCORED joint costs nothing.
      for (final missing in [
        LandmarkType.leftElbow,
        LandmarkType.leftWrist,
      ]) {
        final rep = Map.of(measuredDeepReps.first)..remove(missing);
        expect(poseMatchScore(frameOf(rep), squatBottomTarget), isNotNull,
            reason: '${missing.name} is drawn, not judged');
      }
    });

    test('the re-authored target is an anatomically possible body', () {
      // The check that would have caught the original defect, in the space the
      // joints are actually compared in.
      // No aspect factor: since FORMCOACH_TARGET_ISOTROPIC_2026-09-01 these
      // ARE lengths, in units of frame height, on any device.
      double len(LandmarkType a, LandmarkType b) {
        final p = squatBottomTarget.joints[a]!;
        final q = squatBottomTarget.joints[b]!;
        final dx = p.$1 - q.$1;
        final dy = p.$2 - q.$2;
        return math.sqrt(dx * dx + dy * dy);
      }

      final thigh = len(LandmarkType.leftHip, LandmarkType.leftKnee);
      final shin = len(LandmarkType.leftKnee, LandmarkType.leftAnkle);
      final torso = len(LandmarkType.leftShoulder, LandmarkType.leftHip);
      expect(thigh / shin, closeTo(1.0, 0.15),
          reason: 'the old target was 0.54 here, where a person is 1.00');
      expect(torso / thigh, closeTo(1.18, 0.25),
          reason: 'the old target was 2.29 here, where a person is 1.18');
    });
  });

  group('the migration itself, pinned against the coordinates it replaced', () {
    // FORMCOACH_TARGET_ISOTROPIC_2026-09-01, and the one group in this file
    // whose fixture does NOT come from the target under test.
    //
    // Everything else here builds its "live" pose out of the very target it
    // then scores, which is the right shape for asking "does the comparison
    // behave" but cannot answer "were the authored numbers actually
    // converted". A target skipped by the multiply would keep scoring 1.0
    // against itself on every frame shape, so the aspect-invariance group
    // above would stay green while that target sat in the old space, silently
    // 1.5x too wide. Caught in review of this gate, not by the suite.
    //
    // So the pre-migration coordinates are pinned here, read out of git rather
    // than retyped: a golden table typed by the same hand that made the change
    // tends to agree with it. The relation asserted is the whole migration in
    // one line -- x_new = x_old * 2/3, then minus the shift that pulled three
    // movements inside a 9:16 frame.
    //
    // `squat.bottom` is deliberately absent: it was re-authored from device
    // measurement in the gate before this one, already in the new space, so it
    // never went through the multiply and pinning it here would assert the
    // opposite of what happened.

    /// How far each movement was slid left, after the conversion, so its drawn
    /// outline fits the narrowest frame. Zero for everything else.
    const shift = {
      'squat.top': 0.016,
      'pushup.top': 0.050,
      'pushup.bottom': 0.050,
      'situp.top': 0.048,
      'situp.bottom': 0.048,
    };

    double round3(double v) => (v * 1000).round() / 1000;

    test('every mechanically converted joint is its old value times 2/3', () {
      var checked = 0;
      for (final target in allShippedTargets) {
        final old = preMigrationJoints[target.id];
        if (old == null) continue;
        for (final entry in target.joints.entries) {
          final before = old[entry.key];
          expect(before, isNotNull,
              reason: '${target.id} has a ${entry.key.name} that the '
                  'pre-migration file did not');
          final want =
              round3(round3(before!.$1 * 2 / 3) - (shift[target.id] ?? 0.0));
          expect(entry.value.$1, closeTo(want, 1e-9),
              reason: '${target.id} ${entry.key.name}: ${before.$1} became '
                  '${entry.value.$1}, but ${before.$1} * 2/3'
                  '${shift[target.id] == null ? '' : ' - ${shift[target.id]}'} '
                  'is $want');
          checked++;
        }
      }
      expect(checked, 78,
          reason: 'the table covers 13 targets of 6 joints; checking $checked '
              'means a target or a joint went missing');
    });

    test('and y was left alone -- this was a one-axis change', () {
      // The other half of "mechanical". If y had moved too, the migration
      // would have been a redesign wearing a migration's name.
      for (final target in allShippedTargets) {
        final old = preMigrationJoints[target.id];
        if (old == null) continue;
        for (final entry in target.joints.entries) {
          expect(entry.value.$2, closeTo(old[entry.key]!.$2, 1e-9),
              reason: '${target.id} ${entry.key.name} moved vertically');
        }
      }
    });

    test('on the reference device the change is equivalent, not identical', () {
      // GPT-PM, closing this gate: do not call the conversion bit-exact when
      // the shipped constants are rounded to three decimals. 0.47 * 2/3 is
      // 0.313333..., and 0.313 ships. The claim this gate can actually make is
      // behavioural equivalence on the device the targets were authored for,
      // so it is measured here instead of asserted in prose.
      //
      // Two bounds, both real numbers rather than round ones: the worst
      // coordinate lands 3.33e-4 from the exact quotient, and the worst score
      // lands 2.96e-3 from a perfect match on a 2:3 frame -- against a 0.80
      // pass mark, and against the 0.6 MEAN normalised joint offset at which
      // the whole pose score reaches zero. (0.6 is not a per-joint cutoff:
      // `poseMatchScore` averages every scored joint's offset and divides that
      // mean by 0.6. An earlier draft of this comment and of the decision log
      // called it the point where "a joint stops counting", which would have
      // sent the recalibration gate looking for a landmark rejection rule that
      // does not exist. Caught by GPT-PM reviewing this very correction.)
      //
      // Both maxima are pinned, not merely bounded. They are pure arithmetic
      // on shipped constants, so they can only move if a target moves -- and
      // if one does, the durable claim in the decision log becomes false and
      // this should say so rather than staying green up to a loose ceiling.
      var worstCoord = 0.0;
      var worstScore = 0.0;
      for (final target in allShippedTargets) {
        final old = preMigrationJoints[target.id];
        if (old == null) continue;
        final exact = {
          for (final e in old.entries)
            e.key: (e.value.$1 * 2 / 3 - (shift[target.id] ?? 0.0), e.value.$2),
        };
        for (final e in exact.entries) {
          final d = (target.joints[e.key]!.$1 - e.value.$1).abs();
          if (d > worstCoord) worstCoord = d;
        }
        final score = poseMatchScore(frameFrom(exact), target);
        final d = (1.0 - score!).abs();
        if (d > worstScore) worstScore = d;
      }
      expect(worstCoord, closeTo(3.33e-4, 5e-6),
          reason: 'the decision log records 3.33e-4 as the cost of rounding to '
              'three decimals; it is now '
              '${worstCoord.toStringAsExponential(2)}');
      expect(worstScore, closeTo(2.96e-3, 5e-5),
          reason: 'the decision log records that a body in the exact '
              'pre-migration shape scores 2.96e-3 short of 1.0 on the '
              'reference frame; it is now '
              '${worstScore.toStringAsExponential(2)}');
    });

    test('the table describes the shipped set, not a stale copy of it', () {
      // Guards the `if (old == null) continue` above: without this, deleting a
      // target from the table would quietly stop testing it.
      final shipped = allShippedTargets.map((t) => t.id).toSet();
      expect(preMigrationJoints.keys.toSet().union({'squat.bottom'}),
          equals(shipped),
          reason: 'the pinned table and the shipped targets have diverged');
    });
  });
}
